// 栞 SHIORI — 引用データ
// 実在する名句のみ。出典（作品名）を必ず添える。ハイライトしたい語は *語* で囲む。
// 著者: y=生没年, o=出身, b=ひとこと紹介, born=生年(並び順用, 紀元前は負数), r=地域(jp/east/west)
window.SHIORI_AUTHORS = {
  "山上憶良":{y:"660年頃–733年頃",o:"日本",b:"万葉の歌人。子や貧しさを詠んだ",born:660,r:"jp"},
  "紀貫之":{y:"872年頃–945年",o:"日本",b:"『古今和歌集』撰者。『土佐日記』の作者",born:872,r:"jp"},
  "小野小町":{y:"9世紀",o:"日本",b:"六歌仙のひとり。恋と無常の歌人",born:825,r:"jp"},
  "清少納言":{y:"966年頃–1025年頃",o:"日本",b:"中宮定子に仕えた女房。随筆の祖",born:966,r:"jp"},
  "紫式部":{y:"970年代–1010年代",o:"日本",b:"『源氏物語』の作者。宮廷に仕えた女房",born:973,r:"jp"},
  "西行":{y:"1118–1190",o:"日本",b:"武士から出家した漂泊の歌人",born:1118,r:"jp"},
  "鴨長明":{y:"1155–1216",o:"日本",b:"歌人。晩年は方丈の庵に隠棲した",born:1155,r:"jp"},
  "親鸞":{y:"1173–1263",o:"日本",b:"浄土真宗の開祖。他力の信仰を説いた",born:1173,r:"jp"},
  "平家物語（作者未詳）":{y:"13世紀成立",o:"日本",b:"琵琶法師が語り継いだ軍記物語",born:1220,r:"jp"},
  "道元":{y:"1200–1253",o:"日本",b:"曹洞宗の開祖。只管打坐を説いた禅僧",born:1200,r:"jp"},
  "吉田兼好":{y:"1283年頃–1352年頃",o:"日本",b:"歌人・随筆家。俗世を離れて『徒然草』を著した",born:1283,r:"jp"},
  "世阿弥":{y:"1363年頃–1443年頃",o:"日本",b:"能を大成した役者・作者",born:1363,r:"jp"},
  "千利休":{y:"1522–1591",o:"日本",b:"わび茶を完成させた茶人",born:1522,r:"jp"},
  "宮本武蔵":{y:"1584年頃–1645",o:"日本",b:"二天一流の剣術家。晩年に兵法書を著した",born:1584,r:"jp"},
  "貝原益軒":{y:"1630–1714",o:"日本",b:"江戸前期の儒学者・本草学者",born:1630,r:"jp"},
  "松尾芭蕉":{y:"1644–1694",o:"日本",b:"俳諧を芸術に高めた俳人。旅に生きた",born:1644,r:"jp"},
  "山本常朝":{y:"1659–1719",o:"日本",b:"佐賀藩士。口述が『葉隠』にまとめられた",born:1659,r:"jp"},
  "上杉鷹山":{y:"1751–1822",o:"日本",b:"米沢藩を立て直した名君",born:1751,r:"jp"},
  "良寛":{y:"1758–1831",o:"日本",b:"越後の禅僧・歌人。子どもと手毬で遊んだ",born:1758,r:"jp"},
  "小林一茶":{y:"1763–1828",o:"日本",b:"信濃の俳人。小さな命を詠んだ",born:1763,r:"jp"},
  "佐藤一斎":{y:"1772–1859",o:"日本",b:"幕末の儒学者。多くの志士を育てた",born:1772,r:"jp"},
  "二宮尊徳":{y:"1787–1856",o:"日本",b:"農村復興に尽くした実践家",born:1787,r:"jp"},
  "西郷隆盛":{y:"1828–1877",o:"日本",b:"維新の指導者。遺訓が『南洲翁遺訓』に残る",born:1828,r:"jp"},
  "吉田松陰":{y:"1830–1859",o:"日本",b:"松下村塾で若者を育てた思想家",born:1830,r:"jp"},
  "福澤諭吉":{y:"1835–1901",o:"日本",b:"啓蒙思想家。慶應義塾を創設した",born:1835,r:"jp"},
  "渋沢栄一":{y:"1840–1931",o:"日本",b:"約500の企業を育てた実業家",born:1840,r:"jp"},
  "内村鑑三":{y:"1861–1930",o:"日本",b:"無教会主義のキリスト教思想家",born:1861,r:"jp"},
  "森鷗外":{y:"1862–1922",o:"日本",b:"軍医にして小説家・翻訳家",born:1862,r:"jp"},
  "新渡戸稲造":{y:"1862–1933",o:"日本",b:"教育者。英文で日本の精神を世界に伝えた",born:1862,r:"jp"},
  "岡倉天心":{y:"1863–1913",o:"日本",b:"美術行政家。英文で日本の美を語った",born:1863,r:"jp"},
  "夏目漱石":{y:"1867–1916",o:"日本",b:"近代日本文学を代表する小説家・英文学者",born:1867,r:"jp"},
  "正岡子規":{y:"1867–1902",o:"日本",b:"俳句・短歌を革新した文学者。病床で書き続けた",born:1867,r:"jp"},
  "西田幾多郎":{y:"1870–1945",o:"日本",b:"京都学派を築いた哲学者",born:1870,r:"jp"},
  "島崎藤村":{y:"1872–1943",o:"日本",b:"詩人から小説家へ。自然主義文学の旗手",born:1872,r:"jp"},
  "与謝野晶子":{y:"1878–1942",o:"日本",b:"情熱の歌人。女性の自立を訴えた",born:1878,r:"jp"},
  "有島武郎":{y:"1878–1923",o:"日本",b:"白樺派の小説家",born:1878,r:"jp"},
  "種田山頭火":{y:"1882–1940",o:"日本",b:"自由律俳句の行乞俳人",born:1882,r:"jp"},
  "高村光太郎":{y:"1883–1956",o:"日本",b:"彫刻家・詩人。『智恵子抄』の作者",born:1883,r:"jp"},
  "志賀直哉":{y:"1883–1971",o:"日本",b:"「小説の神様」と呼ばれた白樺派の作家",born:1883,r:"jp"},
  "武者小路実篤":{y:"1885–1976",o:"日本",b:"白樺派の作家。「新しき村」を興した",born:1885,r:"jp"},
  "尾崎放哉":{y:"1885–1926",o:"日本",b:"自由律俳句の俳人。小豆島で没した",born:1885,r:"jp"},
  "石川啄木":{y:"1886–1912",o:"日本",b:"生活を詠んだ夭折の歌人",born:1886,r:"jp"},
  "谷崎潤一郎":{y:"1886–1965",o:"日本",b:"耽美の小説家。『細雪』の作者",born:1886,r:"jp"},
  "芥川龍之介":{y:"1892–1927",o:"日本",b:"短編の名手。芥川賞にその名を残す",born:1892,r:"jp"},
  "松下幸之助":{y:"1894–1989",o:"日本",b:"パナソニック創業者。「経営の神様」",born:1894,r:"jp"},
  "宮沢賢治":{y:"1896–1933",o:"日本",b:"詩人・童話作家。農学校の教師でもあった",born:1896,r:"jp"},
  "三木清":{y:"1897–1945",o:"日本",b:"哲学者。獄中で没した",born:1897,r:"jp"},
  "井伏鱒二":{y:"1898–1993",o:"日本",b:"『山椒魚』『黒い雨』の小説家",born:1898,r:"jp"},
  "川端康成":{y:"1899–1972",o:"日本",b:"日本人初のノーベル文学賞作家",born:1899,r:"jp"},
  "梶井基次郎":{y:"1901–1932",o:"日本",b:"感覚の冴えた短編を残した夭折の作家",born:1901,r:"jp"},
  "堀辰雄":{y:"1904–1953",o:"日本",b:"軽井沢を愛した小説家",born:1904,r:"jp"},
  "坂口安吾":{y:"1906–1955",o:"日本",b:"無頼派の作家・評論家",born:1906,r:"jp"},
  "中原中也":{y:"1907–1937",o:"日本",b:"30歳で世を去った抒情詩人",born:1907,r:"jp"},
  "太宰治":{y:"1909–1948",o:"日本",b:"無頼派の小説家。『人間失格』の作者",born:1909,r:"jp"},
  "中島敦":{y:"1909–1942",o:"日本",b:"漢籍に材をとった短編の名手",born:1909,r:"jp"},
  "神谷美恵子":{y:"1914–1979",o:"日本",b:"精神科医。ハンセン病療養所で人々に寄り添った",born:1914,r:"jp"},

  "孔子":{y:"前551–前479",o:"中国",b:"儒家の祖。弟子との問答が『論語』に残る",born:-551,r:"east"},
  "老子":{y:"前6世紀頃（諸説あり）",o:"中国",b:"道家の祖とされる伝説的な思想家",born:-570,r:"east"},
  "孫子":{y:"前6〜5世紀頃",o:"中国",b:"兵法家。『孫子』の著者とされる",born:-544,r:"east"},
  "ソクラテス":{y:"前470年頃–前399",o:"古代ギリシア",b:"問答で人々を目覚めさせた哲学者。著作は残さなかった",born:-470,r:"west"},
  "アイスキュロス":{y:"前525年頃–前456",o:"古代ギリシア",b:"ギリシア悲劇の父",born:-525,r:"west"},
  "ソポクレス":{y:"前497年頃–前406年頃",o:"古代ギリシア",b:"『オイディプス王』の悲劇詩人",born:-497,r:"west"},
  "ヘラクレイトス":{y:"前540年頃–前480年頃",o:"古代ギリシア",b:"「万物は流転する」の哲学者",born:-540,r:"west"},
  "ブッダ":{y:"前5世紀頃",o:"古代インド",b:"仏教の開祖。教えは弟子たちが伝えた",born:-480,r:"east"},
  "アリストテレス":{y:"前384–前322",o:"古代ギリシア",b:"万学の祖。プラトンの弟子",born:-384,r:"west"},
  "孟子":{y:"前372年頃–前289年頃",o:"中国",b:"性善説を唱えた儒家の思想家",born:-372,r:"east"},
  "荘子":{y:"前369年頃–前286年頃",o:"中国",b:"自由な寓話で世を相対化した思想家",born:-369,r:"east"},
  "エピクロス":{y:"前341–前270",o:"古代ギリシア",b:"心の平静を説いた「庭園」の哲学者",born:-341,r:"west"},
  "司馬遷":{y:"前145年頃–前86年頃",o:"中国",b:"『史記』を完成させた歴史家",born:-145,r:"east"},
  "ウェルギリウス":{y:"前70–前19",o:"古代ローマ",b:"ローマ最大の詩人。『アエネーイス』の作者",born:-70,r:"west"},
  "ホラティウス":{y:"前65–前8",o:"古代ローマ",b:"抒情詩人。「カルペ・ディエム」の人",born:-65,r:"west"},
  "セネカ":{y:"前4年頃–65",o:"古代ローマ",b:"ストア派の哲学者。皇帝ネロの師",born:-4,r:"west"},
  "エピクテトス":{y:"55年頃–135年頃",o:"古代ローマ",b:"奴隷の身から哲学者へ。ストア派",born:55,r:"west"},
  "マルクス・アウレリウス":{y:"121–180",o:"古代ローマ",b:"哲人皇帝。陣中で自分に向けた手記を書いた",born:121,r:"west"},
  "アウグスティヌス":{y:"354–430",o:"北アフリカ・ローマ帝国",b:"教父。『告白』で内面を語った",born:354,r:"west"},
  "陶淵明":{y:"365–427",o:"中国",b:"官を捨て田園に帰った詩人",born:365,r:"east"},
  "杜甫":{y:"712–770",o:"中国",b:"「詩聖」と呼ばれる唐の詩人",born:712,r:"east"},
  "ダンテ":{y:"1265–1321",o:"イタリア",b:"『神曲』でイタリア語文学を築いた詩人",born:1265,r:"west"},
  "マキャヴェリ":{y:"1469–1527",o:"イタリア",b:"フィレンツェの外交官・政治思想家",born:1469,r:"west"},
  "モンテーニュ":{y:"1533–1592",o:"フランス",b:"「エセー（随想録）」という形式を生んだ思索家",born:1533,r:"west"},
  "セルバンテス":{y:"1547–1616",o:"スペイン",b:"近代小説の祖。『ドン・キホーテ』の作者",born:1547,r:"west"},
  "フランシス・ベーコン":{y:"1561–1626",o:"イギリス",b:"経験論の哲学者・政治家",born:1561,r:"west"},
  "シェイクスピア":{y:"1564–1616",o:"イギリス",b:"英語圏最大の劇作家・詩人",born:1564,r:"west"},
  "ジョン・ダン":{y:"1572–1631",o:"イギリス",b:"形而上詩人。聖職者でもあった",born:1572,r:"west"},
  "デカルト":{y:"1596–1650",o:"フランス",b:"近代哲学の父。方法的懐疑",born:1596,r:"west"},
  "ミルトン":{y:"1608–1674",o:"イギリス",b:"失明ののち『失楽園』を口述した詩人",born:1608,r:"west"},
  "ラ・ロシュフコー":{y:"1613–1680",o:"フランス",b:"人間の自己愛を見抜いた箴言家",born:1613,r:"west"},
  "パスカル":{y:"1623–1662",o:"フランス",b:"数学者・物理学者・思想家。39歳で没した",born:1623,r:"west"},
  "スピノザ":{y:"1632–1677",o:"オランダ",b:"レンズ磨きで生計を立てた哲学者",born:1632,r:"west"},
  "ニュートン":{y:"1642–1727",o:"イギリス",b:"万有引力を見出した物理学者",born:1642,r:"west"},
  "ヴォルテール":{y:"1694–1778",o:"フランス",b:"啓蒙の世紀を代表する作家・思想家",born:1694,r:"west"},
  "ルソー":{y:"1712–1778",o:"ジュネーヴ・フランス",b:"『社会契約論』『エミール』の思想家",born:1712,r:"west"},
  "カント":{y:"1724–1804",o:"ドイツ",b:"批判哲学を打ち立てた。生涯ケーニヒスベルクを離れず",born:1724,r:"west"},
  "ゲーテ":{y:"1749–1832",o:"ドイツ",b:"詩人・劇作家・自然科学者。ドイツ文学の巨匠",born:1749,r:"west"},
  "ブレイク":{y:"1757–1827",o:"イギリス",b:"幻視の詩人・版画家",born:1757,r:"west"},
  "オースティン":{y:"1775–1817",o:"イギリス",b:"結婚と家庭を鋭く描いた小説家",born:1775,r:"west"},
  "スタンダール":{y:"1783–1842",o:"フランス",b:"『赤と黒』『パルムの僧院』の小説家",born:1783,r:"west"},
  "ショーペンハウアー":{y:"1788–1860",o:"ドイツ",b:"意志と表象の哲学者。厭世思想で知られる",born:1788,r:"west"},
  "キーツ":{y:"1795–1821",o:"イギリス",b:"25歳で没したロマン派の詩人",born:1795,r:"west"},
  "プーシキン":{y:"1799–1837",o:"ロシア",b:"近代ロシア文学の父",born:1799,r:"west"},
  "ユゴー":{y:"1802–1885",o:"フランス",b:"『レ・ミゼラブル』のロマン主義の巨匠",born:1802,r:"west"},
  "デュマ":{y:"1802–1870",o:"フランス",b:"『三銃士』『モンテ・クリスト伯』の作家",born:1802,r:"west"},
  "エマソン":{y:"1803–1882",o:"アメリカ",b:"超越主義の思想家・随筆家",born:1803,r:"west"},
  "アンデルセン":{y:"1805–1875",o:"デンマーク",b:"貧しい靴屋の子から童話の王へ",born:1805,r:"west"},
  "ダーウィン":{y:"1809–1882",o:"イギリス",b:"進化論を確立した博物学者",born:1809,r:"west"},
  "ディケンズ":{y:"1812–1870",o:"イギリス",b:"ヴィクトリア朝を代表する国民作家",born:1812,r:"west"},
  "キルケゴール":{y:"1813–1855",o:"デンマーク",b:"実存主義の先駆けとなった思想家",born:1813,r:"west"},
  "シャーロット・ブロンテ":{y:"1816–1855",o:"イギリス",b:"『ジェイン・エア』の作者。ブロンテ三姉妹の長女",born:1816,r:"west"},
  "ソロー":{y:"1817–1862",o:"アメリカ",b:"ウォールデン湖畔で自給自足を実験した思想家",born:1817,r:"west"},
  "エミリー・ブロンテ":{y:"1818–1848",o:"イギリス",b:"唯一の長編『嵐が丘』を残した",born:1818,r:"west"},
  "メルヴィル":{y:"1819–1891",o:"アメリカ",b:"船乗りの経験から『白鯨』を書いた",born:1819,r:"west"},
  "ホイットマン":{y:"1819–1892",o:"アメリカ",b:"自由詩でアメリカを歌った詩人",born:1819,r:"west"},
  "ジョージ・エリオット":{y:"1819–1880",o:"イギリス",b:"男性名で書いた女性作家。『ミドルマーチ』",born:1819,r:"west"},
  "ボードレール":{y:"1821–1867",o:"フランス",b:"『悪の華』の詩人。近代詩の出発点",born:1821,r:"west"},
  "ドストエフスキー":{y:"1821–1881",o:"ロシア",b:"人間の深淵を描いた小説家。死刑宣告を経験した",born:1821,r:"west"},
  "トルストイ":{y:"1828–1910",o:"ロシア",b:"『戦争と平和』の文豪。晩年は思想家として生きた",born:1828,r:"west"},
  "ディキンソン":{y:"1830–1886",o:"アメリカ",b:"生前ほぼ無名のまま約1800篇の詩を残した",born:1830,r:"west"},
  "ルイス・キャロル":{y:"1832–1898",o:"イギリス",b:"数学者にして『アリス』の作者",born:1832,r:"west"},
  "マーク・トウェイン":{y:"1835–1910",o:"アメリカ",b:"ミシシッピ川を描いたユーモア作家",born:1835,r:"west"},
  "ニーチェ":{y:"1844–1900",o:"ドイツ",b:"「神は死んだ」と告げた哲学者",born:1844,r:"west"},
  "ワイルド":{y:"1854–1900",o:"アイルランド",b:"機知に富む劇作家・小説家",born:1854,r:"west"},
  "タゴール":{y:"1861–1941",o:"インド",b:"アジア初のノーベル文学賞詩人",born:1861,r:"east"},
  "アラン":{y:"1868–1951",o:"フランス",b:"高校教師として書き続けた哲学者。本名エミール・シャルティエ",born:1868,r:"west"},
  "プルースト":{y:"1871–1922",o:"フランス",b:"『失われた時を求めて』に生涯を捧げた",born:1871,r:"west"},
  "リルケ":{y:"1875–1926",o:"オーストリア",b:"孤独と内面を歌った詩人",born:1875,r:"west"},
  "ヘッセ":{y:"1877–1962",o:"ドイツ・スイス",b:"『車輪の下』『デミアン』の作家",born:1877,r:"west"},
  "アインシュタイン":{y:"1879–1955",o:"ドイツ・アメリカ",b:"相対性理論の物理学者",born:1879,r:"west"},
  "ヘレン・ケラー":{y:"1880–1968",o:"アメリカ",b:"視覚と聴覚を失いながら著述家・活動家として生きた",born:1880,r:"west"},
  "ジョイス":{y:"1882–1941",o:"アイルランド",b:"『ユリシーズ』で小説を変えた",born:1882,r:"west"},
  "ウルフ":{y:"1882–1941",o:"イギリス",b:"意識の流れを描いた小説家・批評家",born:1882,r:"west"},
  "カフカ":{y:"1883–1924",o:"プラハ",b:"保険局員として働きながら書いた。生前はほぼ無名",born:1883,r:"west"},
  "ジブラーン":{y:"1883–1931",o:"レバノン・アメリカ",b:"『預言者』の詩人・画家",born:1883,r:"east"},
  "デール・カーネギー":{y:"1888–1955",o:"アメリカ",b:"話し方と人間関係の教育者",born:1888,r:"west"},
  "ヴィトゲンシュタイン":{y:"1889–1951",o:"オーストリア・イギリス",b:"言語の哲学者。庭師や小学校教師も務めた",born:1889,r:"west"},
  "トールキン":{y:"1892–1973",o:"イギリス",b:"言語学者にして『指輪物語』の作者",born:1892,r:"west"},
  "フィッツジェラルド":{y:"1896–1940",o:"アメリカ",b:"ジャズ・エイジを描いた小説家",born:1896,r:"west"},
  "ヘミングウェイ":{y:"1899–1961",o:"アメリカ",b:"簡潔な文体で20世紀文学を変えた",born:1899,r:"west"},
  "ボルヘス":{y:"1899–1986",o:"アルゼンチン",b:"迷宮と図書館の作家。晩年は失明した",born:1899,r:"west"},
  "サン＝テグジュペリ":{y:"1900–1944",o:"フランス",b:"飛行士にして作家。偵察飛行中に消息を絶った",born:1900,r:"west"},
  "スタインベック":{y:"1902–1968",o:"アメリカ",b:"『怒りの葡萄』『エデンの東』の作家",born:1902,r:"west"},
  "オーウェル":{y:"1903–1950",o:"イギリス",b:"全体主義を見つめた作家・ジャーナリスト",born:1903,r:"west"},
  "サルトル":{y:"1905–1980",o:"フランス",b:"実存主義の哲学者・作家。ノーベル賞を辞退した",born:1905,r:"west"},
  "フランクル":{y:"1905–1997",o:"オーストリア",b:"強制収容所を生き延びた精神科医",born:1905,r:"west"},
  "ボーヴォワール":{y:"1908–1986",o:"フランス",b:"『第二の性』の哲学者・作家",born:1908,r:"west"},
  "カミュ":{y:"1913–1960",o:"フランス（アルジェリア生まれ）",b:"不条理を見つめた作家。44歳でノーベル賞",born:1913,r:"west"},
  "ガルシア＝マルケス":{y:"1927–2014",o:"コロンビア",b:"魔術的リアリズムの作家",born:1927,r:"west"},
  "アンネ・フランク":{y:"1929–1945",o:"ドイツ・オランダ",b:"隠れ家で日記を書き続けた少女",born:1929,r:"west"},
  "額田王":{y:"7世紀",o:"日本",b:"万葉初期の女性歌人。天智・天武に仕えた",born:630,r:"jp"},
  "柿本人麻呂":{y:"660年頃–724年頃",o:"日本",b:"万葉の歌聖。壮大な長歌で知られる",born:661,r:"jp"},
  "大伴家持":{y:"718年頃–785",o:"日本",b:"『万葉集』の編纂に関わった歌人・官人",born:718,r:"jp"},
  "在原業平":{y:"825–880",o:"日本",b:"六歌仙のひとり。『伊勢物語』の主人公とされる",born:826,r:"jp"},
  "藤原定家":{y:"1162–1241",o:"日本",b:"『新古今和歌集』の撰者。百人一首を選んだ",born:1162,r:"jp"},
  "空海":{y:"774–835",o:"日本",b:"真言宗の開祖。唐に学び高野山を開いた",born:774,r:"jp"},
  "最澄":{y:"767–822",o:"日本",b:"天台宗の開祖。比叡山に延暦寺を開いた",born:767,r:"jp"},
  "明恵":{y:"1173–1232",o:"日本",b:"華厳宗の僧。夢を記録し続けた",born:1174,r:"jp"},
  "日蓮":{y:"1222–1282",o:"日本",b:"日蓮宗の開祖。法華経に生きた",born:1222,r:"jp"},
  "一休宗純":{y:"1394–1481",o:"日本",b:"型破りな禅僧。詩と風狂で知られる",born:1394,r:"jp"},
  "白隠慧鶴":{y:"1686–1769",o:"日本",b:"臨済宗中興の祖。禅を民衆に広めた",born:1686,r:"jp"},
  "近松門左衛門":{y:"1653–1725",o:"日本",b:"浄瑠璃・歌舞伎の作者。心中物の名手",born:1653,r:"jp"},
  "与謝蕪村":{y:"1716–1784",o:"日本",b:"画家でもあった俳人。絵のような句を詠んだ",born:1716,r:"jp"},
  "本居宣長":{y:"1730–1801",o:"日本",b:"国学者。『古事記伝』に三十余年を費やした",born:1730,r:"jp"},
  "勝海舟":{y:"1823–1899",o:"日本",b:"幕臣。江戸無血開城を導いた",born:1823,r:"jp"},
  "坂本龍馬":{y:"1836–1867",o:"日本",b:"土佐の志士。薩長同盟を仲介した",born:1836,r:"jp"},
  "高杉晋作":{y:"1839–1867",o:"日本",b:"長州の志士。奇兵隊を創った",born:1839,r:"jp"},
  "尾崎紅葉":{y:"1868–1903",o:"日本",b:"硯友社の中心。『金色夜叉』の作者",born:1868,r:"jp"},
  "樋口一葉":{y:"1872–1896",o:"日本",b:"二十四歳で没した明治の女性作家",born:1872,r:"jp"},
  "国木田独歩":{y:"1871–1908",o:"日本",b:"自然主義の先駆。『武蔵野』で知られる",born:1871,r:"jp"},
  "高浜虚子":{y:"1874–1959",o:"日本",b:"子規の後継。「ホトトギス」を率いた俳人",born:1874,r:"jp"},
  "野口英世":{y:"1876–1928",o:"日本",b:"細菌学者。黄熱病の研究に生涯を捧げた",born:1876,r:"jp"},
  "寺田寅彦":{y:"1878–1935",o:"日本",b:"物理学者にして随筆家。漱石の弟子",born:1878,r:"jp"},
  "北原白秋":{y:"1885–1942",o:"日本",b:"詩人・童謡作家。豊かな言葉の魔術師",born:1885,r:"jp"},
  "若山牧水":{y:"1885–1928",o:"日本",b:"旅と酒を愛した歌人",born:1885,r:"jp"},
  "山村暮鳥":{y:"1884–1924",o:"日本",b:"牧師でもあった詩人。素朴な詩を残した",born:1884,r:"jp"},
  "萩原朔太郎":{y:"1886–1942",o:"日本",b:"口語自由詩を完成させた詩人",born:1886,r:"jp"},
  "室生犀星":{y:"1889–1962",o:"日本",b:"金沢生まれの詩人・小説家",born:1889,r:"jp"},
  "岡本かの子":{y:"1889–1939",o:"日本",b:"歌人・小説家。岡本太郎の母",born:1889,r:"jp"},
  "佐藤春夫":{y:"1892–1964",o:"日本",b:"詩人・小説家。「秋刀魚の歌」で知られる",born:1892,r:"jp"},
  "吉川英治":{y:"1892–1962",o:"日本",b:"国民的作家。『宮本武蔵』『三国志』",born:1892,r:"jp"},
  "八木重吉":{y:"1898–1927",o:"日本",b:"二十九歳で没した詩人。静かな信仰の詩",born:1898,r:"jp"},
  "三好達治":{y:"1900–1964",o:"日本",b:"抒情詩人。『測量船』の作者",born:1900,r:"jp"},
  "中村草田男":{y:"1901–1983",o:"日本",b:"人間探求派と呼ばれた俳人",born:1901,r:"jp"},
  "小林秀雄":{y:"1902–1983",o:"日本",b:"近代日本の批評を確立した",born:1902,r:"jp"},
  "金子みすゞ":{y:"1903–1930",o:"日本",b:"童謡詩人。没後半世紀を経て再発見された",born:1903,r:"jp"},
  "林芙美子":{y:"1903–1951",o:"日本",b:"『放浪記』の作者。庶民の生活を描いた",born:1903,r:"jp"},
  "新美南吉":{y:"1913–1943",o:"日本",b:"『ごんぎつね』の童話作家。二十九歳で没",born:1913,r:"jp"},
  "立原道造":{y:"1914–1939",o:"日本",b:"建築家でもあった抒情詩人。二十四歳で没",born:1914,r:"jp"},
  "茨木のり子":{y:"1926–2006",o:"日本",b:"戦後を代表する女性詩人。凛とした言葉",born:1926,r:"jp"},
  "谷川俊太郎":{y:"1931–2024",o:"日本",b:"国民的詩人。平明な言葉で宇宙を詠んだ",born:1931,r:"jp"},
  "石垣りん":{y:"1920–2004",o:"日本",b:"銀行に勤めながら詩を書いた「生活の詩人」",born:1920,r:"jp"},
  "寺山修司":{y:"1935–1983",o:"日本",b:"歌人・劇作家・映画監督。言葉の錬金術師",born:1935,r:"jp"},
  "俵万智":{y:"1962–",o:"日本",b:"口語短歌を広めた歌人。『サラダ記念日』",born:1962,r:"jp"},
  "岡本太郎":{y:"1911–1996",o:"日本",b:"「太陽の塔」の芸術家。爆発する情熱",born:1911,r:"jp"},
  "相田みつを":{y:"1924–1991",o:"日本",b:"書家・詩人。平仮名の言葉で人を励ました",born:1924,r:"jp"},
  "湯川秀樹":{y:"1907–1981",o:"日本",b:"日本人初のノーベル賞。中間子論の物理学者",born:1907,r:"jp"},
  "山本五十六":{y:"1884–1943",o:"日本",b:"海軍の司令長官。人を育てる言葉を残した",born:1884,r:"jp"},
  "稲盛和夫":{y:"1932–2022",o:"日本",b:"京セラ・KDDIの創業者。JALを再建した",born:1932,r:"jp"},
  "安藤百福":{y:"1910–2007",o:"日本",b:"インスタントラーメンの発明者。日清食品の創業者",born:1910,r:"jp"},
  "『易経』（作者未詳）":{y:"周代成立",o:"中国",b:"五経のひとつ。変化の哲学を説く占いの書",born:-800,r:"east"},
  "屈原":{y:"前340年頃–前278年頃",o:"中国",b:"楚の詩人・政治家。『楚辞』の作者",born:-340,r:"east"},
  "荀子":{y:"前313年頃–前238年頃",o:"中国",b:"性悪説を唱えた儒家。学びを重んじた",born:-313,r:"east"},
  "『大学』（作者未詳）":{y:"戦国〜漢代成立",o:"中国",b:"四書のひとつ。修身から天下までを説く",born:-300,r:"east"},
  "『バガヴァッド・ギーター』（作者未詳）":{y:"前2世紀頃成立",o:"古代インド",b:"叙事詩の一部。行為の教えを説く聖典",born:-200,r:"east"},
  "諸葛亮":{y:"181–234",o:"中国",b:"蜀の丞相。『出師表』で知られる軍師",born:181,r:"east"},
  "王維":{y:"699年頃–761",o:"中国",b:"詩仏と呼ばれた唐の詩人・画家",born:699,r:"east"},
  "李白":{y:"701–762",o:"中国",b:"詩仙。酒と月を愛した唐の詩人",born:701,r:"east"},
  "白居易":{y:"772–846",o:"中国",b:"平易な詩で愛された唐の詩人",born:772,r:"east"},
  "蘇軾":{y:"1037–1101",o:"中国",b:"宋の詩人・書家。蘇東坡の名で親しまれる",born:1037,r:"east"},
  "オマル・ハイヤーム":{y:"1048–1131",o:"ペルシア",b:"数学者・天文学者にして四行詩の詩人",born:1048,r:"east"},
  "サアディー":{y:"1210年頃–1291年頃",o:"ペルシア",b:"『薔薇園』を書いた旅の詩人",born:1210,r:"east"},
  "王陽明":{y:"1472–1529",o:"中国",b:"知行合一を説いた明の儒学者",born:1472,r:"east"},
  "洪自誠":{y:"16〜17世紀",o:"中国",b:"『菜根譚』の著者。処世の知恵を説いた",born:1573,r:"east"},
  "魯迅":{y:"1881–1936",o:"中国",b:"近代中国文学の父。『阿Q正伝』",born:1881,r:"east"},
  "ガンディー":{y:"1869–1948",o:"インド",b:"非暴力でインド独立を導いた",born:1869,r:"east"},
  "プラトン":{y:"前427年頃–前347年頃",o:"古代ギリシア",b:"ソクラテスの弟子。アカデメイアを開いた",born:-427,r:"west"},
  "キケロ":{y:"前106–前43",o:"古代ローマ",b:"弁論家・政治家。ラテン散文の模範",born:-106,r:"west"},
  "オウィディウス":{y:"前43–17年頃",o:"古代ローマ",b:"『変身物語』の詩人。黒海のほとりに流された",born:-43,r:"west"},
  "トマス・ア・ケンピス":{y:"1380年頃–1471",o:"ドイツ・オランダ",b:"修道士。『キリストにならいて』の著者とされる",born:1380,r:"west"},
  "レオナルド・ダ・ヴィンチ":{y:"1452–1519",o:"イタリア",b:"万能の人。絵画・解剖・機械を手記に残した",born:1452,r:"west"},
  "エラスムス":{y:"1466年頃–1536",o:"オランダ",b:"ルネサンスの人文学者。『痴愚神礼賛』",born:1466,r:"west"},
  "ラブレー":{y:"1483年頃–1553",o:"フランス",b:"医師にして笑いの作家。『ガルガンチュア』",born:1483,r:"west"},
  "ガリレオ":{y:"1564–1642",o:"イタリア",b:"望遠鏡で天を観た近代科学の父",born:1564,r:"west"},
  "ホッブズ":{y:"1588–1679",o:"イギリス",b:"『リヴァイアサン』の政治哲学者",born:1588,r:"west"},
  "ラ・フォンテーヌ":{y:"1621–1695",o:"フランス",b:"動物たちに人間を語らせた寓話詩人",born:1621,r:"west"},
  "ラ・ブリュイエール":{y:"1645–1696",o:"フランス",b:"『カラクテール』で人間の性格を描いた",born:1645,r:"west"},
  "ポープ":{y:"1688–1744",o:"イギリス",b:"十八世紀イギリスを代表する詩人",born:1688,r:"west"},
  "ベンジャミン・フランクリン":{y:"1706–1790",o:"アメリカ",b:"印刷工から建国の父へ。避雷針の発明者",born:1706,r:"west"},
  "サミュエル・ジョンソン":{y:"1709–1784",o:"イギリス",b:"英語辞典をひとりで編んだ文人",born:1709,r:"west"},
  "アダム・スミス":{y:"1723–1790",o:"イギリス（スコットランド）",b:"『国富論』で経済学を築いた",born:1723,r:"west"},
  "シラー":{y:"1759–1805",o:"ドイツ",b:"ゲーテの盟友。『群盗』『ヴィルヘルム・テル』",born:1759,r:"west"},
  "ワーズワース":{y:"1770–1850",o:"イギリス",b:"湖水地方の自然を詠んだロマン派詩人",born:1770,r:"west"},
  "ヘーゲル":{y:"1770–1831",o:"ドイツ",b:"弁証法で歴史を捉えた哲学者",born:1770,r:"west"},
  "バイロン":{y:"1788–1824",o:"イギリス",b:"放浪のロマン派詩人。ギリシア独立戦争に赴いた",born:1788,r:"west"},
  "シェリー":{y:"1792–1822",o:"イギリス",b:"ロマン派詩人。二十九歳で海に没した",born:1792,r:"west"},
  "ハイネ":{y:"1797–1856",o:"ドイツ",b:"抒情と風刺の詩人。パリに亡命した",born:1797,r:"west"},
  "バルザック":{y:"1799–1850",o:"フランス",b:"『人間喜劇』で社会全体を描こうとした",born:1799,r:"west"},
  "テニスン":{y:"1809–1892",o:"イギリス",b:"ヴィクトリア朝の桂冠詩人",born:1809,r:"west"},
  "リンカーン":{y:"1809–1865",o:"アメリカ",b:"第十六代大統領。奴隷解放を成し遂げた",born:1809,r:"west"},
  "ブラウニング":{y:"1812–1889",o:"イギリス",b:"劇的独白の詩人。上田敏訳で日本に知られた",born:1812,r:"west"},
  "マルクス":{y:"1818–1883",o:"ドイツ",b:"『資本論』の思想家。世界を変えようとした",born:1818,r:"west"},
  "パスツール":{y:"1822–1895",o:"フランス",b:"微生物学の父。狂犬病ワクチンを開発した",born:1822,r:"west"},
  "イプセン":{y:"1828–1906",o:"ノルウェー",b:"近代劇の父。『人形の家』",born:1828,r:"west"},
  "スティーヴンソン":{y:"1850–1894",o:"イギリス（スコットランド）",b:"『宝島』『ジキル博士とハイド氏』の作家",born:1850,r:"west"},
  "ゴッホ":{y:"1853–1890",o:"オランダ",b:"生前ほとんど売れなかった画家。弟テオへの手紙",born:1853,r:"west"},
  "コナン・ドイル":{y:"1859–1930",o:"イギリス",b:"シャーロック・ホームズを生んだ医師",born:1859,r:"west"},
  "チェーホフ":{y:"1860–1904",o:"ロシア",b:"医師にして短篇と戯曲の名手",born:1860,r:"west"},
  "サンタヤーナ":{y:"1863–1952",o:"スペイン・アメリカ",b:"哲学者・詩人。『理性の生活』",born:1863,r:"west"},
  "イェイツ":{y:"1865–1939",o:"アイルランド",b:"アイルランド文芸復興の詩人",born:1865,r:"west"},
  "キプリング":{y:"1865–1936",o:"イギリス",b:"『ジャングル・ブック』の作家。詩「もし」",born:1865,r:"west"},
  "ロマン・ロラン":{y:"1866–1944",o:"フランス",b:"『ジャン・クリストフ』の作家。平和主義者",born:1866,r:"west"},
  "ジッド":{y:"1869–1951",o:"フランス",b:"『狭き門』『地の糧』の作家",born:1869,r:"west"},
  "ラッセル":{y:"1872–1970",o:"イギリス",b:"論理学者・哲学者。反核運動にも尽くした",born:1872,r:"west"},
  "チェスタトン":{y:"1874–1936",o:"イギリス",b:"逆説の名手。ブラウン神父の生みの親",born:1874,r:"west"},
  "チャーチル":{y:"1874–1965",o:"イギリス",b:"戦時の首相。文筆でノーベル文学賞",born:1874,r:"west"},
  "シュヴァイツァー":{y:"1875–1965",o:"ドイツ・フランス",b:"アフリカで医療に尽くした医師・神学者",born:1875,r:"west"},
  "ユング":{y:"1875–1961",o:"スイス",b:"分析心理学の創始者。元型と集合的無意識",born:1875,r:"west"},
  "ブレヒト":{y:"1898–1956",o:"ドイツ",b:"異化効果の劇作家。『三文オペラ』",born:1898,r:"west"},
  "ケストナー":{y:"1899–1974",o:"ドイツ",b:"『飛ぶ教室』『エーミールと探偵たち』の作家",born:1899,r:"west"},
  "ハンナ・アーレント":{y:"1906–1975",o:"ドイツ・アメリカ",b:"全体主義を考え抜いた政治哲学者",born:1906,r:"west"},
  "ベケット":{y:"1906–1989",o:"アイルランド",b:"『ゴドーを待ちながら』の劇作家",born:1906,r:"west"},
  "レイチェル・カーソン":{y:"1907–1964",o:"アメリカ",b:"『沈黙の春』で環境問題を告発した",born:1907,r:"west"},
  "シモーヌ・ヴェイユ":{y:"1909–1943",o:"フランス",b:"工場で働いた哲学者。三十四歳で没",born:1909,r:"west"},
  "ケネディ":{y:"1917–1963",o:"アメリカ",b:"第三十五代大統領。ニューフロンティア",born:1917,r:"west"},
  "ファインマン":{y:"1918–1988",o:"アメリカ",b:"ノーベル賞物理学者。教えることの名人",born:1918,r:"west"},
  "ヴォネガット":{y:"1922–2007",o:"アメリカ",b:"『スローターハウス5』のユーモアと悲しみ",born:1922,r:"west"},
  "キング牧師":{y:"1929–1968",o:"アメリカ",b:"公民権運動の指導者。非暴力の行進",born:1929,r:"west"},
};

// 引用: a=著者, w=出典, t=本文(日本語), x=原文(あれば), m=図版 (book/quill/lamp/hourglass/laurel/candle/moon)
window.SHIORI_QUOTES = [
  // ── 日本 ──
  {a:"山上憶良",w:"『万葉集』巻五",t:"銀も金も玉も何せむに 勝れる宝 *子*に及かめやも",e:"Silver, gold, and jewels — what are they worth? No treasure surpasses a child.",m:"moon"},
  {a:"紀貫之",w:"『古今和歌集』仮名序",t:"やまとうたは、人の*心*を種として、よろづの言の葉とぞなれりける。",e:"Japanese poetry has the human heart as its seed, and grows into countless leaves of words.",m:"quill"},
  {a:"小野小町",w:"『古今和歌集』",t:"*花の色*は移りにけりな いたづらに わが身世にふる ながめせしまに",e:"The color of the flowers has faded away, while I idly gazed at the long rains, my life passing in this world.",m:"hourglass"},
  {a:"清少納言",w:"『枕草子』",t:"春は*あけぼの*。やうやう白くなりゆく山ぎは、少しあかりて、紫だちたる雲の細くたなびきたる。",e:"In spring, the dawn. The rim of the mountains slowly whitens, brightening a little, and slender clouds tinged with purple trail across it.",m:"moon"},
  {a:"紫式部",w:"『源氏物語』桐壺",t:"いづれの御時にか、女御、更衣あまたさぶらひたまひける中に、いとやむごとなき際にはあらぬが、すぐれて*時めき*たまふありけり。",e:"In a certain reign, among the many consorts and ladies who served the Emperor, there was one who, though not of the highest rank, was favored far above all the others.",m:"book"},
  {a:"西行",w:"『山家集』",t:"願はくは *花*の下にて春死なむ その如月の望月のころ",e:"Let me die in spring, beneath the blossoms, around the full moon of the second month.",m:"moon"},
  {a:"鴨長明",w:"『方丈記』",t:"ゆく河の流れは絶えずして、しかももとの水にあらず。よどみに浮かぶ*うたかた*は、かつ消えかつ結びて、久しくとどまりたるためしなし。",e:"The flowing river never ceases, yet its water is never the same. The foam that floats on the pools, now vanishing, now forming, never stays for long.",m:"hourglass"},
  {a:"鴨長明",w:"『方丈記』",t:"知らず、生まれ死ぬる人、いづかたより来たりて、いづかたへか*去る*。",e:"I do not know: those who are born and those who die, whence do they come, and whither do they go?",m:"hourglass"},
  {a:"親鸞",w:"『歎異抄』（唯円編）",t:"善人なほもて往生をとぐ、いはんや*悪人*をや。",e:"Even a good person attains birth in the Pure Land; how much more so an evil person.",m:"candle"},
  {a:"平家物語（作者未詳）",w:"『平家物語』",t:"祇園精舎の鐘の声、*諸行無常*の響きあり。沙羅双樹の花の色、盛者必衰の理をあらはす。",e:"The bell of the Gion temple tolls the impermanence of all things. The color of the sala flowers reveals the truth that the prosperous must decline.",m:"hourglass"},
  {a:"道元",w:"『正法眼蔵』現成公案",t:"仏道をならふといふは、*自己*をならふなり。自己をならふといふは、自己をわするるなり。",e:"To study the Buddha Way is to study the self. To study the self is to forget the self.",m:"lamp"},
  {a:"吉田兼好",w:"『徒然草』序段",t:"つれづれなるままに、日暮らし、硯にむかひて、心にうつりゆく*よしなし事*を、そこはかとなく書きつくれば、あやしうこそものぐるほしけれ。",e:"With nothing better to do, I sit all day before the inkstone, jotting down whatever trifles drift through my mind, and a strange madness comes over me.",m:"quill"},
  {a:"吉田兼好",w:"『徒然草』第九十二段",t:"初心の人、*二つの矢*を持つことなかれ。後の矢を頼みて、始めの矢になほざりの心あり。",e:"A beginner should not hold two arrows. Counting on the second, he grows careless with the first.",m:"laurel"},
  {a:"吉田兼好",w:"『徒然草』第百三十七段",t:"花は*盛り*に、月は隈なきをのみ、見るものかは。",e:"Are blossoms to be seen only in full bloom, and the moon only when unclouded?",m:"moon"},
  {a:"吉田兼好",w:"『徒然草』第百五十段",t:"天下のものの*上手*といへども、始めは不堪の聞こえもあり、無下の瑕瑾もありき。",e:"Even the greatest masters in the land were once called clumsy, and bore glaring faults.",m:"laurel"},
  {a:"世阿弥",w:"『花鏡』",t:"*初心*忘るべからず。",e:"Never forget the beginner's heart.",m:"laurel"},
  {a:"世阿弥",w:"『風姿花伝』",t:"秘すれば*花*なり。秘せずは花なるべからず。",e:"What is hidden is the flower. What is not hidden cannot be the flower.",m:"moon"},
  {a:"千利休",w:"『利休百首』（伝）",t:"稽古とは *一*より習ひ十を知り 十よりかへる もとのその一",e:"Practice is this: learn from one to ten, then return from ten to the first one.",m:"laurel"},
  {a:"宮本武蔵",w:"『五輪書』水の巻",t:"千日の稽古を鍛とし、万日の稽古を*錬*とす。",e:"A thousand days of practice to forge; ten thousand days of practice to refine.",m:"laurel"},
  {a:"山本常朝",w:"『葉隠』",t:"武士道といふは、*死ぬ事*と見付けたり。",e:"The Way of the warrior, I have found, is death.",m:"hourglass"},
  {a:"貝原益軒",w:"『養生訓』",t:"養生の術は、まづ*心気*を養ふべし。",e:"The art of nourishing life begins with nourishing the heart and spirit.",m:"lamp"},
  {a:"松尾芭蕉",w:"『おくのほそ道』",t:"月日は*百代の過客*にして、行きかふ年もまた旅人なり。",e:"The months and days are travelers of eternity; the years that come and go are travelers too.",m:"hourglass"},
  {a:"松尾芭蕉",w:"『おくのほそ道』",t:"夏草や 兵どもが *夢*の跡",e:"Summer grasses: all that remains of warriors' dreams.",m:"moon"},
  {a:"松尾芭蕉",w:"『蛙合』",t:"古池や 蛙飛びこむ *水の音*",e:"An old pond. A frog leaps in. The sound of water.",m:"moon"},
  {a:"上杉鷹山",w:"伝・家臣への歌",t:"*為せば成る* 為さねば成らぬ何事も 成らぬは人の為さぬなりけり",e:"If you act, it will be done; if you do not, it will not. Whatever fails, fails because no one acted.",m:"laurel"},
  {a:"良寛",w:"山田杜皐宛の手紙",t:"災難に逢う時節には災難に逢うがよく候。死ぬ時節には死ぬがよく候。是はこれ災難をのがるる*妙法*にて候。",e:"When disaster comes, it is well to meet disaster. When it is time to die, it is well to die. This is the secret art of escaping disaster.",m:"candle"},
  {a:"小林一茶",w:"『おらが春』",t:"目出度さも *ちう位*也 おらが春",e:"New Year's joy: a middling sort of joy, this spring of mine.",m:"moon"},
  {a:"佐藤一斎",w:"『言志晩録』",t:"少にして学べば、則ち壮にして為すこと有り。壮にして学べば、則ち老いて衰へず。老いて学べば、則ち死して*朽ちず*。",e:"Learn in youth, and you will achieve in your prime. Learn in your prime, and you will not decline in old age. Learn in old age, and you will not decay in death.",m:"book"},
  {a:"二宮尊徳",w:"『二宮翁夜話』",t:"*小*を積みて大と為す。",e:"Accumulate the small to make the great.",m:"laurel"},
  {a:"西郷隆盛",w:"『南洲翁遺訓』",t:"命もいらず、名もいらず、官位も金もいらぬ人は、*始末に困る*もの也。",e:"One who wants neither life, nor fame, nor rank, nor money is a hard person to deal with.",m:"lamp"},
  {a:"吉田松陰",w:"「士規七則」",t:"*志*を立てて以て万事の源と為す。",e:"Set your resolve, and make it the source of all things.",m:"laurel"},
  {a:"福澤諭吉",w:"『学問のすすめ』初編",t:"*天*は人の上に人を造らず、人の下に人を造らずと言えり。",e:"It is said that Heaven creates no one above another, and no one below another.",m:"book"},
  {a:"福澤諭吉",w:"『学問のすすめ』三編",t:"一身独立して*一国独立*す。",e:"When each person is independent, the nation is independent.",m:"laurel"},
  {a:"渋沢栄一",w:"『論語と算盤』",t:"正しい道理の富でなければ、その富は完全に*永続*することができぬ。",e:"Unless wealth is gained by right principle, that wealth can never truly last.",m:"lamp"},
  {a:"内村鑑三",w:"『後世への最大遺物』",t:"後世への最大遺物とは何であるか。私は、それは*勇ましい高尚なる生涯*であると思います。",e:"What is the greatest legacy we can leave to posterity? I believe it is a brave and noble life.",m:"candle"},
  {a:"森鷗外",w:"『高瀬舟』",t:"人は身に病があると、この病がなかったらと思う。蓄えがあっても、またその蓄えがもっと多かったらと思う。人はどこまで行って*踏み止まる*ことができるものやら分からない。",e:"When we are ill, we wish we were not. Even with savings, we wish we had more. Thinking on and on like this, there is no telling where a person could ever stop.",m:"lamp"},
  {a:"新渡戸稲造",w:"『武士道』",t:"武士道は、その象徴である*桜*と同じく、日本の土壌に固有の花である。",x:"Chivalry is a flower no less indigenous to the soil of Japan than its emblem, the cherry blossom.",m:"moon"},
  {a:"岡倉天心",w:"『茶の本』",t:"茶道とは、日常の俗事のただ中にある*美*しきものを崇める、ひとつの儀式である。",x:"Teaism is a cult founded on the adoration of the beautiful among the sordid facts of everyday existence.",m:"lamp"},
  {a:"夏目漱石",w:"『吾輩は猫である』",t:"吾輩は*猫*である。名前はまだ無い。",e:"I am a cat. As yet I have no name.",m:"book"},
  {a:"夏目漱石",w:"『草枕』",t:"智に働けば角が立つ。情に棹させば流される。意地を通せば窮屈だ。とかくに人の世は*住みにくい*。",e:"Use your intellect and you grow harsh. Give in to feeling and you are swept away. Insist on your will and you are hemmed in. Whichever way, this world is hard to live in.",m:"lamp"},
  {a:"夏目漱石",w:"『三四郎』",t:"日本より*頭の中*のほうが広いでしょう。とらわれちゃだめだ。",e:"The inside of your head is wider than Japan. Don't let yourself be trapped.",m:"book"},
  {a:"夏目漱石",w:"『こころ』",t:"精神的に*向上心*のないものは、馬鹿だ。",e:"Anyone with no wish to improve in spirit is a fool.",m:"lamp"},
  {a:"夏目漱石",w:"『私の個人主義』",t:"私はこの*自己本位*という言葉を自分の手に握ってから大変強くなりました。",e:"Once I grasped the phrase 'self-centered' in my own hands, I grew very strong.",m:"quill"},
  {a:"夏目漱石",w:"『坊っちゃん』",t:"親譲りの*無鉄砲*で小供の時から損ばかりしている。",e:"Reckless by nature, I have been losing out ever since I was a child.",m:"book"},
  {a:"正岡子規",w:"『病牀六尺』",t:"悟りといふ事は如何なる場合にも平気で死ぬる事かと思つて居たのは間違で、悟りといふ事は如何なる場合にも*平気で生きて居る*事であつた。",e:"I had thought enlightenment meant being able to die calmly in any circumstance. I was wrong. Enlightenment means being able to live calmly in any circumstance.",m:"candle"},
  {a:"西田幾多郎",w:"『善の研究』",t:"善とは一言にていえば*人格*の実現である。",e:"In a word, the good is the realization of personality.",m:"lamp"},
  {a:"島崎藤村",w:"『若菜集』「初恋」",t:"まだあげ初めし前髪の *林檎*のもとに見えしとき",e:"When first I saw you, your hair just put up, beneath the apple tree.",m:"moon"},
  {a:"与謝野晶子",w:"『みだれ髪』",t:"やは肌のあつき血汐にふれも見で さびしからずや *道*を説く君",e:"You who preach the Way, never touching the hot blood beneath this soft skin: are you not lonely?",m:"quill"},
  {a:"有島武郎",w:"『小さき者へ』",t:"前途は遠い。そして暗い。然し恐れてはならぬ。*恐れない者*の前に道は開ける。",e:"The road ahead is long, and dark. But do not fear. Before those who do not fear, the road opens.",m:"candle"},
  {a:"種田山頭火",w:"『草木塔』",t:"分け入っても分け入っても*青い山*",e:"Pushing on, pushing on, still the blue mountains.",m:"moon"},
  {a:"高村光太郎",w:"『道程』",t:"僕の前に道はない 僕の後ろに*道*は出来る",e:"There is no road before me. Behind me, a road is made.",m:"laurel"},
  {a:"志賀直哉",w:"『城の崎にて』",t:"生きている事と死んでしまっている事と、それは*両極*ではなかった。それ程に差はないような気がした。",e:"Being alive and being dead were not opposite poles. It seemed there was not much difference between them.",m:"hourglass"},
  {a:"武者小路実篤",w:"色紙の言葉",t:"この道より我を生かす道なし *この道*を歩く",e:"There is no road but this one to make me live. I walk this road.",m:"laurel"},
  {a:"尾崎放哉",w:"『大空』",t:"咳をしても*一人*",e:"Even coughing, alone.",m:"candle"},
  {a:"石川啄木",w:"『一握の砂』",t:"はたらけど はたらけど猶わが生活楽にならざり ぢつと*手*を見る",e:"I work and I work, and still my life is no easier. I stare at my hands.",m:"candle"},
  {a:"石川啄木",w:"『一握の砂』",t:"東海の小島の磯の白砂に われ泣きぬれて *蟹*とたはむる",e:"On the white sand of a small island's shore in the eastern sea, wet with tears, I play with a crab.",m:"moon"},
  {a:"谷崎潤一郎",w:"『陰翳礼讃』",t:"美は物体にあるのではなく、物体と物体との作り出す*陰翳*のあや、明暗にあると考える。",e:"Beauty lies not in objects themselves, but in the patterns of shadow, the light and dark, that objects create between them.",m:"lamp"},
  {a:"芥川龍之介",w:"『侏儒の言葉』",t:"人生は一箱の*マッチ*に似ている。重大に扱うのは莫迦莫迦しい。重大に扱わなければ危険である。",e:"Life is like a box of matches. To treat it seriously is absurd. To treat it lightly is dangerous.",m:"candle"},
  {a:"芥川龍之介",w:"『羅生門』",t:"下人の*行方*は、誰も知らない。",e:"What became of the servant, no one knows.",m:"book"},
  {a:"松下幸之助",w:"『道をひらく』",t:"自分には自分に与えられた道がある。ほかの人には歩めない。自分だけしか歩めない、二度と歩めぬ*かけがえのない*この道。",e:"I have a road given to me alone. No one else can walk it; only I can, and only once. This irreplaceable road.",m:"laurel"},
  {a:"宮沢賢治",w:"『農民芸術概論綱要』",t:"世界がぜんたい*幸福*にならないうちは個人の幸福はあり得ない。",e:"Until the whole world is happy, there can be no happiness for the individual.",m:"candle"},
  {a:"宮沢賢治",w:"『銀河鉄道の夜』",t:"けれども*ほんとうのさいわい*は一体何だろう。",e:"But what, after all, is true happiness?",m:"moon"},
  {a:"宮沢賢治",w:"『春と修羅』序",t:"わたくしといふ現象は 仮定された有機交流電燈の ひとつの*青い照明*です",e:"The phenomenon called I is a single blue illumination of a hypothesized organic alternating-current lamp.",m:"lamp"},
  {a:"宮沢賢治",w:"「雨ニモマケズ」",t:"雨ニモマケズ 風ニモマケズ 雪ニモ夏ノ暑サニモマケヌ *丈夫ナカラダ*ヲモチ",e:"Unbeaten by rain, unbeaten by wind, unbeaten by snow or summer heat, with a strong body.",m:"laurel"},
  {a:"三木清",w:"『人生論ノート』",t:"幸福は*人格*である。",e:"Happiness is character.",m:"lamp"},
  {a:"三木清",w:"『人生論ノート』",t:"孤独は山になく、*街*にある。一人の人間にあるのでなく、大勢の人間の「間」にあるのである。",e:"Solitude is not in the mountains but in the streets; not in one person, but in the space between many.",m:"candle"},
  {a:"井伏鱒二",w:"『厄除け詩集』（于武陵「勧酒」訳）",t:"ハナニアラシノタトヘモアルゾ *サヨナラ*ダケガ人生ダ",e:"Storms scatter the blossoms, as they say. Farewell alone is life.",m:"moon"},
  {a:"川端康成",w:"『雪国』",t:"国境の長いトンネルを抜けると*雪国*であった。夜の底が白くなった。",e:"The train came out of the long tunnel into the snow country. The bottom of the night turned white.",m:"book"},
  {a:"梶井基次郎",w:"『檸檬』",t:"えたいの知れない*不吉な塊*が私の心を始終圧えつけていた。",e:"An indefinable, ominous lump pressed down on my heart without cease.",m:"lamp"},
  {a:"堀辰雄",w:"『風立ちぬ』",t:"風立ちぬ、いざ*生きめやも*。",x:"Le vent se lève, il faut tenter de vivre. — Paul Valéry",e:"The wind is rising. We must try to live.",m:"moon"},
  {a:"坂口安吾",w:"『堕落論』",t:"生きよ*堕ちよ*、その正当な手順の外に、真に人間を救い得る便利な近道が有りようもない。",e:"Live, and fall. Outside that rightful course, there is no convenient shortcut that can truly save a human being.",m:"candle"},
  {a:"中原中也",w:"『山羊の歌』「汚れつちまつた悲しみに」",t:"汚れつちまつた*悲しみ*に 今日も小雪の降りかかる",e:"On my sorrow, soiled and stained, today again a light snow falls.",m:"moon"},
  {a:"太宰治",w:"『人間失格』",t:"恥の多い*生涯*を送って来ました。",e:"Mine has been a life of much shame.",m:"book"},
  {a:"太宰治",w:"『走れメロス』",t:"メロスは*激怒*した。必ず、かの邪智暴虐の王を除かなければならぬと決意した。",e:"Melos was furious. He resolved that the wicked and tyrannical king must be removed.",m:"laurel"},
  {a:"太宰治",w:"『斜陽』",t:"人間は*恋と革命*のために生れて来たのだ。",e:"Human beings were born for love and revolution.",m:"candle"},
  {a:"中島敦",w:"『山月記』",t:"己の*珠*に非ざることを惧れるが故に、敢て刻苦して磨こうともせず、又、己の珠なるべきを半ば信ずるが故に、碌々として瓦に伍することも出来なかった。",e:"Fearing I was no jewel, I would not labor to polish myself; half believing I was a jewel, I could not settle among the common tiles.",m:"lamp"},
  {a:"神谷美恵子",w:"『生きがいについて』",t:"人間がもっとも*生きがい*を感じるのは、自分がしたいと思うことと義務とが一致したときだと思われる。",e:"People feel most alive, I believe, when what they wish to do and what they must do coincide.",m:"candle"},
  // ── 東洋 ──
  {a:"孔子",w:"『論語』学而",t:"学びて時にこれを習う、また*説ばしから*ずや。朋あり遠方より来たる、また楽しからずや。",x:"學而時習之、不亦說乎。有朋自遠方來、不亦樂乎。",e:"To learn and practice in due time, is this not a pleasure? To have friends come from afar, is this not a joy?",m:"book"},
  {a:"孔子",w:"『論語』為政",t:"学びて思わざれば則ち罔し、思いて学ばざれば則ち*殆*し。",x:"學而不思則罔、思而不學則殆。",e:"Learning without thought is labor lost; thought without learning is perilous.",m:"book"},
  {a:"孔子",w:"『論語』為政",t:"故きを温めて新しきを知れば、以て*師*たるべし。",x:"溫故而知新、可以為師矣。",e:"Review the old and learn the new, and you may become a teacher.",m:"lamp"},
  {a:"孔子",w:"『論語』衛霊公",t:"己の欲せざる所は、人に*施す*こと勿れ。",x:"己所不欲、勿施於人。",e:"Do not impose on others what you do not wish for yourself.",m:"lamp"},
  {a:"老子",w:"『老子』第八章",t:"上善は*水*の若し。水は善く万物を利して争わず。",x:"上善若水。水善利萬物而不爭。",e:"The highest good is like water. Water benefits all things and does not contend.",m:"moon"},
  {a:"老子",w:"『老子』第三十三章",t:"足るを知る者は*富む*。",x:"知足者富。",e:"One who knows contentment is rich.",m:"lamp"},
  {a:"老子",w:"『老子』第六十四章",t:"千里の行も*足下*より始まる。",x:"千里之行、始於足下。",e:"A journey of a thousand miles begins beneath one's feet.",m:"laurel"},
  {a:"孫子",w:"『孫子』謀攻篇",t:"彼を知り己を知れば、*百戦*して殆うからず。",x:"知彼知己、百戰不殆。",e:"Know the enemy and know yourself, and in a hundred battles you will never be in peril.",m:"laurel"},
  {a:"孟子",w:"『孟子』告子下",t:"天の将に大任を是の人に降さんとするや、必ず先ず其の*心志*を苦しめる。",x:"天將降大任於是人也、必先苦其心志。",e:"When Heaven is about to place a great responsibility on a person, it first tests their heart and will with suffering.",m:"laurel"},
  {a:"荘子",w:"『荘子』人間世",t:"人皆有用の用を知りて、*無用の用*を知る莫きなり。",x:"人皆知有用之用、而莫知無用之用也。",e:"Everyone knows the usefulness of the useful, but no one knows the usefulness of the useless.",m:"lamp"},
  {a:"荘子",w:"『荘子』斉物論",t:"知らず、周の夢に*胡蝶*と為れるか、胡蝶の夢に周と為れるかを。",x:"不知周之夢為胡蝶與、胡蝶之夢為周與。",e:"I do not know whether Zhou dreamed he was a butterfly, or a butterfly dreamed it was Zhou.",m:"moon"},
  {a:"ブッダ",w:"『ダンマパダ』第一偈",t:"ものごとは*心*にもとづき、心を主とし、心によってつくり出される。",x:"Manopubbaṅgamā dhammā manoseṭṭhā manomayā.",e:"All things are preceded by the mind, led by the mind, made by the mind.",m:"lamp"},
  {a:"ブッダ",w:"『スッタニパータ』",t:"犀の角のように、ただ*独り*歩め。",x:"Eko care khaggavisāṇakappo.",e:"Wander alone, like the horn of a rhinoceros.",m:"candle"},
  {a:"司馬遷",w:"『史記』李将軍列伝",t:"*桃李*もの言わざれども、下自ずから蹊を成す。",x:"桃李不言、下自成蹊。",e:"The peach and the plum do not speak, yet a path forms beneath them.",m:"laurel"},
  {a:"陶淵明",w:"「飲酒」其五",t:"菊を采る東籬の下、悠然として*南山*を見る。",x:"采菊東籬下、悠然見南山。",e:"Picking chrysanthemums by the eastern hedge, I gaze serenely at the southern mountain.",m:"moon"},
  {a:"杜甫",w:"「春望」",t:"国破れて*山河*あり、城春にして草木深し。",x:"國破山河在、城春草木深。",e:"The nation is broken, yet mountains and rivers remain; spring in the city, and grass and trees grow deep.",m:"moon"},
  {a:"タゴール",w:"『迷い鳥』",t:"すべての誤りに扉を閉ざすなら、*真理*も締め出されてしまう。",x:"If you shut your door to all errors truth will be shut out.",m:"lamp"},
  {a:"ジブラーン",w:"『預言者』",t:"あなたの*子ども*は、あなたの子どもではない。生命そのものが自らを求めて生んだ、息子であり娘である。",x:"Your children are not your children. They are the sons and daughters of Life's longing for itself.",m:"candle"},

  // ── 西洋（古代） ──
  {a:"アイスキュロス",w:"『アガメムノン』",t:"*苦しみ*によって学ぶ。",x:"πάθει μάθος",e:"Through suffering, learning.",m:"lamp"},
  {a:"ヘラクレイトス",w:"断片12（ディールス＝クランツ）",t:"同じ*川*に足を踏み入れる者にも、次々と別の水が流れ寄せる。",x:"ποταμοῖσι τοῖσιν αὐτοῖσιν ἐμβαίνουσιν ἕτερα καὶ ἕτερα ὕδατα ἐπιρρεῖ.",e:"Upon those who step into the same rivers, ever different waters flow.",m:"hourglass"},
  {a:"ソポクレス",w:"『アンティゴネー』",t:"不思議なものは数あれど、*人間*ほど不思議なものはない。",x:"πολλὰ τὰ δεινὰ κοὐδὲν ἀνθρώπου δεινότερον πέλει.",e:"Wonders are many, and none is more wonderful than man.",m:"lamp"},
  {a:"ソクラテス",w:"プラトン『ソクラテスの弁明』",t:"吟味されない人生は、人間にとって*生きるに値しない*。",x:"ὁ δὲ ἀνεξέταστος βίος οὐ βιωτὸς ἀνθρώπῳ.",e:"The unexamined life is not worth living.",m:"lamp"},
  {a:"アリストテレス",w:"『ニコマコス倫理学』",t:"正しいことを*行う*ことによって、われわれは正しい人になる。",x:"τὰ μὲν δίκαια πράττοντες δίκαιοι γινόμεθα.",e:"By doing just acts we become just.",m:"laurel"},
  {a:"エピクロス",w:"「メノイケウス宛の手紙」",t:"*死*は、われわれにとって何ものでもない。",x:"ὁ θάνατος οὐδὲν πρὸς ἡμᾶς.",e:"Death is nothing to us.",m:"hourglass"},
  {a:"ウェルギリウス",w:"『アエネーイス』第一巻",t:"いつの日か、これらのことを思い出すのも*喜び*となるだろう。",x:"Forsan et haec olim meminisse iuvabit.",e:"Perhaps one day it will be a joy to remember even these things.",m:"candle"},
  {a:"ホラティウス",w:"『歌集』第一巻十一歌",t:"*今日という日*を摘め。明日をできるだけ信じずに。",x:"Carpe diem, quam minimum credula postero.",e:"Seize the day, trusting as little as possible in tomorrow.",m:"hourglass"},
  {a:"セネカ",w:"『人生の短さについて』",t:"われわれは短い時間を持っているのではない。その多くを*浪費*しているのだ。",x:"Non exiguum temporis habemus, sed multum perdidimus.",e:"It is not that we have a short time to live, but that we waste much of it.",m:"hourglass"},
  {a:"セネカ",w:"『倫理書簡集』第76書簡",t:"生きているかぎり、*生き方*を学び続けなければならない。",x:"Tamdiu discendum est quemadmodum vivas, quamdiu vivas.",e:"As long as you live, keep learning how to live.",m:"book"},
  {a:"エピクテトス",w:"『提要（エンケイリディオン）』",t:"物事のうちには、われわれの*力の及ぶ*ものと、及ばないものとがある。",x:"Τῶν ὄντων τὰ μέν ἐστιν ἐφ' ἡμῖν, τὰ δὲ οὐκ ἐφ' ἡμῖν.",e:"Some things are within our power, and some are not.",m:"lamp"},
  {a:"マルクス・アウレリウス",w:"『自省録』第五巻",t:"明け方、起きるのがつらいときは、こう思え。私は*人間の仕事*をするために起きるのだ、と。",x:"Ὄρθρου ὅταν δυσόκνως ἐξεγείρῃ, πρόχειρον ἔστω ὅτι ἐπὶ ἀνθρώπου ἔργον ἐγείρομαι.",e:"At dawn, when you have trouble getting out of bed, tell yourself: I am rising to do the work of a human being.",m:"lamp"},
  {a:"マルクス・アウレリウス",w:"『自省録』第四巻",t:"自分自身の*魂*の内ほど、静かで煩いのない隠れ家はどこにもない。",x:"οὐδαμοῦ γὰρ οὔτε ἡσυχιώτερον οὔτε ἀπραγμονέστερον ἄνθρωπος ἀναχωρεῖ ἢ εἰς τὴν ἑαυτοῦ ψυχήν.",e:"Nowhere can a person find a quieter or more untroubled retreat than in their own soul.",m:"candle"},
  {a:"アウグスティヌス",w:"『告白』第一巻",t:"私たちの*心*は、あなたのうちに憩うまで安らぐことがありません。",x:"Inquietum est cor nostrum, donec requiescat in te.",e:"Our heart is restless until it rests in You.",m:"candle"},
  // ── 西洋（中世〜近代） ──
  {a:"ダンテ",w:"『神曲』地獄篇第一歌",t:"人生の道の半ばで、私は*暗い森*の中にいた。",x:"Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura.",e:"Midway upon the journey of our life, I found myself within a dark wood.",m:"candle"},
  {a:"マキャヴェリ",w:"『君主論』第十七章",t:"愛されるよりも*恐れられる*ほうが、はるかに安全である。",x:"È molto più sicuro essere temuto che amato.",e:"It is much safer to be feared than loved.",m:"lamp"},
  {a:"モンテーニュ",w:"『エセー』第二巻十二章",t:"私は*何を知っている*のか。",x:"Que sçay-je ?",e:"What do I know?",m:"lamp"},
  {a:"モンテーニュ",w:"『エセー』第三巻十三章",t:"われわれの偉大で輝かしい*傑作*とは、ふさわしく生きることである。",x:"Nostre grand et glorieux chef-d'œuvre, c'est vivre à propos.",e:"Our great and glorious masterpiece is to live appropriately.",m:"laurel"},
  {a:"セルバンテス",w:"『ドン・キホーテ』後編第五十八章",t:"*自由*とはな、サンチョ、天が人間に授けた最も貴い賜物のひとつなのだ。",x:"La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.",e:"Freedom, Sancho, is one of the most precious gifts that heaven has bestowed upon men.",m:"laurel"},
  {a:"フランシス・ベーコン",w:"『随筆集』「学問について」",t:"*読書*は充実した人間を、会話は機敏な人間を、書くことは正確な人間をつくる。",x:"Reading maketh a full man; conference a ready man; and writing an exact man.",m:"book"},
  {a:"シェイクスピア",w:"『ハムレット』第三幕第一場",t:"生きるべきか、*死ぬ*べきか、それが問題だ。",x:"To be, or not to be, that is the question.",m:"lamp"},
  {a:"シェイクスピア",w:"『お気に召すまま』第二幕第七場",t:"この世はすべて*舞台*、男も女もみな役者にすぎない。",x:"All the world's a stage, and all the men and women merely players.",m:"moon"},
  {a:"シェイクスピア",w:"『テンペスト』第四幕第一場",t:"われわれは*夢*と同じ材料でできている。そのささやかな一生は、眠りに包まれている。",x:"We are such stuff as dreams are made on; and our little life is rounded with a sleep.",m:"moon"},
  {a:"ジョン・ダン",w:"『不意に発生する事態に関する瞑想』第十七",t:"何人も*孤島*ではない。",x:"No man is an island, entire of itself.",m:"candle"},
  {a:"デカルト",w:"『方法序説』第四部",t:"我思う、ゆえに*我あり*。",x:"Je pense, donc je suis.",e:"I think, therefore I am.",m:"lamp"},
  {a:"ミルトン",w:"『失楽園』第一巻",t:"心はそれ自身の場所であり、それ自身の中で地獄を*天国*に、天国を地獄に変えることができる。",x:"The mind is its own place, and in itself can make a Heav'n of Hell, a Hell of Heav'n.",m:"lamp"},
  {a:"ラ・ロシュフコー",w:"『箴言集』26",t:"*太陽*も死も、じっと見つめることはできない。",x:"Le soleil ni la mort ne se peuvent regarder fixement.",e:"Neither the sun nor death can be looked at steadily.",m:"hourglass"},
  {a:"パスカル",w:"『パンセ』",t:"人間はひとくきの*葦*にすぎない。自然の中で最も弱いものである。だが、それは考える葦である。",x:"L'homme n'est qu'un roseau, le plus faible de la nature ; mais c'est un roseau pensant.",e:"Man is but a reed, the weakest in nature; but he is a thinking reed.",m:"lamp"},
  {a:"パスカル",w:"『パンセ』",t:"人間の不幸はすべて、たったひとつのこと、*部屋*にじっと休んでいられないことから来る。",x:"Tout le malheur des hommes vient d'une seule chose, qui est de ne savoir pas demeurer en repos, dans une chambre.",e:"All of humanity's misfortune comes from one thing: not knowing how to sit quietly in a room.",m:"candle"},
  {a:"スピノザ",w:"『エチカ』第五部（結び）",t:"すべて*高貴*なものは、稀であるとともに困難である。",x:"Sed omnia praeclara tam difficilia, quam rara sunt.",e:"All things excellent are as difficult as they are rare.",m:"laurel"},
  {a:"ニュートン",w:"ロバート・フック宛の手紙（1675年）",t:"私がより遠くを見たとすれば、それは*巨人*の肩の上に立っていたからだ。",x:"If I have seen further it is by standing on the shoulders of Giants.",m:"lamp"},
  {a:"ヴォルテール",w:"『カンディード』",t:"しかし、われわれの*庭*を耕さねばなりません。",x:"Il faut cultiver notre jardin.",e:"But we must cultivate our garden.",m:"laurel"},
  {a:"ルソー",w:"『社会契約論』第一篇第一章",t:"人間は*自由*なものとして生まれた。しかし、いたるところで鎖につながれている。",x:"L'homme est né libre, et partout il est dans les fers.",e:"Man is born free, and everywhere he is in chains.",m:"lamp"},
  {a:"カント",w:"『実践理性批判』結語",t:"わが上なる*星空*と、わが内なる道徳法則。",x:"Der bestirnte Himmel über mir und das moralische Gesetz in mir.",e:"The starry heavens above me and the moral law within me.",m:"moon"},
  {a:"ゲーテ",w:"『ファウスト』天上の序曲",t:"人間は*努力*するかぎり、迷うものだ。",x:"Es irrt der Mensch, solang er strebt.",e:"Man errs as long as he strives.",m:"laurel"},
  {a:"ゲーテ",w:"『ファウスト』第一部",t:"時よ*止まれ*、おまえはいかにも美しい。",x:"Verweile doch! du bist so schön!",e:"Stay a while! You are so beautiful!",m:"hourglass"},
  {a:"ブレイク",w:"「無垢の予兆」",t:"一粒の*砂*に世界を見、一輪の野の花に天国を見る。",x:"To see a World in a Grain of Sand and a Heaven in a Wild Flower.",m:"moon"},
  {a:"オースティン",w:"『高慢と偏見』第一章",t:"財産のある独身男性なら妻を欲しがっているに違いない。これは世間一般に認められた*真理*である。",x:"It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",m:"book"},
  {a:"スタンダール",w:"『赤と黒』",t:"小説とは、大きな道に沿って持ち歩かれる*鏡*である。",x:"Un roman est un miroir qui se promène sur une grande route.",e:"A novel is a mirror carried along a high road.",m:"book"},
  {a:"ショーペンハウアー",w:"『幸福について（処世術箴言）』",t:"われわれは自分の持っているものをめったに考えず、いつも*欠けているもの*ばかりを考える。",x:"Wir denken selten an das, was wir haben, aber immer an das, was uns fehlt.",e:"We seldom think of what we have, but always of what we lack.",m:"lamp"},
  {a:"キーツ",w:"「ギリシアの壺に寄せるオード」",t:"*美*は真なり、真は美なり。",x:"Beauty is truth, truth beauty.",m:"moon"},
  {a:"プーシキン",w:"「もし人生に欺かれたら」",t:"もし人生があなたを欺いても、悲しまず、怒らず。憂鬱な日には心静かに。*楽しい日*がきっと来ると信じて。",x:"Если жизнь тебя обманет, не печалься, не сердись! В день уныния смирись: день веселья, верь, настанет.",e:"If life deceives you, do not grieve, do not be angry. On the day of sorrow, be still; the day of joy, believe, will come.",m:"candle"},
  {a:"ユゴー",w:"『レ・ミゼラブル』第一部第五編",t:"*悪い草*も、悪い人間もない。あるのは、悪い耕し手だけだ。",x:"Il n'y a ni mauvaises herbes ni mauvais hommes. Il n'y a que de mauvais cultivateurs.",e:"There are no bad plants or bad men. There are only bad cultivators.",m:"laurel"},
  {a:"デュマ",w:"『三銃士』",t:"一人はみんなのために、*みんな*は一人のために。",x:"Tous pour un, un pour tous.",e:"All for one, one for all.",m:"laurel"},
  {a:"エマソン",w:"『自己信頼』",t:"*自分自身*を信じよ。すべての心はその鉄の弦に震える。",x:"Trust thyself: every heart vibrates to that iron string.",m:"laurel"},
  {a:"アンデルセン",w:"『みにくいアヒルの子』",t:"アヒルの庭に生まれたって、*白鳥*の卵からかえったのなら、なんでもないのだ。",x:"Det gør ikke noget at være født i andegården, når man kun har ligget i et svaneæg!",e:"It does not matter that one was born in a duckyard, if one has lain in a swan's egg.",m:"moon"},
  {a:"ダーウィン",w:"『種の起源』結び",t:"この生命観には*壮大さ*がある。",x:"There is grandeur in this view of life.",m:"lamp"},
  {a:"ディケンズ",w:"『二都物語』第一章",t:"それは最良の時代であり、*最悪*の時代であった。",x:"It was the best of times, it was the worst of times.",m:"hourglass"},
  {a:"キルケゴール",w:"『日記』1843年",t:"人生は*後ろ向き*にしか理解できない。しかし、前向きにしか生きられない。",x:"Livet forstaaes baglænds, men maa leves forlænds.",e:"Life can only be understood backwards; but it must be lived forwards.",m:"hourglass"},
  {a:"シャーロット・ブロンテ",w:"『ジェイン・エア』第二十三章",t:"私は*鳥*ではない。どんな網も私を捕らえはしない。私は自由な意志を持つ、自由な人間です。",x:"I am no bird; and no net ensnares me: I am a free human being with an independent will.",m:"laurel"},
  {a:"ソロー",w:"『ウォールデン 森の生活』",t:"私が森へ行ったのは、*意図的に*生きたいと思ったからだ。",x:"I went to the woods because I wished to live deliberately.",m:"candle"},
  {a:"エミリー・ブロンテ",w:"『嵐が丘』第九章",t:"彼は私以上に*私自身*なの。私たちの魂が何でできていようと、彼のと私のは同じもの。",x:"He's more myself than I am. Whatever our souls are made of, his and mine are the same.",m:"moon"},
  {a:"メルヴィル",w:"『白鯨』第一章",t:"私を*イシュメール*と呼んでくれ。",x:"Call me Ishmael.",m:"book"},
  {a:"ホイットマン",w:"『草の葉』「ぼく自身の歌」",t:"私は矛盾しているだろうか。よろしい、ならば私は矛盾している。私は大きい、私は*多数*を含んでいる。",x:"Do I contradict myself? Very well then I contradict myself, (I am large, I contain multitudes.)",m:"laurel"},
  {a:"ジョージ・エリオット",w:"『ミドルマーチ』終章",t:"世界の善が増していくのは、一部には*歴史に残らない行い*のおかげなのだから。",x:"For the growing good of the world is partly dependent on unhistoric acts.",m:"candle"},
  {a:"ボードレール",w:"『パリの憂鬱』「酔え」",t:"常に*酔って*いなければならない。",x:"Il faut être toujours ivre.",e:"One must always be drunk.",m:"moon"},
  {a:"ドストエフスキー",w:"『白痴』",t:"*美*が世界を救う。",x:"Красота спасёт мир.",e:"Beauty will save the world.",m:"lamp"},
  {a:"ドストエフスキー",w:"『カラマーゾフの兄弟』エピローグ",t:"何かしら*よい思い出*、とりわけ子どものころの思い出ほど、その後の人生にとって尊く、力強く、健やかで、有益なものはありません。",x:"Ничего нет выше и сильнее и здоровее и полезнее впредь для жизни, как хорошее какое-нибудь воспоминание, и особенно вынесенное ещё из детства.",e:"There is nothing higher, stronger, healthier, or more useful for later life than some good memory, especially one carried from childhood.",m:"candle"},
  {a:"トルストイ",w:"『アンナ・カレーニナ』第一部第一章",t:"幸福な*家庭*はどれも似たものだが、不幸な家庭はいずれもそれぞれに不幸である。",x:"Все счастливые семьи похожи друг на друга, каждая несчастливая семья несчастлива по-своему.",e:"All happy families are alike; each unhappy family is unhappy in its own way.",m:"book"},
  {a:"ディキンソン",w:"詩 314番",t:"「*希望*」は羽をもつもの ― 魂にとまり ―",x:"'Hope' is the thing with feathers – That perches in the soul –",m:"candle"},
  {a:"ルイス・キャロル",w:"『不思議の国のアリス』第六章",t:"「ここからどっちへ行けばいいか、教えてくださらない？」「それは、君が*どこへ行きたい*かによるね」",x:"\"Would you tell me, please, which way I ought to go from here?\" \"That depends a good deal on where you want to get to,\" said the Cat.",m:"book"},
  {a:"マーク・トウェイン",w:"『ハックルベリー・フィンの冒険』第三十一章",t:"よし、それなら、おれは*地獄*へ行こう。",x:"All right, then, I'll go to hell.",m:"laurel"},
  {a:"ニーチェ",w:"『ツァラトゥストラはこう語った』序説",t:"人間とは、*乗り越えられる*べき何ものかである。",x:"Der Mensch ist Etwas, das überwunden werden soll.",e:"Man is something that shall be overcome.",m:"laurel"},
  {a:"ニーチェ",w:"『ツァラトゥストラはこう語った』序説",t:"踊る*星*を産むためには、人は自分の内に混沌を持っていなければならない。",x:"Man muss noch Chaos in sich haben, um einen tanzenden Stern gebären zu können.",e:"One must still have chaos in oneself to give birth to a dancing star.",m:"moon"},
  {a:"ニーチェ",w:"『偶像の黄昏』",t:"生きる*なぜ*を持つ者は、ほとんどどんな「いかに」にも耐えられる。",x:"Hat man sein warum? des Lebens, so verträgt man sich fast mit jedem wie?",e:"He who has a why to live can bear almost any how.",m:"lamp"},
  {a:"ワイルド",w:"『ウィンダミア卿夫人の扇』第三幕",t:"われわれはみな溝の中にいる。だが、そのうちの何人かは*星*を見上げている。",x:"We are all in the gutter, but some of us are looking at the stars.",m:"moon"},
  {a:"ワイルド",w:"『ドリアン・グレイの肖像』序文",t:"すべての*芸術*は、まったく無用である。",x:"All art is quite useless.",m:"quill"},
  // ── 西洋（現代） ──
  {a:"アラン",w:"『幸福論』",t:"*悲観主義*は気分のものであり、楽観主義は意志のものである。",x:"Le pessimisme est d'humeur ; l'optimisme est de volonté.",e:"Pessimism is a matter of mood; optimism is a matter of will.",m:"lamp"},
  {a:"プルースト",w:"『失われた時を求めて』囚われの女",t:"唯一の本当の旅とは、新しい風景に向かうことではなく、*別の目*を持つことだろう。",x:"Le seul véritable voyage, ce ne serait pas d'aller vers de nouveaux paysages, mais d'avoir d'autres yeux.",e:"The only true voyage would be not to visit new landscapes, but to possess other eyes.",m:"book"},
  {a:"リルケ",w:"『若き詩人への手紙』",t:"あなたの心の中の未解決のものすべてに対して忍耐を持ち、*問いそのもの*を愛そうと努めてください。",x:"Geduld zu haben gegen alles Ungelöste in Ihrem Herzen und zu versuchen, die Fragen selbst liebzuhaben.",e:"Be patient toward all that is unsolved in your heart, and try to love the questions themselves.",m:"candle"},
  {a:"ヘッセ",w:"『デミアン』",t:"鳥は*卵*の中から抜け出ようと戦う。卵は世界だ。",x:"Der Vogel kämpft sich aus dem Ei. Das Ei ist die Welt.",e:"The bird fights its way out of the egg. The egg is the world.",m:"laurel"},
  {a:"アインシュタイン",w:"インタビュー（1929年）",t:"*想像力*は知識よりも重要である。",x:"Imagination is more important than knowledge.",m:"lamp"},
  {a:"ヘレン・ケラー",w:"『楽天主義』",t:"世界は苦しみに満ちているが、それを*乗り越えること*にも満ちている。",x:"Although the world is full of suffering, it is full also of the overcoming of it.",m:"candle"},
  {a:"ジョイス",w:"『ユリシーズ』第二挿話",t:"歴史とは、僕が目覚めようとしている*悪夢*だ。",x:"History is a nightmare from which I am trying to awake.",m:"hourglass"},
  {a:"ウルフ",w:"『自分ひとりの部屋』",t:"女性が小説を書こうと思うなら、お金と*自分ひとりの部屋*を持たねばならない。",x:"A woman must have money and a room of her own if she is to write fiction.",m:"quill"},
  {a:"カフカ",w:"オスカー・ポラック宛の手紙（1904年）",t:"本とは、われわれの内なる凍った海を砕く*斧*でなければならない。",x:"Ein Buch muß die Axt sein für das gefrorene Meer in uns.",e:"A book must be the axe for the frozen sea within us.",m:"book"},
  {a:"カフカ",w:"『変身』",t:"ある朝、グレゴール・ザムザが不安な夢から目を覚ますと、ベッドの中で自分が一匹の巨大な*虫*に変わっているのに気づいた。",x:"Als Gregor Samsa eines Morgens aus unruhigen Träumen erwachte, fand er sich in seinem Bett zu einem ungeheueren Ungeziefer verwandelt.",e:"As Gregor Samsa awoke one morning from uneasy dreams, he found himself transformed in his bed into a gigantic insect.",m:"book"},
  {a:"デール・カーネギー",w:"『道は開ける』",t:"*今日一日*の区切りで生きよ。",x:"Live in day-tight compartments.",m:"hourglass"},
  {a:"ヴィトゲンシュタイン",w:"『論理哲学論考』7",t:"語りえぬものについては、*沈黙*しなければならない。",x:"Wovon man nicht sprechen kann, darüber muß man schweigen.",e:"Whereof one cannot speak, thereof one must be silent.",m:"lamp"},
  {a:"トールキン",w:"『指輪物語』旅の仲間",t:"さまよう者すべてが、*道に迷って*いるわけではない。",x:"Not all those who wander are lost.",m:"moon"},
  {a:"フィッツジェラルド",w:"『グレート・ギャツビー』結び",t:"こうして我々は、*流れ*にさからう舟のように、絶えず過去へと押し戻されながら進んでいく。",x:"So we beat on, boats against the current, borne back ceaselessly into the past.",m:"hourglass"},
  {a:"ヘミングウェイ",w:"『老人と海』",t:"人間は*負ける*ようには造られていない。人間は滅ぼされることはあっても、負けることはない。",x:"But man is not made for defeat. A man can be destroyed but not defeated.",m:"laurel"},
  {a:"ボルヘス",w:"「天恵の詩」",t:"私はいつも、*楽園*とは図書館のようなものだと思い描いていた。",x:"Yo, que me figuraba el Paraíso bajo la especie de una biblioteca.",e:"I, who had always imagined Paradise as a kind of library.",m:"book"},
  {a:"サン＝テグジュペリ",w:"『星の王子さま』",t:"大切なものは、*目*に見えない。",x:"L'essentiel est invisible pour les yeux.",e:"What is essential is invisible to the eye.",m:"moon"},
  {a:"サン＝テグジュペリ",w:"『人間の土地』",t:"愛するとは、互いに見つめ合うことではなく、いっしょに*同じ方向*を見つめることだ。",x:"Aimer, ce n'est pas se regarder l'un l'autre, c'est regarder ensemble dans la même direction.",e:"Love does not consist in gazing at each other, but in looking outward together in the same direction.",m:"candle"},
  {a:"スタインベック",w:"『エデンの東』",t:"*ティムシェル* ― 汝、なしうる。",x:"Timshel — thou mayest.",m:"laurel"},
  {a:"オーウェル",w:"『1984年』",t:"自由とは、二足す二が四であると言える*自由*である。",x:"Freedom is the freedom to say that two plus two make four.",m:"lamp"},
  {a:"オーウェル",w:"『動物農場』",t:"すべての動物は平等である。だが、ある動物は他の動物より*もっと平等*である。",x:"All animals are equal, but some animals are more equal than others.",m:"book"},
  {a:"サルトル",w:"『実存主義とは何か』",t:"人間は*自由の刑*に処せられている。",x:"L'homme est condamné à être libre.",e:"Man is condemned to be free.",m:"lamp"},
  {a:"フランクル",w:"『夜と霧』",t:"問題なのは、私たちが人生に何を期待するかではなく、*人生*が私たちに何を期待しているかだ。",x:"Es kommt nie und nimmer darauf an, was wir vom Leben noch zu erwarten haben, vielmehr lediglich darauf: was das Leben von uns erwartet.",e:"It does not really matter what we expect from life, but rather what life expects from us.",m:"candle"},
  {a:"ボーヴォワール",w:"『第二の性』",t:"人は女に生まれるのではない、女に*なる*のだ。",x:"On ne naît pas femme : on le devient.",e:"One is not born, but rather becomes, a woman.",m:"lamp"},
  {a:"カミュ",w:"『シーシュポスの神話』",t:"*幸福なシーシュポス*を想像しなければならない。",x:"Il faut imaginer Sisyphe heureux.",e:"One must imagine Sisyphus happy.",m:"laurel"},
  {a:"カミュ",w:"『夏』「ティパサに帰る」",t:"冬のさなかに、私はついに、自分の内に*打ち負かしがたい夏*があることを知った。",x:"Au milieu de l'hiver, j'apprenais enfin qu'il y avait en moi un été invincible.",e:"In the midst of winter, I finally learned that there was in me an invincible summer.",m:"candle"},
  {a:"ガルシア＝マルケス",w:"『百年の孤独』冒頭",t:"長い歳月が流れて銃殺隊の前に立つはめになったとき、アウレリャノ・ブエンディア大佐は、父親に連れられて*氷*を見に行った遠い日の午後を思い出したにちがいない。",x:"Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",e:"Many years later, as he faced the firing squad, Colonel Aureliano Buendía was to remember that distant afternoon when his father took him to discover ice.",m:"book"},
  {a:"アンネ・フランク",w:"『アンネの日記』1944年7月15日",t:"それでもなお、私は人間の心が本当は*善*なのだと信じています。",x:"Ik geloof, ondanks alles, aan de innerlijke goedheid van de mens.",e:"In spite of everything, I still believe that people are really good at heart.",m:"candle"},
  {a:"額田王",w:"『万葉集』巻一",t:"熟田津に 船乗りせむと 月待てば *潮*もかなひぬ 今は漕ぎ出でな",e:"At Nikitatsu we waited for the moon to board our ships; now the tide is right, let us row out.",m:"compass"},
  {a:"柿本人麻呂",w:"『万葉集』巻一",t:"東の野に*かぎろひ*の立つ見えて かへり見すれば月傾きぬ",e:"In the eastern fields I see the dawn light rising; looking back, the moon is sinking.",m:"moon"},
  {a:"大伴家持",w:"『万葉集』巻十九",t:"うらうらに 照れる春日に ひばり上がり 心悲しも *ひとり*し思へば",e:"In the soft spring sunlight a skylark rises, and my heart grows sad, thinking alone.",m:"bird"},
  {a:"在原業平",w:"『古今和歌集』",t:"世の中に たえて*桜*のなかりせば 春の心は のどけからまし",e:"If only there were no cherry blossoms in this world, how calm our hearts would be in spring.",m:"tree"},
  {a:"藤原定家",w:"『新古今和歌集』",t:"見わたせば 花も紅葉も なかりけり 浦の苫屋の *秋の夕暮*",e:"Looking out, there are no blossoms, no crimson leaves; only a thatched hut by the bay in the autumn dusk.",m:"moon"},
  {a:"紫式部",w:"『新古今和歌集』（百人一首）",t:"めぐりあひて 見しやそれとも わかぬ間に 雲がくれにし *夜半の月*かな",e:"We met, and before I could tell whether it was really you, you vanished like the midnight moon behind clouds.",m:"moon"},
  {a:"西行",w:"『新古今和歌集』",t:"心なき 身にも*あはれ*は 知られけり 鴫立つ沢の 秋の夕暮",e:"Even a heart that has renounced the world feels this sorrow: a snipe rising from the marsh in the autumn dusk.",m:"bird"},
  {a:"空海",w:"『御請来目録』（語は『荘子』徳充符による）",t:"虚しく往きて*実ちて*帰る。",x:"虚往実帰",e:"I went empty and returned full.",m:"book"},
  {a:"最澄",w:"『山家学生式』",t:"*一隅*を照らす、此れ則ち国宝なり。",x:"照于一隅、此則国宝",e:"One who lights up a single corner—this is a national treasure.",m:"candle"},
  {a:"明恵",w:"『栂尾明恵上人遺訓』",t:"人は*あるべきやう*は、と云ふ七文字を持つべきなり。",e:"A person should hold to these words: 'What ought I to be?'",m:"lamp"},
  {a:"日蓮",w:"「妙一尼御前御消息」",t:"冬は必ず*春*となる。",e:"Winter always turns to spring.",m:"tree"},
  {a:"親鸞",w:"『歎異抄』第一条",t:"弥陀の本願には、*老少善悪*のひとをえらばれず。",e:"Amida's Vow does not choose between the old and the young, the good and the evil.",m:"lamp"},
  {a:"道元",w:"『傘松道詠』",t:"春は花 夏ほととぎす 秋は月 冬雪さえて *冷しかりけり*",e:"In spring, blossoms; in summer, the cuckoo; in autumn, the moon; in winter, snow, clear and cold.",m:"moon"},
  {a:"鴨長明",w:"『方丈記』",t:"世にしたがへば、身くるし。したがはねば、*狂せる*に似たり。",e:"Follow the world and the body suffers; refuse it and you seem mad.",m:"hourglass"},
  {a:"吉田兼好",w:"『徒然草』第七段",t:"世は*定めなき*こそいみじけれ。",e:"It is precisely because the world is uncertain that it is so moving.",m:"hourglass"},
  {a:"清少納言",w:"『枕草子』",t:"冬は*つとめて*。雪の降りたるは言ふべきにもあらず。",e:"In winter, the early morning. When snow has fallen, there is nothing to be said.",m:"candle"},
  {a:"世阿弥",w:"『風姿花伝』",t:"時分の花をまことの花と知る心が、*真実の花*になほ遠ざかる心なり。",e:"A heart that takes the flower of the moment for the true flower is a heart drifting further from the true flower.",m:"laurel"},
  {a:"一休宗純",w:"伝・一休の狂歌",t:"門松は 冥土の旅の *一里塚* めでたくもあり めでたくもなし",e:"The New Year pine is a milestone on the road to the underworld—half a blessing, half not.",m:"hourglass"},
  {a:"白隠慧鶴",w:"『坐禅和讃』",t:"衆生本来*仏*なり。水と氷の如くにて、水を離れて氷なく、衆生の外に仏なし。",e:"All beings are Buddha by nature. As with water and ice, there is no ice apart from water, and no Buddha apart from beings.",m:"lamp"},
  {a:"近松門左衛門",w:"『難波土産』（穂積以貫の記録）",t:"芸といふものは、*実と虚との皮膜*の間にあるものなり。",e:"Art lies in the thin membrane between the real and the unreal.",m:"quill"},
  {a:"与謝蕪村",w:"『蕪村句集』",t:"*菜の花*や 月は東に 日は西に",e:"Fields of rapeseed—the moon in the east, the sun in the west.",m:"moon"},
  {a:"松尾芭蕉",w:"『おくのほそ道』",t:"閑さや 岩にしみ入る *蝉の声*",e:"Such stillness—the cry of the cicadas sinks into the rocks.",m:"tree"},
  {a:"松尾芭蕉",w:"病中吟（1694年）",t:"旅に病んで *夢*は枯野を かけ廻る",e:"Sick on a journey, my dreams go wandering over withered fields.",m:"hourglass"},
  {a:"本居宣長",w:"自画像の賛（1790年）",t:"敷島の 大和心を 人問はば 朝日に匂ふ *山桜花*",e:"If someone asks what the heart of Japan is: mountain cherry blossoms, fragrant in the morning sun.",m:"tree"},
  {a:"小林一茶",w:"『七番日記』",t:"やせ蛙 *負けるな*一茶 これにあり",e:"Skinny frog, don't give up—Issa is here.",m:"laurel"},
  {a:"小林一茶",w:"『おらが春』",t:"我と来て 遊べや 親のない*雀*",e:"Come and play with me, little sparrow with no mother.",m:"bird"},
  {a:"良寛",w:"辞世（伝）",t:"散る桜 残る桜も *散る桜*",e:"Falling cherry blossoms; the blossoms that remain are falling blossoms too.",m:"tree"},
  {a:"勝海舟",w:"福澤諭吉への返書（1892年）",t:"*行蔵*は我に存す、毀誉は他人の主張、我に与らず我に関せずと存候。",e:"What I do and leave undone is mine. Praise and blame belong to others; they are not my concern.",m:"quill"},
  {a:"坂本龍馬",w:"伝・龍馬の歌",t:"世の人は 我を何とも 言はば言へ 我が成す事は *我のみぞ知る*",e:"Let the world say what it will of me. What I do, I alone know.",m:"compass"},
  {a:"高杉晋作",w:"辞世の句（伝）",t:"おもしろき こともなき世を *おもしろく*",e:"This world with nothing amusing in it—I will make it amusing.",m:"laurel"},
  {a:"福澤諭吉",w:"『学問のすすめ』三編",t:"独立の気力なき者は必ず人に*依頼*す。",e:"Those who lack the spirit of independence will always depend on others.",m:"book"},
  {a:"尾崎紅葉",w:"『金色夜叉』",t:"来年の今月今夜になったならば、僕の*涙*で必ず月は曇らして見せるから。",e:"A year from tonight, I swear my tears will cloud this moon.",m:"moon"},
  {a:"樋口一葉",w:"『たけくらべ』冒頭",t:"廻れば大門の見返り柳いと長けれど、お歯ぐろ溝に燈火うつる三階の騒ぎも*手に取る如く*。",e:"It is a long way round to the great gate and the willow that looks back, but the lights of the three-storied houses glitter in the moat, and their revelry seems close enough to touch.",m:"lamp"},
  {a:"国木田独歩",w:"『武蔵野』",t:"武蔵野に散歩する人は、*道に迷う*ことを苦にしてはならない。",e:"Whoever walks in Musashino must not mind losing the way.",m:"compass"},
  {a:"正岡子規",w:"「海南新聞」（1895年）",t:"柿くへば *鐘*が鳴るなり 法隆寺",e:"I bite into a persimmon—and a bell rings out at Horyuji.",m:"bell"},
  {a:"高浜虚子",w:"『六百五十句』",t:"去年今年 貫く*棒*の如きもの",e:"Last year, this year—something runs through them like a rod.",m:"hourglass"},
  {a:"与謝野晶子",w:"「君死にたまふことなかれ」（『明星』1904年）",t:"ああ弟よ、君を泣く、君*死にたまふ*ことなかれ。",e:"Ah, my brother, I weep for you. Do not die.",m:"candle"},
  {a:"野口英世",w:"生家の柱に刻んだ言葉（1896年）",t:"志を得ざれば再び*此地*を踏まず。",e:"Until I have achieved my aim, I will not set foot on this ground again.",m:"compass"},
  {a:"寺田寅彦",w:"「小爆発二件」（1935年）",t:"ものをこわがらな過ぎたり、こわがり過ぎたりするのはやさしいが、*正当にこわがる*ことはなかなかむつかしい。",e:"It is easy to fear too little or too much; to fear rightly is very hard.",m:"telescope"},
  {a:"夏目漱石",w:"『草枕』",t:"住みにくき世から、住みにくき煩いを引き抜いて、ありがたい世界をまのあたりに写すのが*詩*である、画である。",e:"To pull the vexations out of this hard-to-live-in world and set a blessed world before our eyes—that is poetry, that is painting.",m:"quill"},
  {a:"北原白秋",w:"『水墨集』「落葉松」",t:"からまつの林を過ぎて、からまつをしみじみと見き。からまつは*さびしかり*けり。たびゆくはさびしかりけり。",e:"Passing through the larch woods, I gazed long at the larches. The larches were lonely; to travel is lonely.",m:"tree"},
  {a:"若山牧水",w:"『海の声』",t:"*白鳥*は 哀しからずや 空の青 海のあをにも 染まずただよふ",e:"Is the white bird not sad? Dyed neither by the blue of the sky nor the blue of the sea, it drifts.",m:"bird"},
  {a:"若山牧水",w:"『海の声』",t:"幾山河 越えさり行かば *寂しさ*の 終てなむ国ぞ 今日も旅ゆく",e:"How many mountains and rivers must I cross before I reach the land where loneliness ends? Today, again, I travel.",m:"compass"},
  {a:"山村暮鳥",w:"『聖三稜玻璃』「風景」",t:"いちめんのなのはな いちめんのなのはな いちめんの*なのはな*",e:"A whole field of rape blossoms, a whole field of rape blossoms, a whole field of rape blossoms.",m:"tree"},
  {a:"萩原朔太郎",w:"『純情小曲集』「旅上」",t:"ふらんすへ行きたしと思へども ふらんすはあまりに*遠し*",e:"I long to go to France, but France is far too far.",m:"compass"},
  {a:"室生犀星",w:"『抒情小曲集』「小景異情」",t:"*ふるさと*は遠きにありて思ふもの そして悲しくうたふもの",e:"Home is something to think of from afar, and to sing of in sorrow.",m:"lamp"},
  {a:"石川啄木",w:"『一握の砂』",t:"ふるさとの *訛*なつかし 停車場の 人ごみの中に そを聴きにゆく",e:"Longing for the accent of my hometown, I go to the crowded station just to hear it.",m:"bell"},
  {a:"岡本かの子",w:"『老妓抄』",t:"年々にわが悲しみは深くして いよよ*華やぐ*いのちなりけり",e:"Year by year my sorrow deepens, and all the more my life grows radiant.",m:"laurel"},
  {a:"佐藤春夫",w:"「秋刀魚の歌」",t:"あはれ 秋風よ 情あらば伝へてよ、男ありて 今日の夕餉に ひとり *さんま*を食ひて 思ひにふける と。",e:"Ah, autumn wind, if you have a heart, tell them: there is a man who, at supper tonight, eats a saury alone and sinks into thought.",m:"candle"},
  {a:"吉川英治",w:"『宮本武蔵』",t:"*我以外皆我師*。",e:"Everyone but myself is my teacher.",m:"book"},
  {a:"八木重吉",w:"『貧しき信徒』「素朴な琴」",t:"このあかるさのなかへ ひとつの素朴な*琴*をおけば 秋の美くしさに耐へかね 琴はしづかに鳴りいだすだらう",e:"Set a simple harp in this brightness, and unable to bear the beauty of autumn, the harp will softly begin to sound.",m:"candle"},
  {a:"三好達治",w:"『測量船』「雪」",t:"太郎を眠らせ、太郎の屋根に*雪*ふりつむ。次郎を眠らせ、次郎の屋根に雪ふりつむ。",e:"Putting Taro to sleep, snow piles on Taro's roof. Putting Jiro to sleep, snow piles on Jiro's roof.",m:"moon"},
  {a:"中村草田男",w:"『長子』",t:"降る雪や *明治*は遠くなりにけり",e:"Falling snow—how far away Meiji has become.",m:"hourglass"},
  {a:"小林秀雄",w:"『当麻』",t:"美しい「花」がある、「花」の*美しさ*という様なものはない。",e:"There are beautiful flowers; there is no such thing as the beauty of flowers.",m:"laurel"},
  {a:"金子みすゞ",w:"「私と小鳥と鈴と」",t:"みんなちがって、*みんないい*。",e:"We are all different, and all of us are good.",m:"bell"},
  {a:"林芙美子",w:"色紙の言葉",t:"*花の命*は短くて 苦しきことのみ多かりき",e:"The life of a flower is short, and full only of hardship.",m:"tree"},
  {a:"宮沢賢治",w:"『銀河鉄道の夜』",t:"なにがしあわせかわからないです。ほんとうにどんなつらいことでも、それが*ただしいみち*を進む中でのできごとなら、峠の上りも下りもみんなほんとうの幸福に近づく一あしずつですから。",e:"I don't know what happiness is. But truly, whatever hardship comes, if it happens on the right path, every climb and descent of the pass is one step closer to real happiness.",m:"compass"},
  {a:"太宰治",w:"『二十世紀旗手』副題",t:"生れて、*すみません*。",e:"Forgive me for being born.",m:"candle"},
  {a:"芥川龍之介",w:"『侏儒の言葉』",t:"人生は*地獄*よりも地獄的である。",e:"Life is more hellish than hell.",m:"hourglass"},
  {a:"中原中也",w:"『山羊の歌』「サーカス」",t:"ゆあーん ゆよーん *ゆやゆよん*",e:"Yuaan, yuyoon, yuyayuyon.",m:"moon"},
  {a:"新美南吉",w:"『ごんぎつね』",t:"ごん、お前だったのか。いつも*栗*をくれたのは。",e:"Gon, it was you? You were the one who always brought me chestnuts?",m:"tree"},
  {a:"立原道造",w:"『萱草に寄す』「のちのおもひに」",t:"*夢*はいつもかへつて行つた 山の麓のさびしい村に",e:"My dreams always went back to the lonely village at the foot of the mountain.",m:"lamp"},
  {a:"石垣りん",w:"「表札」",t:"自分の住むところには 自分で*表札*を出すにかぎる。",e:"Where you live, you had best hang your own nameplate.",m:"key"},
  {a:"茨木のり子",w:"「自分の感受性くらい」",t:"自分の*感受性*くらい 自分で守れ ばかものよ",e:"Your own sensibility, at least—guard it yourself, you fool.",m:"quill"},
  {a:"谷川俊太郎",w:"「二十億光年の孤独」",t:"二十億光年の*孤独*に 僕は思わずくしゃみをした",e:"In the loneliness of two billion light-years, I sneezed without meaning to.",m:"telescope"},
  {a:"寺山修司",w:"『空には本』",t:"マッチ擦る つかのま海に 霧ふかし 身捨つるほどの *祖国*はありや",e:"Striking a match—for an instant, thick fog on the sea. Is there a homeland worth throwing my body away for?",m:"compass"},
  {a:"俵万智",w:"『サラダ記念日』",t:"「この味がいいね」と君が言ったから 七月六日は*サラダ記念日*",e:"Because you said 'This tastes good,' July sixth is Salad Anniversary.",m:"laurel"},
  {a:"岡本太郎",w:"「芸術は爆発だ」（1981年、テレビCMでの発言）",t:"芸術は*爆発*だ。",e:"Art is an explosion.",m:"telescope"},
  {a:"相田みつを",w:"『にんげんだもの』",t:"つまづいたっていいじゃないか *にんげん*だもの",e:"It's all right to stumble—we are only human.",m:"quill"},
  {a:"湯川秀樹",w:"色紙の言葉",t:"一日生きることは、*一歩進む*ことでありたい。",e:"To live one day should be to advance one step.",m:"compass"},
  {a:"山本五十六",w:"伝・部下への言葉",t:"やってみせ、言って聞かせて、させてみて、*ほめて*やらねば、人は動かじ。",e:"Show them, tell them, let them try, and praise them—or people will not move.",m:"laurel"},
  {a:"松下幸之助",w:"『素直な心になるために』",t:"*素直な心*とは、私心なくくもりのない心、一つのことにとらわれずに、物事をあるがままに見ようとする心である。",e:"An honest heart is one without self-interest or cloud, that does not cling to one thing but tries to see things as they are.",m:"lamp"},
  {a:"稲盛和夫",w:"『生き方』",t:"人生・仕事の結果 ＝ *考え方* × 熱意 × 能力",e:"The result of life and work = way of thinking × passion × ability.",m:"compass"},
  {a:"安藤百福",w:"創業の精神「食足世平」",t:"*食*足りて世は平らか。",e:"When there is enough to eat, the world is at peace.",m:"lamp"},
  {a:"神谷美恵子",w:"『生きがいについて』",t:"生きがいというものは、私たちが*生きている*ことそのものの中に、その根拠を持っているものである。",e:"What makes life worth living has its ground in the very fact that we are alive.",m:"candle"},
  {a:"三木清",w:"『人生論ノート』",t:"人生は*運命*であるように、人生は希望である。",e:"Just as life is fate, life is hope.",m:"candle"},
  {a:"『易経』（作者未詳）",w:"『易経』乾卦",t:"天行は健なり。君子は以て*自ら強めて息まず*。",x:"天行健、君子以自強不息。",e:"The movement of heaven is vigorous; so the noble person strengthens himself without ceasing.",m:"compass"},
  {a:"屈原",w:"『楚辞』「離騒」",t:"路は漫漫として其れ修遠なり。吾将に上下して*求め索めん*とす。",x:"路漫漫其修遠兮、吾将上下而求索。",e:"The road is long and far. I will search high and low.",m:"compass"},
  {a:"荀子",w:"『荀子』勧学篇",t:"青は之を藍より取りて*藍より青し*。",x:"青取之於藍、而青於藍。",e:"Blue comes from the indigo plant, yet is bluer than indigo.",m:"book"},
  {a:"『大学』（作者未詳）",w:"『大学』",t:"苟に日に新たに、*日々に新たに*、又日に新たなり。",x:"苟日新、日日新、又日新。",e:"If you can renew yourself one day, do so every day, and again day after day.",m:"hourglass"},
  {a:"『バガヴァッド・ギーター』（作者未詳）",w:"『バガヴァッド・ギーター』第二章四十七",t:"汝の為すべきは*行為*のみにあり、その果報にはあらず。",e:"Your right is to action alone, never to its fruits.",m:"laurel"},
  {a:"諸葛亮",w:"「誡子書」",t:"淡泊に非ざれば以て*志*を明らかにする無く、寧静に非ざれば以て遠きを致す無し。",x:"非淡泊無以明志、非寧静無以致遠。",e:"Without simplicity there is no way to make one's aims clear; without tranquility there is no way to reach far.",m:"lamp"},
  {a:"王維",w:"「送元二使安西」",t:"君に勧む 更に尽くせ*一杯の酒* 西のかた陽関を出づれば故人無からん",x:"勧君更尽一杯酒、西出陽関無故人。",e:"I urge you, drink one more cup of wine; west of the Yang Pass there will be no old friends.",m:"candle"},
  {a:"李白",w:"「静夜思」",t:"頭を挙げて山月を望み、頭を低れて*故郷*を思ふ。",x:"挙頭望山月、低頭思故郷。",e:"I raise my head and gaze at the mountain moon; I lower my head and think of home.",m:"moon"},
  {a:"李白",w:"「将進酒」",t:"天の我が材を生ずる、*必ず用*有り。",x:"天生我材必有用。",e:"Heaven gave me talents; they must be of use.",m:"laurel"},
  {a:"杜甫",w:"「曲江」",t:"人生七十 *古来稀*なり。",x:"人生七十古来稀。",e:"To reach seventy has been rare since ancient times.",m:"hourglass"},
  {a:"白居易",w:"「長恨歌」",t:"天長く地久しきも時ありて尽きん。此の恨みは綿綿として*尽くる期*無からん。",x:"天長地久有時尽、此恨綿綿無絶期。",e:"Heaven and earth are long-lasting, yet they will end; this sorrow goes on and on, with no time of ending.",m:"moon"},
  {a:"陶淵明",w:"「雑詩」其一",t:"盛年重ねて来たらず、一日再び晨なり難し。時に及んで当に勉励すべし、*歳月*人を待たず。",x:"盛年不重来、一日難再晨。及時当勉励、歳月不待人。",e:"The prime of life does not come twice; a day cannot dawn again. Strive while there is time—the years wait for no one.",m:"hourglass"},
  {a:"蘇軾",w:"「水調歌頭」",t:"但だ願はくは人長久にして、*千里*嬋娟を共にせんことを。",x:"但願人長久、千里共嬋娟。",e:"I only wish that we may live long, and share the beauty of the moon though a thousand miles apart.",m:"moon"},
  {a:"オマル・ハイヤーム",w:"『ルバイヤート』（フィッツジェラルド英訳）",t:"動く指は書き、書き終えれば、また進む。汝の信心も知恵も、それを呼び戻して*半行*も消させはしない。",x:"The Moving Finger writes; and, having writ, Moves on: nor all thy Piety nor Wit Shall lure it back to cancel half a Line.",m:"quill"},
  {a:"サアディー",w:"『薔薇園』第一章",t:"人の子らは互いに*一つの身体*の肢体である。創られしとき、同じ一つの本質から生まれたのだから。",e:"Human beings are members of a whole, in creation of one essence and soul.",m:"laurel"},
  {a:"王陽明",w:"『伝習録』",t:"知は行の始めなり、行は知の*成る*なり。",x:"知是行之始、行是知之成。",e:"Knowing is the beginning of acting; acting is the completion of knowing.",m:"book"},
  {a:"洪自誠",w:"『菜根譚』",t:"花は*半開*を看、酒は微酔に飲む。此の中に大いに佳趣あり。",x:"花看半開、酒飲微酔、此中大有佳趣。",e:"Look at flowers half-open; drink wine to slight tipsiness. Herein lies great delight.",m:"candle"},
  {a:"孔子",w:"『論語』雍也",t:"之を知る者は之を好む者に如かず。之を好む者は之を*楽しむ*者に如かず。",x:"知之者不如好之者、好之者不如楽之者。",e:"Those who know it are not equal to those who love it; those who love it are not equal to those who delight in it.",m:"book"},
  {a:"孔子",w:"『論語』里仁",t:"*徳*は孤ならず、必ず隣有り。",x:"徳不孤、必有隣。",e:"Virtue is never alone; it always has neighbors.",m:"lamp"},
  {a:"孔子",w:"『論語』衛霊公",t:"過ちて*改めざる*、是を過ちと謂う。",x:"過而不改、是謂過矣。",e:"To err and not to correct it—that is what is called an error.",m:"quill"},
  {a:"老子",w:"『老子』第四十一章",t:"大器は*晩成*す。",x:"大器晩成。",e:"The greatest vessel takes longest to complete.",m:"hourglass"},
  {a:"老子",w:"『老子』第三十六章",t:"*柔弱*は剛強に勝つ。",x:"柔弱勝剛強。",e:"The soft and weak overcome the hard and strong.",m:"tree"},
  {a:"孫子",w:"『孫子』謀攻篇",t:"百戦百勝は善の善なる者に非ざるなり。*戦わずして*人の兵を屈するは善の善なる者なり。",x:"百戦百勝、非善之善者也。不戦而屈人之兵、善之善者也。",e:"To win a hundred victories in a hundred battles is not the height of skill. To subdue the enemy without fighting is the height of skill.",m:"laurel"},
  {a:"孟子",w:"『孟子』梁恵王上",t:"*恒産*無ければ、因りて恒心無し。",x:"無恒産、因無恒心。",e:"Without a constant livelihood, there will be no constant heart.",m:"book"},
  {a:"荘子",w:"『荘子』秋水",t:"井蛙は以て*海*を語るべからず。虚に拘ればなり。",x:"井蛙不可以語於海者、拘於虚也。",e:"You cannot speak of the sea to a frog in a well; it is confined to its own space.",m:"telescope"},
  {a:"ブッダ",w:"『ダンマパダ』第五偈",t:"怨みは怨みによって果たされず、*怨みを捨てて*こそ果たされる。これは永遠の真理である。",e:"Hatred is never appeased by hatred in this world; by non-hatred alone is hatred appeased. This is an eternal law.",m:"lamp"},
  {a:"ブッダ",w:"『ダンマパダ』第百六十偈",t:"*自己*こそ自分の主である。他人がどうして自分の主であろうか。",e:"Oneself is one's own protector; what other protector could there be?",m:"candle"},
  {a:"司馬遷",w:"「報任少卿書」",t:"人は固より一死有り。或いは*泰山*より重く、或いは鴻毛より軽し。",x:"人固有一死、或重於泰山、或軽於鴻毛。",e:"Everyone must die once; a death may be heavier than Mount Tai or lighter than a goose feather.",m:"hourglass"},
  {a:"魯迅",w:"『故郷』",t:"もともと地上には*道*はない。歩く人が多くなれば、それが道になるのだ。",x:"其実地上本没有路、走的人多了、也便成了路。",e:"Actually the earth had no roads to begin with; when many people walk one way, a road is made.",m:"compass"},
  {a:"ガンディー",w:"「ハリジャン」紙（1935年）",t:"*非暴力*は人類に与えられた最大の力である。",x:"Non-violence is the greatest force at the disposal of mankind.",m:"laurel"},
  {a:"プラトン",w:"『テアイテトス』",t:"*驚き*こそ、知を愛する者の情念である。哲学の始まりはこれ以外にない。",x:"μάλα γὰρ φιλοσόφου τοῦτο τὸ πάθος, τὸ θαυμάζειν· οὐ γὰρ ἄλλη ἀρχὴ φιλοσοφίας ἢ αὕτη.",e:"Wonder is the feeling of a philosopher, and philosophy begins in wonder.",m:"telescope"},
  {a:"キケロ",w:"『弁論家について』",t:"歴史は人生の*教師*である。",x:"Historia magistra vitae.",e:"History is the teacher of life.",m:"book"},
  {a:"オウィディウス",w:"『変身物語』第十五巻",t:"*時*は万物を貪り食う。",x:"Tempus edax rerum.",e:"Time, the devourer of all things.",m:"hourglass"},
  {a:"トマス・ア・ケンピス",w:"『キリストにならいて』第一巻",t:"人は思い、神は*導く*。",x:"Homo proponit, sed Deus disponit.",e:"Man proposes, but God disposes.",m:"candle"},
  {a:"レオナルド・ダ・ヴィンチ",w:"『手稿』",t:"よく過ごした一日が幸せな眠りをもたらすように、*よく生きた一生*は幸せな死をもたらす。",x:"Sì come una giornata bene spesa dà lieto dormire, così una vita bene usata dà lieto morire.",e:"As a well-spent day brings happy sleep, so a life well used brings happy death.",m:"candle"},
  {a:"エラスムス",w:"『格言集』",t:"*盲人の国*では、片目の者が王である。",x:"In regione caecorum rex est luscus.",e:"In the land of the blind, the one-eyed man is king.",m:"lamp"},
  {a:"ラブレー",w:"『ガルガンチュア』序詩",t:"*笑う*ことは人間に固有のものだから。",x:"Pour ce que rire est le propre de l'homme.",e:"For laughter is proper to man.",m:"bell"},
  {a:"ガリレオ",w:"『偽金鑑識官』",t:"宇宙という書物は*数学*の言葉で書かれている。",x:"Egli è scritto in lingua matematica.",e:"The book of the universe is written in the language of mathematics.",m:"telescope"},
  {a:"ホッブズ",w:"『リヴァイアサン』第十三章",t:"*万人*の万人に対する闘争。",x:"a warre, as is of every man, against every man",e:"A war of every man against every man.",m:"hourglass"},
  {a:"ラ・フォンテーヌ",w:"『寓話』「ライオンと鼠」",t:"*忍耐*と時間は、力や怒りよりも多くを成し遂げる。",x:"Patience et longueur de temps font plus que force ni que rage.",e:"Patience and length of time do more than strength or rage.",m:"hourglass"},
  {a:"ラ・ブリュイエール",w:"『カラクテール』",t:"すべては言われてしまった。人間が考えるようになって七千年、われわれは*遅すぎた*のだ。",x:"Tout est dit, et l'on vient trop tard depuis plus de sept mille ans qu'il y a des hommes et qui pensent.",e:"Everything has been said, and we come too late, after more than seven thousand years of men who think.",m:"quill"},
  {a:"ポープ",w:"『批評論』",t:"過つは人の常、*許す*は神の業。",x:"To err is human, to forgive divine.",m:"laurel"},
  {a:"ベンジャミン・フランクリン",w:"『貧しいリチャードの暦』",t:"*早寝早起き*は、人を健康に、豊かに、賢くする。",x:"Early to bed and early to rise, makes a man healthy, wealthy and wise.",m:"lamp"},
  {a:"サミュエル・ジョンソン",w:"ボズウェル『ジョンソン伝』（1777年）",t:"*ロンドン*に飽きた者は人生に飽きた者だ。ロンドンには人生が与えうるすべてがある。",x:"When a man is tired of London, he is tired of life; for there is in London all that life can afford.",m:"lamp"},
  {a:"アダム・スミス",w:"『国富論』第四篇第二章",t:"彼は*見えざる手*に導かれて、みずから意図していなかった目的を促進することになる。",x:"He is in this, as in many other cases, led by an invisible hand to promote an end which was no part of his intention.",m:"compass"},
  {a:"シラー",w:"『人間の美的教育について』第十五書簡",t:"人間は*遊ぶ*ときにのみ、完全な人間である。",x:"Der Mensch ist nur da ganz Mensch, wo er spielt.",e:"Man is only fully human when he plays.",m:"bell"},
  {a:"ワーズワース",w:"「わが心は躍る」",t:"*子ども*は大人の父である。",x:"The Child is father of the Man.",m:"tree"},
  {a:"ヘーゲル",w:"『法の哲学』序文",t:"*ミネルヴァの梟*は、迫りくる黄昏にはじめて飛び立つ。",x:"Die Eule der Minerva beginnt erst mit der einbrechenden Dämmerung ihren Flug.",e:"The owl of Minerva spreads its wings only with the falling of the dusk.",m:"bird"},
  {a:"バイロン",w:"『ドン・ジュアン』第十四歌",t:"真実はつねに奇なり、*小説*よりも奇なり。",x:"'Tis strange—but true; for truth is always strange; Stranger than fiction.",m:"book"},
  {a:"シェリー",w:"「西風に寄せる歌」",t:"*冬*来たりなば、春遠からじ。",x:"If Winter comes, can Spring be far behind?",m:"tree"},
  {a:"ハイネ",w:"『アルマンゾル』",t:"*本*を焼く者は、やがて人間をも焼くようになる。",x:"Dort, wo man Bücher verbrennt, verbrennt man am Ende auch Menschen.",e:"Where they burn books, they will in the end also burn people.",m:"book"},
  {a:"バルザック",w:"『ゴリオ爺さん』結び",t:"さあ、今度は俺とお前の*勝負*だ！",x:"À nous deux maintenant !",e:"Now it's between the two of us!",m:"compass"},
  {a:"テニスン",w:"『イン・メモリアム』",t:"愛して失うほうが、一度も*愛さない*よりはよい。",x:"'Tis better to have loved and lost than never to have loved at all.",m:"candle"},
  {a:"リンカーン",w:"ゲティスバーグ演説（1863年）",t:"人民の、人民による、*人民のため*の政治。",x:"government of the people, by the people, for the people",m:"laurel"},
  {a:"ブラウニング",w:"『ピッパが通る』（上田敏訳）",t:"神、そらに知ろしめす。すべて世は*事も無し*。",x:"God's in his heaven—All's right with the world!",m:"bird"},
  {a:"マルクス",w:"「フォイエルバッハに関するテーゼ」十一",t:"哲学者たちは世界をさまざまに解釈してきたにすぎない。肝心なのは、それを*変える*ことである。",x:"Die Philosophen haben die Welt nur verschieden interpretiert; es kömmt aber darauf an, sie zu verändern.",e:"The philosophers have only interpreted the world in various ways; the point is to change it.",m:"quill"},
  {a:"パスツール",w:"リール大学での講演（1854年）",t:"観察の領域において、偶然は*準備された心*にしか味方しない。",x:"Dans les champs de l'observation, le hasard ne favorise que les esprits préparés.",e:"In the fields of observation, chance favors only the prepared mind.",m:"telescope"},
  {a:"イプセン",w:"『民衆の敵』第五幕",t:"世界で最も強い人間とは、最も*孤独*に立つ者だ。",x:"Den stærkeste mand i verden, det er han, som står mest alene.",e:"The strongest man in the world is he who stands most alone.",m:"lamp"},
  {a:"スティーヴンソン",w:"『若い人々のために』「エル・ドラド」",t:"希望をもって*旅する*ことは、到着することよりも良い。",x:"To travel hopefully is a better thing than to arrive.",m:"compass"},
  {a:"ゴッホ",w:"弟テオへの手紙（1888年7月、アルル）",t:"それについて私は何も知らないと言おう。けれど*星*を見ると、いつも夢を見る。",x:"Pour moi je déclare ne rien savoir là-dessus. Mais toujours la vue des étoiles me fait rêver.",e:"For my part I declare I know nothing about it. But the sight of the stars always makes me dream.",m:"telescope"},
  {a:"コナン・ドイル",w:"『四つの署名』",t:"不可能なものを取り除いて残ったものは、どれほどありそうになくても、*真実*である。",x:"When you have eliminated the impossible, whatever remains, however improbable, must be the truth.",m:"key"},
  {a:"チェーホフ",w:"スヴォーリン宛の手紙（1888年）",t:"医学は私の正妻で、*文学*は愛人だ。",x:"Медицина — моя законная жена, а литература — любовница.",e:"Medicine is my lawful wife, and literature is my mistress.",m:"quill"},
  {a:"サンタヤーナ",w:"『理性の生活』",t:"過去を*記憶*できない者は、それを繰り返す運命にある。",x:"Those who cannot remember the past are condemned to repeat it.",m:"hourglass"},
  {a:"イェイツ",w:"「彼は天の布を望む」",t:"そっと踏んでください。あなたは私の*夢*を踏んでいるのだから。",x:"Tread softly because you tread on my dreams.",m:"moon"},
  {a:"キプリング",w:"「もし」",t:"周りの皆が正気を失い、それをお前のせいにしても、お前が*冷静*でいられるなら。",x:"If you can keep your head when all about you are losing theirs and blaming it on you.",m:"compass"},
  {a:"ロマン・ロラン",w:"『ジャン・クリストフ』",t:"*英雄*とは、自分にできることをした人である。",x:"Un héros, c'est celui qui fait ce qu'il peut.",e:"A hero is one who does what he can.",m:"laurel"},
  {a:"ジッド",w:"『地の糧』",t:"ナタナエル、私は君に*熱情*を教えよう。",x:"Nathanaël, je t'enseignerai la ferveur.",e:"Nathanael, I will teach you fervor.",m:"candle"},
  {a:"ラッセル",w:"『幸福論』",t:"幸福の秘訣はこうだ。*興味*をできるだけ広く持ち、興味を引く人や物への反応を、敵意ではなくできるだけ好意的なものにすること。",x:"The secret of happiness is this: let your interests be as wide as possible, and let your reactions to the things and persons that interest you be as far as possible friendly rather than hostile.",m:"telescope"},
  {a:"チェスタトン",w:"『世界の問題点』",t:"やる価値のあることは、*下手にやる*価値もある。",x:"If a thing is worth doing, it is worth doing badly.",m:"quill"},
  {a:"チャーチル",w:"下院演説（1940年5月13日）",t:"私が捧げられるものは、*血と労苦と涙と汗*のほかにない。",x:"I have nothing to offer but blood, toil, tears and sweat.",m:"laurel"},
  {a:"シュヴァイツァー",w:"『文化と倫理』",t:"私は、生きようとする生命に囲まれた、*生きようとする生命*である。",x:"Ich bin Leben, das leben will, inmitten von Leben, das leben will.",e:"I am life that wants to live, in the midst of life that wants to live.",m:"tree"},
  {a:"ユング",w:"手紙（1916年）",t:"外を見る者は夢を見る。*内*を見る者は目覚める。",x:"Wer nach außen schaut, träumt; wer nach innen schaut, erwacht.",e:"Who looks outside, dreams; who looks inside, awakes.",m:"lamp"},
  {a:"ブレヒト",w:"『ガリレイの生涯』",t:"*英雄*を必要とする国は不幸だ。",x:"Unglücklich das Land, das Helden nötig hat.",e:"Unhappy the land that is in need of heroes.",m:"bell"},
  {a:"ケストナー",w:"「モラール」（『短く、はっきりと』）",t:"良いことは、*行わない*かぎり存在しない。",x:"Es gibt nichts Gutes, außer man tut es.",e:"There is nothing good unless you do it.",m:"key"},
  {a:"ハンナ・アーレント",w:"『エルサレムのアイヒマン』",t:"言葉に尽くしがたい、考えることもできない、*悪の凡庸さ*。",x:"the fearsome, word-and-thought-defying banality of evil",m:"book"},
  {a:"ベケット",w:"『いざ最悪の方へ』",t:"もう一度やってみよ。もう一度失敗せよ。*もっとうまく*失敗せよ。",x:"Try again. Fail again. Fail better.",m:"quill"},
  {a:"レイチェル・カーソン",w:"『センス・オブ・ワンダー』",t:"知ることは、*感じる*ことの半分も重要ではない。",x:"It is not half so important to know as to feel.",m:"tree"},
  {a:"シモーヌ・ヴェイユ",w:"ジョエ・ブスケ宛の手紙（1942年）",t:"*注意*は、最も稀で最も純粋な寛容の形である。",x:"L'attention est la forme la plus rare et la plus pure de la générosité.",e:"Attention is the rarest and purest form of generosity.",m:"candle"},
  {a:"ケネディ",w:"大統領就任演説（1961年）",t:"国があなたのために何をしてくれるかではなく、あなたが*国のために*何ができるかを問おう。",x:"Ask not what your country can do for you—ask what you can do for your country.",m:"laurel"},
  {a:"ファインマン",w:"カリフォルニア工科大学卒業式講演（1974年）",t:"第一の原則は、*自分を騙さない*ことだ。そして、自分こそ最も騙しやすい相手である。",x:"The first principle is that you must not fool yourself—and you are the easiest person to fool.",m:"telescope"},
  {a:"ヴォネガット",w:"『スローターハウス5』",t:"*そういうものだ*。",x:"So it goes.",m:"hourglass"},
  {a:"キング牧師",w:"ワシントン大行進での演説（1963年）",t:"私には*夢*がある。",x:"I have a dream.",m:"laurel"},
  {a:"ソクラテス",w:"プラトン『ソクラテスの弁明』",t:"私は、知らないことを*知らない*と思っている、その点でわずかに知恵があるらしい。",x:"ἔοικα γοῦν τούτου γε σμικρῷ τινι αὐτῷ τούτῳ σοφώτερος εἶναι, ὅτι ἃ μὴ οἶδα οὐδὲ οἴομαι εἰδέναι.",e:"I seem to be wiser than he to this small extent: that I do not think I know what I do not know.",m:"lamp"},
  {a:"ヘラクレイトス",w:"断片（伝）",t:"*万物*は流転する。",x:"πάντα ῥεῖ",e:"Everything flows.",m:"hourglass"},
  {a:"アリストテレス",w:"『形而上学』冒頭",t:"すべての人間は、生まれつき、*知る*ことを欲する。",x:"πάντες ἄνθρωποι τοῦ εἰδέναι ὀρέγονται φύσει.",e:"All human beings by nature desire to know.",m:"book"},
  {a:"セネカ",w:"『倫理書簡集』第104書簡",t:"困難だから*やろうとしない*のではない。やろうとしないから困難なのだ。",x:"Non quia difficilia sunt non audemus, sed quia non audemus difficilia sunt.",e:"It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.",m:"compass"},
  {a:"エピクテトス",w:"『提要（エンケイリディオン）』五",t:"人を悩ませるのは物事そのものではなく、それについての*判断*である。",x:"Ταράσσει τοὺς ἀνθρώπους οὐ τὰ πράγματα, ἀλλὰ τὰ περὶ τῶν πραγμάτων δόγματα.",e:"People are disturbed not by things, but by the views they take of them.",m:"lamp"},
  {a:"マルクス・アウレリウス",w:"『自省録』第五巻",t:"あなたの魂は、あなたの*思考*によって染められる。",x:"Οἷα ἂν πολλάκις φαντασθῇς, τοιαύτη σοι ἔσται ἡ διάνοια· βάπτεται γὰρ ὑπὸ τῶν φαντασιῶν ἡ ψυχή.",e:"Such as are your habitual thoughts, such also will be the character of your mind; for the soul is dyed by the thoughts.",m:"candle"},
  {a:"モンテーニュ",w:"『エセー』第一巻三十九章",t:"世の中で最も偉大なことは、*自分自身*のものであることを知ることだ。",x:"La plus grande chose du monde, c'est de savoir être à soi.",e:"The greatest thing in the world is to know how to belong to oneself.",m:"key"},
  {a:"パスカル",w:"『パンセ』",t:"*クレオパトラの鼻*。それがもっと短かったなら、地上の全表面は変わっていただろう。",x:"Le nez de Cléopâtre, s'il eût été plus court, toute la face de la terre aurait changé.",e:"Cleopatra's nose: had it been shorter, the whole face of the earth would have changed.",m:"hourglass"},
  {a:"ゲーテ",w:"フリードリヒ・フォン・ミュラーとの対話（1819年4月24日）",t:"人は、すでに*知っている*ものしか見ない。",x:"Man erblickt nur, was man schon weiß und versteht.",e:"One sees only what one already knows and understands.",m:"telescope"},
  {a:"ソロー",w:"『ウォールデン 森の生活』",t:"時は、私が*釣り*をする川にすぎない。",x:"Time is but the stream I go a-fishing in.",m:"hourglass"},
  {a:"ホイットマン",w:"『草の葉』「ぼく自身の歌」",t:"私は*自分*を祝福し、自分を歌う。",x:"I celebrate myself, and sing myself.",m:"laurel"},
  {a:"ディキンソン",w:"詩 260番",t:"私は*誰でもない*！あなたは誰？",x:"I'm Nobody! Who are you?",m:"bird"},
  {a:"ドストエフスキー",w:"『死の家の記録』",t:"金は鋳造された*自由*である。",x:"Деньги есть чеканенная свобода.",e:"Money is coined liberty.",m:"key"},
  {a:"キルケゴール",w:"『死に至る病』",t:"あえて*冒険*することは不安を招く。しかし冒険しないことは、自分自身を失うことだ。",x:"At vove er at tabe fodfæstet en kort stund. Ikke at vove er at tabe sig selv.",e:"To venture causes anxiety, but not to venture is to lose one's self.",m:"compass"},
  {a:"マーク・トウェイン",w:"『ノートブック』（1894年）",t:"*本当のこと*を言えば、何も覚えておく必要がない。",x:"If you tell the truth you don't have to remember anything.",m:"quill"},
  {a:"ニーチェ",w:"『人間的、あまりに人間的』283",t:"一日の三分の二を自分のために持たない者は、*奴隷*である。",x:"Wer nicht zwei Drittel seines Tages für sich selbst hat, ist ein Sklave.",e:"Whoever does not have two-thirds of his day for himself is a slave.",m:"hourglass"},
  {a:"ワイルド",w:"『真面目が肝心』第一幕",t:"真実はめったに純粋ではないし、決して*単純*ではない。",x:"The truth is rarely pure and never simple.",m:"quill"},
  {a:"リルケ",w:"『若き詩人への手紙』",t:"愛することもまた良い。なぜなら*愛*は難しいからだ。",x:"Es ist auch gut, zu lieben: denn Liebe ist schwer.",e:"It is also good to love: because love is difficult.",m:"candle"},
  {a:"ヘッセ",w:"『シッダールタ』",t:"*知識*は伝えることができるが、知恵は伝えることができない。",x:"Wissen kann man mitteilen, Weisheit aber nicht.",e:"Knowledge can be communicated, but not wisdom.",m:"book"},
  {a:"カフカ",w:"「罪、苦悩、希望、真実の道についての考察」五十二",t:"君と世界との戦いでは、*世界*に加勢せよ。",x:"Im Kampf zwischen dir und der Welt sekundiere der Welt.",e:"In the fight between you and the world, back the world.",m:"compass"},
  {a:"ウルフ",w:"『自分ひとりの部屋』",t:"うまく*食事*をしなければ、よく考え、よく愛し、よく眠ることはできない。",x:"One cannot think well, love well, sleep well, if one has not dined well.",m:"lamp"},
  {a:"サン＝テグジュペリ",w:"『星の王子さま』献辞",t:"大人は、はじめはみんな*子ども*だった。でも、それを覚えている大人は少ない。",x:"Toutes les grandes personnes ont d'abord été des enfants. (Mais peu d'entre elles s'en souviennent.)",e:"All grown-ups were once children—but only few of them remember it.",m:"tree"},
  {a:"アインシュタイン",w:"カール・ゼーリヒ宛の手紙（1952年）",t:"私は特別に才能があるわけではない。ただ、情熱的に*好奇心*が強いだけだ。",x:"Ich habe keine besondere Begabung, sondern bin nur leidenschaftlich neugierig.",e:"I have no special talent. I am only passionately curious.",m:"telescope"},
  {a:"ヘミングウェイ",w:"ドロシー・パーカー「芸術家の報酬」（『ニューヨーカー』1929年）での発言",t:"私が言っているのは、圧力の下での*気品*のことだ。",x:"I mean, grace under pressure.",m:"laurel"},
  {a:"カミュ",w:"『ペスト』",t:"ペストと闘う唯一の方法は、*誠実さ*だ。",x:"La seule façon de lutter contre la peste, c'est l'honnêteté.",e:"The only way to fight the plague is with honesty.",m:"candle"},
  {a:"フランクル",w:"『夜と霧』",t:"人間の最後の自由——与えられた状況のなかで、自分の*態度*を選ぶ自由。",x:"the last of the human freedoms—to choose one's attitude in any given set of circumstances",m:"lamp"}
];
