// 栞 SHIORI — 引用データ
// 実在する名句のみ。出典（作品名）を必ず添える。ハイライトしたい語は *語* で囲む。
// 著者: y=生没年, o=出身, b=ひとこと紹介, born=生年(並び順用, 紀元前は負数), r=地域(jp/east/west)
window.SHIORI_AUTHORS = {
  "山上憶良":{y:"660年頃–733年頃",o:"日本",b:"万葉の歌人。子や貧しさを詠んだ",born:660,r:"jp"},
  "紀貫之":{y:"872年頃–945年",o:"日本",b:"『古今和歌集』撰者。『土佐日記』の作者",born:872,r:"jp"},
  "小野小町":{y:"9世紀",o:"日本",b:"六歌仙のひとり。恋と無常の歌人",born:825,r:"jp"},
  "清少納言":{y:"966年頃–1025年頃",o:"日本",b:"中宮定子に仕えた女房。随筆の祖",born:966,r:"jp"},
  "紫式部":{y:"970年代–1010年代",o:"日本",b:"『源氏物語』の作者。宮廷に仕えた女房",born:973,r:"jp"},
  "西行":{y:"1118–1190",o:"日本",b:"武士から出家した漂泊の歌人",born:1118,r:"jp"},
  "鴨長明":{y:"1155–1216",o:"日本",b:"歌人。晩年は方丈の庵に隠棲した",born:1155,r:"jp"},
  "親鸞":{y:"1173–1263",o:"日本",b:"浄土真宗の開祖。他力の信仰を説いた",born:1173,r:"jp"},
  "平家物語（作者未詳）":{y:"13世紀成立",o:"日本",b:"琵琶法師が語り継いだ軍記物語",born:1220,r:"jp"},
  "道元":{y:"1200–1253",o:"日本",b:"曹洞宗の開祖。只管打坐を説いた禅僧",born:1200,r:"jp"},
  "吉田兼好":{y:"1283年頃–1352年頃",o:"日本",b:"歌人・随筆家。俗世を離れて『徒然草』を著した",born:1283,r:"jp"},
  "世阿弥":{y:"1363年頃–1443年頃",o:"日本",b:"能を大成した役者・作者",born:1363,r:"jp"},
  "千利休":{y:"1522–1591",o:"日本",b:"わび茶を完成させた茶人",born:1522,r:"jp"},
  "宮本武蔵":{y:"1584年頃–1645",o:"日本",b:"二天一流の剣術家。晩年に兵法書を著した",born:1584,r:"jp"},
  "貝原益軒":{y:"1630–1714",o:"日本",b:"江戸前期の儒学者・本草学者",born:1630,r:"jp"},
  "松尾芭蕉":{y:"1644–1694",o:"日本",b:"俳諧を芸術に高めた俳人。旅に生きた",born:1644,r:"jp"},
  "山本常朝":{y:"1659–1719",o:"日本",b:"佐賀藩士。口述が『葉隠』にまとめられた",born:1659,r:"jp"},
  "上杉鷹山":{y:"1751–1822",o:"日本",b:"米沢藩を立て直した名君",born:1751,r:"jp"},
  "良寛":{y:"1758–1831",o:"日本",b:"越後の禅僧・歌人。子どもと手毬で遊んだ",born:1758,r:"jp"},
  "小林一茶":{y:"1763–1828",o:"日本",b:"信濃の俳人。小さな命を詠んだ",born:1763,r:"jp"},
  "佐藤一斎":{y:"1772–1859",o:"日本",b:"幕末の儒学者。多くの志士を育てた",born:1772,r:"jp"},
  "二宮尊徳":{y:"1787–1856",o:"日本",b:"農村復興に尽くした実践家",born:1787,r:"jp"},
  "西郷隆盛":{y:"1828–1877",o:"日本",b:"維新の指導者。遺訓が『南洲翁遺訓』に残る",born:1828,r:"jp"},
  "吉田松陰":{y:"1830–1859",o:"日本",b:"松下村塾で若者を育てた思想家",born:1830,r:"jp"},
  "福澤諭吉":{y:"1835–1901",o:"日本",b:"啓蒙思想家。慶應義塾を創設した",born:1835,r:"jp"},
  "渋沢栄一":{y:"1840–1931",o:"日本",b:"約500の企業を育てた実業家",born:1840,r:"jp"},
  "内村鑑三":{y:"1861–1930",o:"日本",b:"無教会主義のキリスト教思想家",born:1861,r:"jp"},
  "森鷗外":{y:"1862–1922",o:"日本",b:"軍医にして小説家・翻訳家",born:1862,r:"jp"},
  "新渡戸稲造":{y:"1862–1933",o:"日本",b:"教育者。英文で日本の精神を世界に伝えた",born:1862,r:"jp"},
  "岡倉天心":{y:"1863–1913",o:"日本",b:"美術行政家。英文で日本の美を語った",born:1863,r:"jp"},
  "夏目漱石":{y:"1867–1916",o:"日本",b:"近代日本文学を代表する小説家・英文学者",born:1867,r:"jp"},
  "正岡子規":{y:"1867–1902",o:"日本",b:"俳句・短歌を革新した文学者。病床で書き続けた",born:1867,r:"jp"},
  "西田幾多郎":{y:"1870–1945",o:"日本",b:"京都学派を築いた哲学者",born:1870,r:"jp"},
  "島崎藤村":{y:"1872–1943",o:"日本",b:"詩人から小説家へ。自然主義文学の旗手",born:1872,r:"jp"},
  "与謝野晶子":{y:"1878–1942",o:"日本",b:"情熱の歌人。女性の自立を訴えた",born:1878,r:"jp"},
  "有島武郎":{y:"1878–1923",o:"日本",b:"白樺派の小説家",born:1878,r:"jp"},
  "種田山頭火":{y:"1882–1940",o:"日本",b:"自由律俳句の行乞俳人",born:1882,r:"jp"},
  "高村光太郎":{y:"1883–1956",o:"日本",b:"彫刻家・詩人。『智恵子抄』の作者",born:1883,r:"jp"},
  "志賀直哉":{y:"1883–1971",o:"日本",b:"「小説の神様」と呼ばれた白樺派の作家",born:1883,r:"jp"},
  "武者小路実篤":{y:"1885–1976",o:"日本",b:"白樺派の作家。「新しき村」を興した",born:1885,r:"jp"},
  "尾崎放哉":{y:"1885–1926",o:"日本",b:"自由律俳句の俳人。小豆島で没した",born:1885,r:"jp"},
  "石川啄木":{y:"1886–1912",o:"日本",b:"生活を詠んだ夭折の歌人",born:1886,r:"jp"},
  "谷崎潤一郎":{y:"1886–1965",o:"日本",b:"耽美の小説家。『細雪』の作者",born:1886,r:"jp"},
  "芥川龍之介":{y:"1892–1927",o:"日本",b:"短編の名手。芥川賞にその名を残す",born:1892,r:"jp"},
  "松下幸之助":{y:"1894–1989",o:"日本",b:"パナソニック創業者。「経営の神様」",born:1894,r:"jp"},
  "宮沢賢治":{y:"1896–1933",o:"日本",b:"詩人・童話作家。農学校の教師でもあった",born:1896,r:"jp"},
  "三木清":{y:"1897–1945",o:"日本",b:"哲学者。獄中で没した",born:1897,r:"jp"},
  "井伏鱒二":{y:"1898–1993",o:"日本",b:"『山椒魚』『黒い雨』の小説家",born:1898,r:"jp"},
  "川端康成":{y:"1899–1972",o:"日本",b:"日本人初のノーベル文学賞作家",born:1899,r:"jp"},
  "梶井基次郎":{y:"1901–1932",o:"日本",b:"感覚の冴えた短編を残した夭折の作家",born:1901,r:"jp"},
  "堀辰雄":{y:"1904–1953",o:"日本",b:"軽井沢を愛した小説家",born:1904,r:"jp"},
  "坂口安吾":{y:"1906–1955",o:"日本",b:"無頼派の作家・評論家",born:1906,r:"jp"},
  "中原中也":{y:"1907–1937",o:"日本",b:"30歳で世を去った抒情詩人",born:1907,r:"jp"},
  "太宰治":{y:"1909–1948",o:"日本",b:"無頼派の小説家。『人間失格』の作者",born:1909,r:"jp"},
  "中島敦":{y:"1909–1942",o:"日本",b:"漢籍に材をとった短編の名手",born:1909,r:"jp"},
  "神谷美恵子":{y:"1914–1979",o:"日本",b:"精神科医。ハンセン病療養所で人々に寄り添った",born:1914,r:"jp"},

  "孔子":{y:"前551–前479",o:"中国",b:"儒家の祖。弟子との問答が『論語』に残る",born:-551,r:"east"},
  "老子":{y:"前6世紀頃（諸説あり）",o:"中国",b:"道家の祖とされる伝説的な思想家",born:-570,r:"east"},
  "孫子":{y:"前6〜5世紀頃",o:"中国",b:"兵法家。『孫子』の著者とされる",born:-544,r:"east"},
  "ソクラテス":{y:"前470年頃–前399",o:"古代ギリシア",b:"問答で人々を目覚めさせた哲学者。著作は残さなかった",born:-470,r:"west"},
  "アイスキュロス":{y:"前525年頃–前456",o:"古代ギリシア",b:"ギリシア悲劇の父",born:-525,r:"west"},
  "ソポクレス":{y:"前497年頃–前406年頃",o:"古代ギリシア",b:"『オイディプス王』の悲劇詩人",born:-497,r:"west"},
  "ヘラクレイトス":{y:"前540年頃–前480年頃",o:"古代ギリシア",b:"「万物は流転する」の哲学者",born:-540,r:"west"},
  "ブッダ":{y:"前5世紀頃",o:"古代インド",b:"仏教の開祖。教えは弟子たちが伝えた",born:-480,r:"east"},
  "アリストテレス":{y:"前384–前322",o:"古代ギリシア",b:"万学の祖。プラトンの弟子",born:-384,r:"west"},
  "孟子":{y:"前372年頃–前289年頃",o:"中国",b:"性善説を唱えた儒家の思想家",born:-372,r:"east"},
  "荘子":{y:"前369年頃–前286年頃",o:"中国",b:"自由な寓話で世を相対化した思想家",born:-369,r:"east"},
  "エピクロス":{y:"前341–前270",o:"古代ギリシア",b:"心の平静を説いた「庭園」の哲学者",born:-341,r:"west"},
  "司馬遷":{y:"前145年頃–前86年頃",o:"中国",b:"『史記』を完成させた歴史家",born:-145,r:"east"},
  "ウェルギリウス":{y:"前70–前19",o:"古代ローマ",b:"ローマ最大の詩人。『アエネーイス』の作者",born:-70,r:"west"},
  "ホラティウス":{y:"前65–前8",o:"古代ローマ",b:"抒情詩人。「カルペ・ディエム」の人",born:-65,r:"west"},
  "セネカ":{y:"前4年頃–65",o:"古代ローマ",b:"ストア派の哲学者。皇帝ネロの師",born:-4,r:"west"},
  "エピクテトス":{y:"55年頃–135年頃",o:"古代ローマ",b:"奴隷の身から哲学者へ。ストア派",born:55,r:"west"},
  "マルクス・アウレリウス":{y:"121–180",o:"古代ローマ",b:"哲人皇帝。陣中で自分に向けた手記を書いた",born:121,r:"west"},
  "アウグスティヌス":{y:"354–430",o:"北アフリカ・ローマ帝国",b:"教父。『告白』で内面を語った",born:354,r:"west"},
  "陶淵明":{y:"365–427",o:"中国",b:"官を捨て田園に帰った詩人",born:365,r:"east"},
  "杜甫":{y:"712–770",o:"中国",b:"「詩聖」と呼ばれる唐の詩人",born:712,r:"east"},
  "ダンテ":{y:"1265–1321",o:"イタリア",b:"『神曲』でイタリア語文学を築いた詩人",born:1265,r:"west"},
  "マキャヴェリ":{y:"1469–1527",o:"イタリア",b:"フィレンツェの外交官・政治思想家",born:1469,r:"west"},
  "モンテーニュ":{y:"1533–1592",o:"フランス",b:"「エセー（随想録）」という形式を生んだ思索家",born:1533,r:"west"},
  "セルバンテス":{y:"1547–1616",o:"スペイン",b:"近代小説の祖。『ドン・キホーテ』の作者",born:1547,r:"west"},
  "フランシス・ベーコン":{y:"1561–1626",o:"イギリス",b:"経験論の哲学者・政治家",born:1561,r:"west"},
  "シェイクスピア":{y:"1564–1616",o:"イギリス",b:"英語圏最大の劇作家・詩人",born:1564,r:"west"},
  "ジョン・ダン":{y:"1572–1631",o:"イギリス",b:"形而上詩人。聖職者でもあった",born:1572,r:"west"},
  "デカルト":{y:"1596–1650",o:"フランス",b:"近代哲学の父。方法的懐疑",born:1596,r:"west"},
  "ミルトン":{y:"1608–1674",o:"イギリス",b:"失明ののち『失楽園』を口述した詩人",born:1608,r:"west"},
  "ラ・ロシュフコー":{y:"1613–1680",o:"フランス",b:"人間の自己愛を見抜いた箴言家",born:1613,r:"west"},
  "パスカル":{y:"1623–1662",o:"フランス",b:"数学者・物理学者・思想家。39歳で没した",born:1623,r:"west"},
  "スピノザ":{y:"1632–1677",o:"オランダ",b:"レンズ磨きで生計を立てた哲学者",born:1632,r:"west"},
  "ニュートン":{y:"1642–1727",o:"イギリス",b:"万有引力を見出した物理学者",born:1642,r:"west"},
  "ヴォルテール":{y:"1694–1778",o:"フランス",b:"啓蒙の世紀を代表する作家・思想家",born:1694,r:"west"},
  "ルソー":{y:"1712–1778",o:"ジュネーヴ・フランス",b:"『社会契約論』『エミール』の思想家",born:1712,r:"west"},
  "カント":{y:"1724–1804",o:"ドイツ",b:"批判哲学を打ち立てた。生涯ケーニヒスベルクを離れず",born:1724,r:"west"},
  "ゲーテ":{y:"1749–1832",o:"ドイツ",b:"詩人・劇作家・自然科学者。ドイツ文学の巨匠",born:1749,r:"west"},
  "ブレイク":{y:"1757–1827",o:"イギリス",b:"幻視の詩人・版画家",born:1757,r:"west"},
  "オースティン":{y:"1775–1817",o:"イギリス",b:"結婚と家庭を鋭く描いた小説家",born:1775,r:"west"},
  "スタンダール":{y:"1783–1842",o:"フランス",b:"『赤と黒』『パルムの僧院』の小説家",born:1783,r:"west"},
  "ショーペンハウアー":{y:"1788–1860",o:"ドイツ",b:"意志と表象の哲学者。厭世思想で知られる",born:1788,r:"west"},
  "キーツ":{y:"1795–1821",o:"イギリス",b:"25歳で没したロマン派の詩人",born:1795,r:"west"},
  "プーシキン":{y:"1799–1837",o:"ロシア",b:"近代ロシア文学の父",born:1799,r:"west"},
  "ユゴー":{y:"1802–1885",o:"フランス",b:"『レ・ミゼラブル』のロマン主義の巨匠",born:1802,r:"west"},
  "デュマ":{y:"1802–1870",o:"フランス",b:"『三銃士』『モンテ・クリスト伯』の作家",born:1802,r:"west"},
  "エマソン":{y:"1803–1882",o:"アメリカ",b:"超越主義の思想家・随筆家",born:1803,r:"west"},
  "アンデルセン":{y:"1805–1875",o:"デンマーク",b:"貧しい靴屋の子から童話の王へ",born:1805,r:"west"},
  "ダーウィン":{y:"1809–1882",o:"イギリス",b:"進化論を確立した博物学者",born:1809,r:"west"},
  "ディケンズ":{y:"1812–1870",o:"イギリス",b:"ヴィクトリア朝を代表する国民作家",born:1812,r:"west"},
  "キルケゴール":{y:"1813–1855",o:"デンマーク",b:"実存主義の先駆けとなった思想家",born:1813,r:"west"},
  "シャーロット・ブロンテ":{y:"1816–1855",o:"イギリス",b:"『ジェイン・エア』の作者。ブロンテ三姉妹の長女",born:1816,r:"west"},
  "ソロー":{y:"1817–1862",o:"アメリカ",b:"ウォールデン湖畔で自給自足を実験した思想家",born:1817,r:"west"},
  "エミリー・ブロンテ":{y:"1818–1848",o:"イギリス",b:"唯一の長編『嵐が丘』を残した",born:1818,r:"west"},
  "メルヴィル":{y:"1819–1891",o:"アメリカ",b:"船乗りの経験から『白鯨』を書いた",born:1819,r:"west"},
  "ホイットマン":{y:"1819–1892",o:"アメリカ",b:"自由詩でアメリカを歌った詩人",born:1819,r:"west"},
  "ジョージ・エリオット":{y:"1819–1880",o:"イギリス",b:"男性名で書いた女性作家。『ミドルマーチ』",born:1819,r:"west"},
  "ボードレール":{y:"1821–1867",o:"フランス",b:"『悪の華』の詩人。近代詩の出発点",born:1821,r:"west"},
  "ドストエフスキー":{y:"1821–1881",o:"ロシア",b:"人間の深淵を描いた小説家。死刑宣告を経験した",born:1821,r:"west"},
  "トルストイ":{y:"1828–1910",o:"ロシア",b:"『戦争と平和』の文豪。晩年は思想家として生きた",born:1828,r:"west"},
  "ディキンソン":{y:"1830–1886",o:"アメリカ",b:"生前ほぼ無名のまま約1800篇の詩を残した",born:1830,r:"west"},
  "ルイス・キャロル":{y:"1832–1898",o:"イギリス",b:"数学者にして『アリス』の作者",born:1832,r:"west"},
  "マーク・トウェイン":{y:"1835–1910",o:"アメリカ",b:"ミシシッピ川を描いたユーモア作家",born:1835,r:"west"},
  "ニーチェ":{y:"1844–1900",o:"ドイツ",b:"「神は死んだ」と告げた哲学者",born:1844,r:"west"},
  "ワイルド":{y:"1854–1900",o:"アイルランド",b:"機知に富む劇作家・小説家",born:1854,r:"west"},
  "タゴール":{y:"1861–1941",o:"インド",b:"アジア初のノーベル文学賞詩人",born:1861,r:"east"},
  "アラン":{y:"1868–1951",o:"フランス",b:"高校教師として書き続けた哲学者。本名エミール・シャルティエ",born:1868,r:"west"},
  "プルースト":{y:"1871–1922",o:"フランス",b:"『失われた時を求めて』に生涯を捧げた",born:1871,r:"west"},
  "リルケ":{y:"1875–1926",o:"オーストリア",b:"孤独と内面を歌った詩人",born:1875,r:"west"},
  "ヘッセ":{y:"1877–1962",o:"ドイツ・スイス",b:"『車輪の下』『デミアン』の作家",born:1877,r:"west"},
  "アインシュタイン":{y:"1879–1955",o:"ドイツ・アメリカ",b:"相対性理論の物理学者",born:1879,r:"west"},
  "ヘレン・ケラー":{y:"1880–1968",o:"アメリカ",b:"視覚と聴覚を失いながら著述家・活動家として生きた",born:1880,r:"west"},
  "ジョイス":{y:"1882–1941",o:"アイルランド",b:"『ユリシーズ』で小説を変えた",born:1882,r:"west"},
  "ウルフ":{y:"1882–1941",o:"イギリス",b:"意識の流れを描いた小説家・批評家",born:1882,r:"west"},
  "カフカ":{y:"1883–1924",o:"プラハ",b:"保険局員として働きながら書いた。生前はほぼ無名",born:1883,r:"west"},
  "ジブラーン":{y:"1883–1931",o:"レバノン・アメリカ",b:"『預言者』の詩人・画家",born:1883,r:"east"},
  "デール・カーネギー":{y:"1888–1955",o:"アメリカ",b:"話し方と人間関係の教育者",born:1888,r:"west"},
  "ヴィトゲンシュタイン":{y:"1889–1951",o:"オーストリア・イギリス",b:"言語の哲学者。庭師や小学校教師も務めた",born:1889,r:"west"},
  "トールキン":{y:"1892–1973",o:"イギリス",b:"言語学者にして『指輪物語』の作者",born:1892,r:"west"},
  "フィッツジェラルド":{y:"1896–1940",o:"アメリカ",b:"ジャズ・エイジを描いた小説家",born:1896,r:"west"},
  "ヘミングウェイ":{y:"1899–1961",o:"アメリカ",b:"簡潔な文体で20世紀文学を変えた",born:1899,r:"west"},
  "ボルヘス":{y:"1899–1986",o:"アルゼンチン",b:"迷宮と図書館の作家。晩年は失明した",born:1899,r:"west"},
  "サン＝テグジュペリ":{y:"1900–1944",o:"フランス",b:"飛行士にして作家。偵察飛行中に消息を絶った",born:1900,r:"west"},
  "スタインベック":{y:"1902–1968",o:"アメリカ",b:"『怒りの葡萄』『エデンの東』の作家",born:1902,r:"west"},
  "オーウェル":{y:"1903–1950",o:"イギリス",b:"全体主義を見つめた作家・ジャーナリスト",born:1903,r:"west"},
  "サルトル":{y:"1905–1980",o:"フランス",b:"実存主義の哲学者・作家。ノーベル賞を辞退した",born:1905,r:"west"},
  "フランクル":{y:"1905–1997",o:"オーストリア",b:"強制収容所を生き延びた精神科医",born:1905,r:"west"},
  "ボーヴォワール":{y:"1908–1986",o:"フランス",b:"『第二の性』の哲学者・作家",born:1908,r:"west"},
  "カミュ":{y:"1913–1960",o:"フランス（アルジェリア生まれ）",b:"不条理を見つめた作家。44歳でノーベル賞",born:1913,r:"west"},
  "ガルシア＝マルケス":{y:"1927–2014",o:"コロンビア",b:"魔術的リアリズムの作家",born:1927,r:"west"},
  "アンネ・フランク":{y:"1929–1945",o:"ドイツ・オランダ",b:"隠れ家で日記を書き続けた少女",born:1929,r:"west"}
};

// 引用: a=著者, w=出典, t=本文(日本語), x=原文(あれば), m=図版 (book/quill/lamp/hourglass/laurel/candle/moon)
window.SHIORI_QUOTES = [
  // ── 日本 ──
  {a:"山上憶良",w:"『万葉集』巻五",t:"銀も金も玉も何せむに 勝れる宝 *子*に及かめやも",e:"Silver, gold, and jewels — what are they worth? No treasure surpasses a child.",m:"moon"},
  {a:"紀貫之",w:"『古今和歌集』仮名序",t:"やまとうたは、人の*心*を種として、よろづの言の葉とぞなれりける。",e:"Japanese poetry has the human heart as its seed, and grows into countless leaves of words.",m:"quill"},
  {a:"小野小町",w:"『古今和歌集』",t:"*花の色*は移りにけりな いたづらに わが身世にふる ながめせしまに",e:"The color of the flowers has faded away, while I idly gazed at the long rains, my life passing in this world.",m:"hourglass"},
  {a:"清少納言",w:"『枕草子』",t:"春は*あけぼの*。やうやう白くなりゆく山ぎは、少しあかりて、紫だちたる雲の細くたなびきたる。",e:"In spring, the dawn. The rim of the mountains slowly whitens, brightening a little, and slender clouds tinged with purple trail across it.",m:"moon"},
  {a:"紫式部",w:"『源氏物語』桐壺",t:"いづれの御時にか、女御、更衣あまたさぶらひたまひける中に、いとやむごとなき際にはあらぬが、すぐれて*時めき*たまふありけり。",e:"In a certain reign, among the many consorts and ladies who served the Emperor, there was one who, though not of the highest rank, was favored far above all the others.",m:"book"},
  {a:"西行",w:"『山家集』",t:"願はくは *花*の下にて春死なむ その如月の望月のころ",e:"Let me die in spring, beneath the blossoms, around the full moon of the second month.",m:"moon"},
  {a:"鴨長明",w:"『方丈記』",t:"ゆく河の流れは絶えずして、しかももとの水にあらず。よどみに浮かぶ*うたかた*は、かつ消えかつ結びて、久しくとどまりたるためしなし。",e:"The flowing river never ceases, yet its water is never the same. The foam that floats on the pools, now vanishing, now forming, never stays for long.",m:"hourglass"},
  {a:"鴨長明",w:"『方丈記』",t:"知らず、生まれ死ぬる人、いづかたより来たりて、いづかたへか*去る*。",e:"I do not know: those who are born and those who die, whence do they come, and whither do they go?",m:"hourglass"},
  {a:"親鸞",w:"『歎異抄』（唯円編）",t:"善人なほもて往生をとぐ、いはんや*悪人*をや。",e:"Even a good person attains birth in the Pure Land; how much more so an evil person.",m:"candle"},
  {a:"平家物語（作者未詳）",w:"『平家物語』",t:"祇園精舎の鐘の声、*諸行無常*の響きあり。沙羅双樹の花の色、盛者必衰の理をあらはす。",e:"The bell of the Gion temple tolls the impermanence of all things. The color of the sala flowers reveals the truth that the prosperous must decline.",m:"hourglass"},
  {a:"道元",w:"『正法眼蔵』現成公案",t:"仏道をならふといふは、*自己*をならふなり。自己をならふといふは、自己をわするるなり。",e:"To study the Buddha Way is to study the self. To study the self is to forget the self.",m:"lamp"},
  {a:"吉田兼好",w:"『徒然草』序段",t:"つれづれなるままに、日暮らし、硯にむかひて、心にうつりゆく*よしなし事*を、そこはかとなく書きつくれば、あやしうこそものぐるほしけれ。",e:"With nothing better to do, I sit all day before the inkstone, jotting down whatever trifles drift through my mind, and a strange madness comes over me.",m:"quill"},
  {a:"吉田兼好",w:"『徒然草』第九十二段",t:"初心の人、*二つの矢*を持つことなかれ。後の矢を頼みて、始めの矢になほざりの心あり。",e:"A beginner should not hold two arrows. Counting on the second, he grows careless with the first.",m:"laurel"},
  {a:"吉田兼好",w:"『徒然草』第百三十七段",t:"花は*盛り*に、月は隈なきをのみ、見るものかは。",e:"Are blossoms to be seen only in full bloom, and the moon only when unclouded?",m:"moon"},
  {a:"吉田兼好",w:"『徒然草』第百五十段",t:"天下のものの*上手*といへども、始めは不堪の聞こえもあり、無下の瑕瑾もありき。",e:"Even the greatest masters in the land were once called clumsy, and bore glaring faults.",m:"laurel"},
  {a:"世阿弥",w:"『花鏡』",t:"*初心*忘るべからず。",e:"Never forget the beginner's heart.",m:"laurel"},
  {a:"世阿弥",w:"『風姿花伝』",t:"秘すれば*花*なり。秘せずは花なるべからず。",e:"What is hidden is the flower. What is not hidden cannot be the flower.",m:"moon"},
  {a:"千利休",w:"『利休百首』（伝）",t:"稽古とは *一*より習ひ十を知り 十よりかへる もとのその一",e:"Practice is this: learn from one to ten, then return from ten to the first one.",m:"laurel"},
  {a:"宮本武蔵",w:"『五輪書』水の巻",t:"千日の稽古を鍛とし、万日の稽古を*錬*とす。",e:"A thousand days of practice to forge; ten thousand days of practice to refine.",m:"laurel"},
  {a:"山本常朝",w:"『葉隠』",t:"武士道といふは、*死ぬ事*と見付けたり。",e:"The Way of the warrior, I have found, is death.",m:"hourglass"},
  {a:"貝原益軒",w:"『養生訓』",t:"養生の術は、まづ*心気*を養ふべし。",e:"The art of nourishing life begins with nourishing the heart and spirit.",m:"lamp"},
  {a:"松尾芭蕉",w:"『おくのほそ道』",t:"月日は*百代の過客*にして、行きかふ年もまた旅人なり。",e:"The months and days are travelers of eternity; the years that come and go are travelers too.",m:"hourglass"},
  {a:"松尾芭蕉",w:"『おくのほそ道』",t:"夏草や 兵どもが *夢*の跡",e:"Summer grasses: all that remains of warriors' dreams.",m:"moon"},
  {a:"松尾芭蕉",w:"『蛙合』",t:"古池や 蛙飛びこむ *水の音*",e:"An old pond. A frog leaps in. The sound of water.",m:"moon"},
  {a:"上杉鷹山",w:"伝・家臣への歌",t:"*為せば成る* 為さねば成らぬ何事も 成らぬは人の為さぬなりけり",e:"If you act, it will be done; if you do not, it will not. Whatever fails, fails because no one acted.",m:"laurel"},
  {a:"良寛",w:"山田杜皐宛の手紙",t:"災難に逢う時節には災難に逢うがよく候。死ぬ時節には死ぬがよく候。是はこれ災難をのがるる*妙法*にて候。",e:"When disaster comes, it is well to meet disaster. When it is time to die, it is well to die. This is the secret art of escaping disaster.",m:"candle"},
  {a:"小林一茶",w:"『おらが春』",t:"目出度さも *ちう位*也 おらが春",e:"New Year's joy: a middling sort of joy, this spring of mine.",m:"moon"},
  {a:"佐藤一斎",w:"『言志晩録』",t:"少にして学べば、則ち壮にして為すこと有り。壮にして学べば、則ち老いて衰へず。老いて学べば、則ち死して*朽ちず*。",e:"Learn in youth, and you will achieve in your prime. Learn in your prime, and you will not decline in old age. Learn in old age, and you will not decay in death.",m:"book"},
  {a:"二宮尊徳",w:"『二宮翁夜話』",t:"*小*を積みて大と為す。",e:"Accumulate the small to make the great.",m:"laurel"},
  {a:"西郷隆盛",w:"『南洲翁遺訓』",t:"命もいらず、名もいらず、官位も金もいらぬ人は、*始末に困る*もの也。",e:"One who wants neither life, nor fame, nor rank, nor money is a hard person to deal with.",m:"lamp"},
  {a:"吉田松陰",w:"「士規七則」",t:"*志*を立てて以て万事の源と為す。",e:"Set your resolve, and make it the source of all things.",m:"laurel"},
  {a:"福澤諭吉",w:"『学問のすすめ』初編",t:"*天*は人の上に人を造らず、人の下に人を造らずと言えり。",e:"It is said that Heaven creates no one above another, and no one below another.",m:"book"},
  {a:"福澤諭吉",w:"『学問のすすめ』三編",t:"一身独立して*一国独立*す。",e:"When each person is independent, the nation is independent.",m:"laurel"},
  {a:"渋沢栄一",w:"『論語と算盤』",t:"正しい道理の富でなければ、その富は完全に*永続*することができぬ。",e:"Unless wealth is gained by right principle, that wealth can never truly last.",m:"lamp"},
  {a:"内村鑑三",w:"『後世への最大遺物』",t:"後世への最大遺物とは何であるか。私は、それは*勇ましい高尚なる生涯*であると思います。",e:"What is the greatest legacy we can leave to posterity? I believe it is a brave and noble life.",m:"candle"},
  {a:"森鷗外",w:"『高瀬舟』",t:"人は身に病があると、この病がなかったらと思う。蓄えがあっても、またその蓄えがもっと多かったらと思う。人はどこまで行って*踏み止まる*ことができるものやら分からない。",e:"When we are ill, we wish we were not. Even with savings, we wish we had more. Thinking on and on like this, there is no telling where a person could ever stop.",m:"lamp"},
  {a:"新渡戸稲造",w:"『武士道』",t:"武士道は、その象徴である*桜*と同じく、日本の土壌に固有の花である。",x:"Chivalry is a flower no less indigenous to the soil of Japan than its emblem, the cherry blossom.",m:"moon"},
  {a:"岡倉天心",w:"『茶の本』",t:"茶道とは、日常の俗事のただ中にある*美*しきものを崇める、ひとつの儀式である。",x:"Teaism is a cult founded on the adoration of the beautiful among the sordid facts of everyday existence.",m:"lamp"},
  {a:"夏目漱石",w:"『吾輩は猫である』",t:"吾輩は*猫*である。名前はまだ無い。",e:"I am a cat. As yet I have no name.",m:"book"},
  {a:"夏目漱石",w:"『草枕』",t:"智に働けば角が立つ。情に棹させば流される。意地を通せば窮屈だ。とかくに人の世は*住みにくい*。",e:"Use your intellect and you grow harsh. Give in to feeling and you are swept away. Insist on your will and you are hemmed in. Whichever way, this world is hard to live in.",m:"lamp"},
  {a:"夏目漱石",w:"『三四郎』",t:"日本より*頭の中*のほうが広いでしょう。とらわれちゃだめだ。",e:"The inside of your head is wider than Japan. Don't let yourself be trapped.",m:"book"},
  {a:"夏目漱石",w:"『こころ』",t:"精神的に*向上心*のないものは、馬鹿だ。",e:"Anyone with no wish to improve in spirit is a fool.",m:"lamp"},
  {a:"夏目漱石",w:"『私の個人主義』",t:"私はこの*自己本位*という言葉を自分の手に握ってから大変強くなりました。",e:"Once I grasped the phrase 'self-centered' in my own hands, I grew very strong.",m:"quill"},
  {a:"夏目漱石",w:"『坊っちゃん』",t:"親譲りの*無鉄砲*で小供の時から損ばかりしている。",e:"Reckless by nature, I have been losing out ever since I was a child.",m:"book"},
  {a:"正岡子規",w:"『病牀六尺』",t:"悟りといふ事は如何なる場合にも平気で死ぬる事かと思つて居たのは間違で、悟りといふ事は如何なる場合にも*平気で生きて居る*事であつた。",e:"I had thought enlightenment meant being able to die calmly in any circumstance. I was wrong. Enlightenment means being able to live calmly in any circumstance.",m:"candle"},
  {a:"西田幾多郎",w:"『善の研究』",t:"善とは一言にていえば*人格*の実現である。",e:"In a word, the good is the realization of personality.",m:"lamp"},
  {a:"島崎藤村",w:"『若菜集』「初恋」",t:"まだあげ初めし前髪の *林檎*のもとに見えしとき",e:"When first I saw you, your hair just put up, beneath the apple tree.",m:"moon"},
  {a:"与謝野晶子",w:"『みだれ髪』",t:"やは肌のあつき血汐にふれも見で さびしからずや *道*を説く君",e:"You who preach the Way, never touching the hot blood beneath this soft skin: are you not lonely?",m:"quill"},
  {a:"有島武郎",w:"『小さき者へ』",t:"前途は遠い。そして暗い。然し恐れてはならぬ。*恐れない者*の前に道は開ける。",e:"The road ahead is long, and dark. But do not fear. Before those who do not fear, the road opens.",m:"candle"},
  {a:"種田山頭火",w:"『草木塔』",t:"分け入っても分け入っても*青い山*",e:"Pushing on, pushing on, still the blue mountains.",m:"moon"},
  {a:"高村光太郎",w:"『道程』",t:"僕の前に道はない 僕の後ろに*道*は出来る",e:"There is no road before me. Behind me, a road is made.",m:"laurel"},
  {a:"志賀直哉",w:"『城の崎にて』",t:"生きている事と死んでしまっている事と、それは*両極*ではなかった。それ程に差はないような気がした。",e:"Being alive and being dead were not opposite poles. It seemed there was not much difference between them.",m:"hourglass"},
  {a:"武者小路実篤",w:"色紙の言葉",t:"この道より我を生かす道なし *この道*を歩く",e:"There is no road but this one to make me live. I walk this road.",m:"laurel"},
  {a:"尾崎放哉",w:"『大空』",t:"咳をしても*一人*",e:"Even coughing, alone.",m:"candle"},
  {a:"石川啄木",w:"『一握の砂』",t:"はたらけど はたらけど猶わが生活楽にならざり ぢつと*手*を見る",e:"I work and I work, and still my life is no easier. I stare at my hands.",m:"candle"},
  {a:"石川啄木",w:"『一握の砂』",t:"東海の小島の磯の白砂に われ泣きぬれて *蟹*とたはむる",e:"On the white sand of a small island's shore in the eastern sea, wet with tears, I play with a crab.",m:"moon"},
  {a:"谷崎潤一郎",w:"『陰翳礼讃』",t:"美は物体にあるのではなく、物体と物体との作り出す*陰翳*のあや、明暗にあると考える。",e:"Beauty lies not in objects themselves, but in the patterns of shadow, the light and dark, that objects create between them.",m:"lamp"},
  {a:"芥川龍之介",w:"『侏儒の言葉』",t:"人生は一箱の*マッチ*に似ている。重大に扱うのは莫迦莫迦しい。重大に扱わなければ危険である。",e:"Life is like a box of matches. To treat it seriously is absurd. To treat it lightly is dangerous.",m:"candle"},
  {a:"芥川龍之介",w:"『羅生門』",t:"下人の*行方*は、誰も知らない。",e:"What became of the servant, no one knows.",m:"book"},
  {a:"松下幸之助",w:"『道をひらく』",t:"自分には自分に与えられた道がある。ほかの人には歩めない。自分だけしか歩めない、二度と歩めぬ*かけがえのない*この道。",e:"I have a road given to me alone. No one else can walk it; only I can, and only once. This irreplaceable road.",m:"laurel"},
  {a:"宮沢賢治",w:"『農民芸術概論綱要』",t:"世界がぜんたい*幸福*にならないうちは個人の幸福はあり得ない。",e:"Until the whole world is happy, there can be no happiness for the individual.",m:"candle"},
  {a:"宮沢賢治",w:"『銀河鉄道の夜』",t:"けれども*ほんとうのさいわい*は一体何だろう。",e:"But what, after all, is true happiness?",m:"moon"},
  {a:"宮沢賢治",w:"『春と修羅』序",t:"わたくしといふ現象は 仮定された有機交流電燈の ひとつの*青い照明*です",e:"The phenomenon called I is a single blue illumination of a hypothesized organic alternating-current lamp.",m:"lamp"},
  {a:"宮沢賢治",w:"「雨ニモマケズ」",t:"雨ニモマケズ 風ニモマケズ 雪ニモ夏ノ暑サニモマケヌ *丈夫ナカラダ*ヲモチ",e:"Unbeaten by rain, unbeaten by wind, unbeaten by snow or summer heat, with a strong body.",m:"laurel"},
  {a:"三木清",w:"『人生論ノート』",t:"幸福は*人格*である。",e:"Happiness is character.",m:"lamp"},
  {a:"三木清",w:"『人生論ノート』",t:"孤独は山になく、*街*にある。一人の人間にあるのでなく、大勢の人間の「間」にあるのである。",e:"Solitude is not in the mountains but in the streets; not in one person, but in the space between many.",m:"candle"},
  {a:"井伏鱒二",w:"『厄除け詩集』（于武陵「勧酒」訳）",t:"ハナニアラシノタトヘモアルゾ *サヨナラ*ダケガ人生ダ",e:"Storms scatter the blossoms, as they say. Farewell alone is life.",m:"moon"},
  {a:"川端康成",w:"『雪国』",t:"国境の長いトンネルを抜けると*雪国*であった。夜の底が白くなった。",e:"The train came out of the long tunnel into the snow country. The bottom of the night turned white.",m:"book"},
  {a:"梶井基次郎",w:"『檸檬』",t:"えたいの知れない*不吉な塊*が私の心を始終圧えつけていた。",e:"An indefinable, ominous lump pressed down on my heart without cease.",m:"lamp"},
  {a:"堀辰雄",w:"『風立ちぬ』",t:"風立ちぬ、いざ*生きめやも*。",x:"Le vent se lève, il faut tenter de vivre. — Paul Valéry",e:"The wind is rising. We must try to live.",m:"moon"},
  {a:"坂口安吾",w:"『堕落論』",t:"生きよ*堕ちよ*、その正当な手順の外に、真に人間を救い得る便利な近道が有りようもない。",e:"Live, and fall. Outside that rightful course, there is no convenient shortcut that can truly save a human being.",m:"candle"},
  {a:"中原中也",w:"『山羊の歌』「汚れつちまつた悲しみに」",t:"汚れつちまつた*悲しみ*に 今日も小雪の降りかかる",e:"On my sorrow, soiled and stained, today again a light snow falls.",m:"moon"},
  {a:"太宰治",w:"『人間失格』",t:"恥の多い*生涯*を送って来ました。",e:"Mine has been a life of much shame.",m:"book"},
  {a:"太宰治",w:"『走れメロス』",t:"メロスは*激怒*した。必ず、かの邪智暴虐の王を除かなければならぬと決意した。",e:"Melos was furious. He resolved that the wicked and tyrannical king must be removed.",m:"laurel"},
  {a:"太宰治",w:"『斜陽』",t:"人間は*恋と革命*のために生れて来たのだ。",e:"Human beings were born for love and revolution.",m:"candle"},
  {a:"中島敦",w:"『山月記』",t:"己の*珠*に非ざることを惧れるが故に、敢て刻苦して磨こうともせず、又、己の珠なるべきを半ば信ずるが故に、碌々として瓦に伍することも出来なかった。",e:"Fearing I was no jewel, I would not labor to polish myself; half believing I was a jewel, I could not settle among the common tiles.",m:"lamp"},
  {a:"神谷美恵子",w:"『生きがいについて』",t:"人間がもっとも*生きがい*を感じるのは、自分がしたいと思うことと義務とが一致したときだと思われる。",e:"People feel most alive, I believe, when what they wish to do and what they must do coincide.",m:"candle"},
  // ── 東洋 ──
  {a:"孔子",w:"『論語』学而",t:"学びて時にこれを習う、また*説ばしから*ずや。朋あり遠方より来たる、また楽しからずや。",x:"學而時習之、不亦說乎。有朋自遠方來、不亦樂乎。",e:"To learn and practice in due time, is this not a pleasure? To have friends come from afar, is this not a joy?",m:"book"},
  {a:"孔子",w:"『論語』為政",t:"学びて思わざれば則ち罔し、思いて学ばざれば則ち*殆*し。",x:"學而不思則罔、思而不學則殆。",e:"Learning without thought is labor lost; thought without learning is perilous.",m:"book"},
  {a:"孔子",w:"『論語』為政",t:"故きを温めて新しきを知れば、以て*師*たるべし。",x:"溫故而知新、可以為師矣。",e:"Review the old and learn the new, and you may become a teacher.",m:"lamp"},
  {a:"孔子",w:"『論語』衛霊公",t:"己の欲せざる所は、人に*施す*こと勿れ。",x:"己所不欲、勿施於人。",e:"Do not impose on others what you do not wish for yourself.",m:"lamp"},
  {a:"老子",w:"『老子』第八章",t:"上善は*水*の若し。水は善く万物を利して争わず。",x:"上善若水。水善利萬物而不爭。",e:"The highest good is like water. Water benefits all things and does not contend.",m:"moon"},
  {a:"老子",w:"『老子』第三十三章",t:"足るを知る者は*富む*。",x:"知足者富。",e:"One who knows contentment is rich.",m:"lamp"},
  {a:"老子",w:"『老子』第六十四章",t:"千里の行も*足下*より始まる。",x:"千里之行、始於足下。",e:"A journey of a thousand miles begins beneath one's feet.",m:"laurel"},
  {a:"孫子",w:"『孫子』謀攻篇",t:"彼を知り己を知れば、*百戦*して殆うからず。",x:"知彼知己、百戰不殆。",e:"Know the enemy and know yourself, and in a hundred battles you will never be in peril.",m:"laurel"},
  {a:"孟子",w:"『孟子』告子下",t:"天の将に大任を是の人に降さんとするや、必ず先ず其の*心志*を苦しめる。",x:"天將降大任於是人也、必先苦其心志。",e:"When Heaven is about to place a great responsibility on a person, it first tests their heart and will with suffering.",m:"laurel"},
  {a:"荘子",w:"『荘子』人間世",t:"人皆有用の用を知りて、*無用の用*を知る莫きなり。",x:"人皆知有用之用、而莫知無用之用也。",e:"Everyone knows the usefulness of the useful, but no one knows the usefulness of the useless.",m:"lamp"},
  {a:"荘子",w:"『荘子』斉物論",t:"知らず、周の夢に*胡蝶*と為れるか、胡蝶の夢に周と為れるかを。",x:"不知周之夢為胡蝶與、胡蝶之夢為周與。",e:"I do not know whether Zhou dreamed he was a butterfly, or a butterfly dreamed it was Zhou.",m:"moon"},
  {a:"ブッダ",w:"『ダンマパダ』第一偈",t:"ものごとは*心*にもとづき、心を主とし、心によってつくり出される。",x:"Manopubbaṅgamā dhammā manoseṭṭhā manomayā.",e:"All things are preceded by the mind, led by the mind, made by the mind.",m:"lamp"},
  {a:"ブッダ",w:"『スッタニパータ』",t:"犀の角のように、ただ*独り*歩め。",x:"Eko care khaggavisāṇakappo.",e:"Wander alone, like the horn of a rhinoceros.",m:"candle"},
  {a:"司馬遷",w:"『史記』李将軍列伝",t:"*桃李*もの言わざれども、下自ずから蹊を成す。",x:"桃李不言、下自成蹊。",e:"The peach and the plum do not speak, yet a path forms beneath them.",m:"laurel"},
  {a:"陶淵明",w:"「飲酒」其五",t:"菊を采る東籬の下、悠然として*南山*を見る。",x:"采菊東籬下、悠然見南山。",e:"Picking chrysanthemums by the eastern hedge, I gaze serenely at the southern mountain.",m:"moon"},
  {a:"杜甫",w:"「春望」",t:"国破れて*山河*あり、城春にして草木深し。",x:"國破山河在、城春草木深。",e:"The nation is broken, yet mountains and rivers remain; spring in the city, and grass and trees grow deep.",m:"moon"},
  {a:"タゴール",w:"『迷い鳥』",t:"すべての誤りに扉を閉ざすなら、*真理*も締め出されてしまう。",x:"If you shut your door to all errors truth will be shut out.",m:"lamp"},
  {a:"ジブラーン",w:"『預言者』",t:"あなたの*子ども*は、あなたの子どもではない。生命そのものが自らを求めて生んだ、息子であり娘である。",x:"Your children are not your children. They are the sons and daughters of Life's longing for itself.",m:"candle"},

  // ── 西洋（古代） ──
  {a:"アイスキュロス",w:"『アガメムノン』",t:"*苦しみ*によって学ぶ。",x:"πάθει μάθος",e:"Through suffering, learning.",m:"lamp"},
  {a:"ヘラクレイトス",w:"断片12（ディールス＝クランツ）",t:"同じ*川*に足を踏み入れる者にも、次々と別の水が流れ寄せる。",x:"ποταμοῖσι τοῖσιν αὐτοῖσιν ἐμβαίνουσιν ἕτερα καὶ ἕτερα ὕδατα ἐπιρρεῖ.",e:"Upon those who step into the same rivers, ever different waters flow.",m:"hourglass"},
  {a:"ソポクレス",w:"『アンティゴネー』",t:"不思議なものは数あれど、*人間*ほど不思議なものはない。",x:"πολλὰ τὰ δεινὰ κοὐδὲν ἀνθρώπου δεινότερον πέλει.",e:"Wonders are many, and none is more wonderful than man.",m:"lamp"},
  {a:"ソクラテス",w:"プラトン『ソクラテスの弁明』",t:"吟味されない人生は、人間にとって*生きるに値しない*。",x:"ὁ δὲ ἀνεξέταστος βίος οὐ βιωτὸς ἀνθρώπῳ.",e:"The unexamined life is not worth living.",m:"lamp"},
  {a:"アリストテレス",w:"『ニコマコス倫理学』",t:"正しいことを*行う*ことによって、われわれは正しい人になる。",x:"τὰ μὲν δίκαια πράττοντες δίκαιοι γινόμεθα.",e:"By doing just acts we become just.",m:"laurel"},
  {a:"エピクロス",w:"「メノイケウス宛の手紙」",t:"*死*は、われわれにとって何ものでもない。",x:"ὁ θάνατος οὐδὲν πρὸς ἡμᾶς.",e:"Death is nothing to us.",m:"hourglass"},
  {a:"ウェルギリウス",w:"『アエネーイス』第一巻",t:"いつの日か、これらのことを思い出すのも*喜び*となるだろう。",x:"Forsan et haec olim meminisse iuvabit.",e:"Perhaps one day it will be a joy to remember even these things.",m:"candle"},
  {a:"ホラティウス",w:"『歌集』第一巻十一歌",t:"*今日という日*を摘め。明日をできるだけ信じずに。",x:"Carpe diem, quam minimum credula postero.",e:"Seize the day, trusting as little as possible in tomorrow.",m:"hourglass"},
  {a:"セネカ",w:"『人生の短さについて』",t:"われわれは短い時間を持っているのではない。その多くを*浪費*しているのだ。",x:"Non exiguum temporis habemus, sed multum perdidimus.",e:"It is not that we have a short time to live, but that we waste much of it.",m:"hourglass"},
  {a:"セネカ",w:"『倫理書簡集』第76書簡",t:"生きているかぎり、*生き方*を学び続けなければならない。",x:"Tamdiu discendum est quemadmodum vivas, quamdiu vivas.",e:"As long as you live, keep learning how to live.",m:"book"},
  {a:"エピクテトス",w:"『提要（エンケイリディオン）』",t:"物事のうちには、われわれの*力の及ぶ*ものと、及ばないものとがある。",x:"Τῶν ὄντων τὰ μέν ἐστιν ἐφ' ἡμῖν, τὰ δὲ οὐκ ἐφ' ἡμῖν.",e:"Some things are within our power, and some are not.",m:"lamp"},
  {a:"マルクス・アウレリウス",w:"『自省録』第五巻",t:"明け方、起きるのがつらいときは、こう思え。私は*人間の仕事*をするために起きるのだ、と。",x:"Ὄρθρου ὅταν δυσόκνως ἐξεγείρῃ, πρόχειρον ἔστω ὅτι ἐπὶ ἀνθρώπου ἔργον ἐγείρομαι.",e:"At dawn, when you have trouble getting out of bed, tell yourself: I am rising to do the work of a human being.",m:"lamp"},
  {a:"マルクス・アウレリウス",w:"『自省録』第四巻",t:"自分自身の*魂*の内ほど、静かで煩いのない隠れ家はどこにもない。",x:"οὐδαμοῦ γὰρ οὔτε ἡσυχιώτερον οὔτε ἀπραγμονέστερον ἄνθρωπος ἀναχωρεῖ ἢ εἰς τὴν ἑαυτοῦ ψυχήν.",e:"Nowhere can a person find a quieter or more untroubled retreat than in their own soul.",m:"candle"},
  {a:"アウグスティヌス",w:"『告白』第一巻",t:"私たちの*心*は、あなたのうちに憩うまで安らぐことがありません。",x:"Inquietum est cor nostrum, donec requiescat in te.",e:"Our heart is restless until it rests in You.",m:"candle"},
  // ── 西洋（中世〜近代） ──
  {a:"ダンテ",w:"『神曲』地獄篇第一歌",t:"人生の道の半ばで、私は*暗い森*の中にいた。",x:"Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura.",e:"Midway upon the journey of our life, I found myself within a dark wood.",m:"candle"},
  {a:"マキャヴェリ",w:"『君主論』第十七章",t:"愛されるよりも*恐れられる*ほうが、はるかに安全である。",x:"È molto più sicuro essere temuto che amato.",e:"It is much safer to be feared than loved.",m:"lamp"},
  {a:"モンテーニュ",w:"『エセー』第二巻十二章",t:"私は*何を知っている*のか。",x:"Que sçay-je ?",e:"What do I know?",m:"lamp"},
  {a:"モンテーニュ",w:"『エセー』第三巻十三章",t:"われわれの偉大で輝かしい*傑作*とは、ふさわしく生きることである。",x:"Nostre grand et glorieux chef-d'œuvre, c'est vivre à propos.",e:"Our great and glorious masterpiece is to live appropriately.",m:"laurel"},
  {a:"セルバンテス",w:"『ドン・キホーテ』後編第五十八章",t:"*自由*とはな、サンチョ、天が人間に授けた最も貴い賜物のひとつなのだ。",x:"La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos.",e:"Freedom, Sancho, is one of the most precious gifts that heaven has bestowed upon men.",m:"laurel"},
  {a:"フランシス・ベーコン",w:"『随筆集』「学問について」",t:"*読書*は充実した人間を、会話は機敏な人間を、書くことは正確な人間をつくる。",x:"Reading maketh a full man; conference a ready man; and writing an exact man.",m:"book"},
  {a:"シェイクスピア",w:"『ハムレット』第三幕第一場",t:"生きるべきか、*死ぬ*べきか、それが問題だ。",x:"To be, or not to be, that is the question.",m:"lamp"},
  {a:"シェイクスピア",w:"『お気に召すまま』第二幕第七場",t:"この世はすべて*舞台*、男も女もみな役者にすぎない。",x:"All the world's a stage, and all the men and women merely players.",m:"moon"},
  {a:"シェイクスピア",w:"『テンペスト』第四幕第一場",t:"われわれは*夢*と同じ材料でできている。そのささやかな一生は、眠りに包まれている。",x:"We are such stuff as dreams are made on; and our little life is rounded with a sleep.",m:"moon"},
  {a:"ジョン・ダン",w:"『不意に発生する事態に関する瞑想』第十七",t:"何人も*孤島*ではない。",x:"No man is an island, entire of itself.",m:"candle"},
  {a:"デカルト",w:"『方法序説』第四部",t:"我思う、ゆえに*我あり*。",x:"Je pense, donc je suis.",e:"I think, therefore I am.",m:"lamp"},
  {a:"ミルトン",w:"『失楽園』第一巻",t:"心はそれ自身の場所であり、それ自身の中で地獄を*天国*に、天国を地獄に変えることができる。",x:"The mind is its own place, and in itself can make a Heav'n of Hell, a Hell of Heav'n.",m:"lamp"},
  {a:"ラ・ロシュフコー",w:"『箴言集』26",t:"*太陽*も死も、じっと見つめることはできない。",x:"Le soleil ni la mort ne se peuvent regarder fixement.",e:"Neither the sun nor death can be looked at steadily.",m:"hourglass"},
  {a:"パスカル",w:"『パンセ』",t:"人間はひとくきの*葦*にすぎない。自然の中で最も弱いものである。だが、それは考える葦である。",x:"L'homme n'est qu'un roseau, le plus faible de la nature ; mais c'est un roseau pensant.",e:"Man is but a reed, the weakest in nature; but he is a thinking reed.",m:"lamp"},
  {a:"パスカル",w:"『パンセ』",t:"人間の不幸はすべて、たったひとつのこと、*部屋*にじっと休んでいられないことから来る。",x:"Tout le malheur des hommes vient d'une seule chose, qui est de ne savoir pas demeurer en repos, dans une chambre.",e:"All of humanity's misfortune comes from one thing: not knowing how to sit quietly in a room.",m:"candle"},
  {a:"スピノザ",w:"『エチカ』第五部（結び）",t:"すべて*高貴*なものは、稀であるとともに困難である。",x:"Sed omnia praeclara tam difficilia, quam rara sunt.",e:"All things excellent are as difficult as they are rare.",m:"laurel"},
  {a:"ニュートン",w:"ロバート・フック宛の手紙（1675年）",t:"私がより遠くを見たとすれば、それは*巨人*の肩の上に立っていたからだ。",x:"If I have seen further it is by standing on the shoulders of Giants.",m:"lamp"},
  {a:"ヴォルテール",w:"『カンディード』",t:"しかし、われわれの*庭*を耕さねばなりません。",x:"Il faut cultiver notre jardin.",e:"But we must cultivate our garden.",m:"laurel"},
  {a:"ルソー",w:"『社会契約論』第一篇第一章",t:"人間は*自由*なものとして生まれた。しかし、いたるところで鎖につながれている。",x:"L'homme est né libre, et partout il est dans les fers.",e:"Man is born free, and everywhere he is in chains.",m:"lamp"},
  {a:"カント",w:"『実践理性批判』結語",t:"わが上なる*星空*と、わが内なる道徳法則。",x:"Der bestirnte Himmel über mir und das moralische Gesetz in mir.",e:"The starry heavens above me and the moral law within me.",m:"moon"},
  {a:"ゲーテ",w:"『ファウスト』天上の序曲",t:"人間は*努力*するかぎり、迷うものだ。",x:"Es irrt der Mensch, solang er strebt.",e:"Man errs as long as he strives.",m:"laurel"},
  {a:"ゲーテ",w:"『ファウスト』第一部",t:"時よ*止まれ*、おまえはいかにも美しい。",x:"Verweile doch! du bist so schön!",e:"Stay a while! You are so beautiful!",m:"hourglass"},
  {a:"ブレイク",w:"「無垢の予兆」",t:"一粒の*砂*に世界を見、一輪の野の花に天国を見る。",x:"To see a World in a Grain of Sand and a Heaven in a Wild Flower.",m:"moon"},
  {a:"オースティン",w:"『高慢と偏見』第一章",t:"財産のある独身男性なら妻を欲しがっているに違いない。これは世間一般に認められた*真理*である。",x:"It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",m:"book"},
  {a:"スタンダール",w:"『赤と黒』",t:"小説とは、大きな道に沿って持ち歩かれる*鏡*である。",x:"Un roman est un miroir qui se promène sur une grande route.",e:"A novel is a mirror carried along a high road.",m:"book"},
  {a:"ショーペンハウアー",w:"『幸福について（処世術箴言）』",t:"われわれは自分の持っているものをめったに考えず、いつも*欠けているもの*ばかりを考える。",x:"Wir denken selten an das, was wir haben, aber immer an das, was uns fehlt.",e:"We seldom think of what we have, but always of what we lack.",m:"lamp"},
  {a:"キーツ",w:"「ギリシアの壺に寄せるオード」",t:"*美*は真なり、真は美なり。",x:"Beauty is truth, truth beauty.",m:"moon"},
  {a:"プーシキン",w:"「もし人生に欺かれたら」",t:"もし人生があなたを欺いても、悲しまず、怒らず。憂鬱な日には心静かに。*楽しい日*がきっと来ると信じて。",x:"Если жизнь тебя обманет, не печалься, не сердись! В день уныния смирись: день веселья, верь, настанет.",e:"If life deceives you, do not grieve, do not be angry. On the day of sorrow, be still; the day of joy, believe, will come.",m:"candle"},
  {a:"ユゴー",w:"『レ・ミゼラブル』第一部第五編",t:"*悪い草*も、悪い人間もない。あるのは、悪い耕し手だけだ。",x:"Il n'y a ni mauvaises herbes ni mauvais hommes. Il n'y a que de mauvais cultivateurs.",e:"There are no bad plants or bad men. There are only bad cultivators.",m:"laurel"},
  {a:"デュマ",w:"『三銃士』",t:"一人はみんなのために、*みんな*は一人のために。",x:"Tous pour un, un pour tous.",e:"All for one, one for all.",m:"laurel"},
  {a:"エマソン",w:"『自己信頼』",t:"*自分自身*を信じよ。すべての心はその鉄の弦に震える。",x:"Trust thyself: every heart vibrates to that iron string.",m:"laurel"},
  {a:"アンデルセン",w:"『みにくいアヒルの子』",t:"アヒルの庭に生まれたって、*白鳥*の卵からかえったのなら、なんでもないのだ。",x:"Det gør ikke noget at være født i andegården, når man kun har ligget i et svaneæg!",e:"It does not matter that one was born in a duckyard, if one has lain in a swan's egg.",m:"moon"},
  {a:"ダーウィン",w:"『種の起源』結び",t:"この生命観には*壮大さ*がある。",x:"There is grandeur in this view of life.",m:"lamp"},
  {a:"ディケンズ",w:"『二都物語』第一章",t:"それは最良の時代であり、*最悪*の時代であった。",x:"It was the best of times, it was the worst of times.",m:"hourglass"},
  {a:"キルケゴール",w:"『日記』1843年",t:"人生は*後ろ向き*にしか理解できない。しかし、前向きにしか生きられない。",x:"Livet forstaaes baglænds, men maa leves forlænds.",e:"Life can only be understood backwards; but it must be lived forwards.",m:"hourglass"},
  {a:"シャーロット・ブロンテ",w:"『ジェイン・エア』第二十三章",t:"私は*鳥*ではない。どんな網も私を捕らえはしない。私は自由な意志を持つ、自由な人間です。",x:"I am no bird; and no net ensnares me: I am a free human being with an independent will.",m:"laurel"},
  {a:"ソロー",w:"『ウォールデン 森の生活』",t:"私が森へ行ったのは、*意図的に*生きたいと思ったからだ。",x:"I went to the woods because I wished to live deliberately.",m:"candle"},
  {a:"エミリー・ブロンテ",w:"『嵐が丘』第九章",t:"彼は私以上に*私自身*なの。私たちの魂が何でできていようと、彼のと私のは同じもの。",x:"He's more myself than I am. Whatever our souls are made of, his and mine are the same.",m:"moon"},
  {a:"メルヴィル",w:"『白鯨』第一章",t:"私を*イシュメール*と呼んでくれ。",x:"Call me Ishmael.",m:"book"},
  {a:"ホイットマン",w:"『草の葉』「ぼく自身の歌」",t:"私は矛盾しているだろうか。よろしい、ならば私は矛盾している。私は大きい、私は*多数*を含んでいる。",x:"Do I contradict myself? Very well then I contradict myself, (I am large, I contain multitudes.)",m:"laurel"},
  {a:"ジョージ・エリオット",w:"『ミドルマーチ』終章",t:"世界の善が増していくのは、一部には*歴史に残らない行い*のおかげなのだから。",x:"For the growing good of the world is partly dependent on unhistoric acts.",m:"candle"},
  {a:"ボードレール",w:"『パリの憂鬱』「酔え」",t:"常に*酔って*いなければならない。",x:"Il faut être toujours ivre.",e:"One must always be drunk.",m:"moon"},
  {a:"ドストエフスキー",w:"『白痴』",t:"*美*が世界を救う。",x:"Красота спасёт мир.",e:"Beauty will save the world.",m:"lamp"},
  {a:"ドストエフスキー",w:"『カラマーゾフの兄弟』エピローグ",t:"何かしら*よい思い出*、とりわけ子どものころの思い出ほど、その後の人生にとって尊く、力強く、健やかで、有益なものはありません。",x:"Ничего нет выше и сильнее и здоровее и полезнее впредь для жизни, как хорошее какое-нибудь воспоминание, и особенно вынесенное ещё из детства.",e:"There is nothing higher, stronger, healthier, or more useful for later life than some good memory, especially one carried from childhood.",m:"candle"},
  {a:"トルストイ",w:"『アンナ・カレーニナ』第一部第一章",t:"幸福な*家庭*はどれも似たものだが、不幸な家庭はいずれもそれぞれに不幸である。",x:"Все счастливые семьи похожи друг на друга, каждая несчастливая семья несчастлива по-своему.",e:"All happy families are alike; each unhappy family is unhappy in its own way.",m:"book"},
  {a:"ディキンソン",w:"詩 314番",t:"「*希望*」は羽をもつもの ― 魂にとまり ―",x:"'Hope' is the thing with feathers – That perches in the soul –",m:"candle"},
  {a:"ルイス・キャロル",w:"『不思議の国のアリス』第六章",t:"「ここからどっちへ行けばいいか、教えてくださらない？」「それは、君が*どこへ行きたい*かによるね」",x:"\"Would you tell me, please, which way I ought to go from here?\" \"That depends a good deal on where you want to get to,\" said the Cat.",m:"book"},
  {a:"マーク・トウェイン",w:"『ハックルベリー・フィンの冒険』第三十一章",t:"よし、それなら、おれは*地獄*へ行こう。",x:"All right, then, I'll go to hell.",m:"laurel"},
  {a:"ニーチェ",w:"『ツァラトゥストラはこう語った』序説",t:"人間とは、*乗り越えられる*べき何ものかである。",x:"Der Mensch ist Etwas, das überwunden werden soll.",e:"Man is something that shall be overcome.",m:"laurel"},
  {a:"ニーチェ",w:"『ツァラトゥストラはこう語った』序説",t:"踊る*星*を産むためには、人は自分の内に混沌を持っていなければならない。",x:"Man muss noch Chaos in sich haben, um einen tanzenden Stern gebären zu können.",e:"One must still have chaos in oneself to give birth to a dancing star.",m:"moon"},
  {a:"ニーチェ",w:"『偶像の黄昏』",t:"生きる*なぜ*を持つ者は、ほとんどどんな「いかに」にも耐えられる。",x:"Hat man sein warum? des Lebens, so verträgt man sich fast mit jedem wie?",e:"He who has a why to live can bear almost any how.",m:"lamp"},
  {a:"ワイルド",w:"『ウィンダミア卿夫人の扇』第三幕",t:"われわれはみな溝の中にいる。だが、そのうちの何人かは*星*を見上げている。",x:"We are all in the gutter, but some of us are looking at the stars.",m:"moon"},
  {a:"ワイルド",w:"『ドリアン・グレイの肖像』序文",t:"すべての*芸術*は、まったく無用である。",x:"All art is quite useless.",m:"quill"},
  // ── 西洋（現代） ──
  {a:"アラン",w:"『幸福論』",t:"*悲観主義*は気分のものであり、楽観主義は意志のものである。",x:"Le pessimisme est d'humeur ; l'optimisme est de volonté.",e:"Pessimism is a matter of mood; optimism is a matter of will.",m:"lamp"},
  {a:"プルースト",w:"『失われた時を求めて』囚われの女",t:"唯一の本当の旅とは、新しい風景に向かうことではなく、*別の目*を持つことだろう。",x:"Le seul véritable voyage, ce ne serait pas d'aller vers de nouveaux paysages, mais d'avoir d'autres yeux.",e:"The only true voyage would be not to visit new landscapes, but to possess other eyes.",m:"book"},
  {a:"リルケ",w:"『若き詩人への手紙』",t:"あなたの心の中の未解決のものすべてに対して忍耐を持ち、*問いそのもの*を愛そうと努めてください。",x:"Geduld zu haben gegen alles Ungelöste in Ihrem Herzen und zu versuchen, die Fragen selbst liebzuhaben.",e:"Be patient toward all that is unsolved in your heart, and try to love the questions themselves.",m:"candle"},
  {a:"ヘッセ",w:"『デミアン』",t:"鳥は*卵*の中から抜け出ようと戦う。卵は世界だ。",x:"Der Vogel kämpft sich aus dem Ei. Das Ei ist die Welt.",e:"The bird fights its way out of the egg. The egg is the world.",m:"laurel"},
  {a:"アインシュタイン",w:"インタビュー（1929年）",t:"*想像力*は知識よりも重要である。",x:"Imagination is more important than knowledge.",m:"lamp"},
  {a:"ヘレン・ケラー",w:"『楽天主義』",t:"世界は苦しみに満ちているが、それを*乗り越えること*にも満ちている。",x:"Although the world is full of suffering, it is full also of the overcoming of it.",m:"candle"},
  {a:"ジョイス",w:"『ユリシーズ』第二挿話",t:"歴史とは、僕が目覚めようとしている*悪夢*だ。",x:"History is a nightmare from which I am trying to awake.",m:"hourglass"},
  {a:"ウルフ",w:"『自分ひとりの部屋』",t:"女性が小説を書こうと思うなら、お金と*自分ひとりの部屋*を持たねばならない。",x:"A woman must have money and a room of her own if she is to write fiction.",m:"quill"},
  {a:"カフカ",w:"オスカー・ポラック宛の手紙（1904年）",t:"本とは、われわれの内なる凍った海を砕く*斧*でなければならない。",x:"Ein Buch muß die Axt sein für das gefrorene Meer in uns.",e:"A book must be the axe for the frozen sea within us.",m:"book"},
  {a:"カフカ",w:"『変身』",t:"ある朝、グレゴール・ザムザが不安な夢から目を覚ますと、ベッドの中で自分が一匹の巨大な*虫*に変わっているのに気づいた。",x:"Als Gregor Samsa eines Morgens aus unruhigen Träumen erwachte, fand er sich in seinem Bett zu einem ungeheueren Ungeziefer verwandelt.",e:"As Gregor Samsa awoke one morning from uneasy dreams, he found himself transformed in his bed into a gigantic insect.",m:"book"},
  {a:"デール・カーネギー",w:"『道は開ける』",t:"*今日一日*の区切りで生きよ。",x:"Live in day-tight compartments.",m:"hourglass"},
  {a:"ヴィトゲンシュタイン",w:"『論理哲学論考』7",t:"語りえぬものについては、*沈黙*しなければならない。",x:"Wovon man nicht sprechen kann, darüber muß man schweigen.",e:"Whereof one cannot speak, thereof one must be silent.",m:"lamp"},
  {a:"トールキン",w:"『指輪物語』旅の仲間",t:"さまよう者すべてが、*道に迷って*いるわけではない。",x:"Not all those who wander are lost.",m:"moon"},
  {a:"フィッツジェラルド",w:"『グレート・ギャツビー』結び",t:"こうして我々は、*流れ*にさからう舟のように、絶えず過去へと押し戻されながら進んでいく。",x:"So we beat on, boats against the current, borne back ceaselessly into the past.",m:"hourglass"},
  {a:"ヘミングウェイ",w:"『老人と海』",t:"人間は*負ける*ようには造られていない。人間は滅ぼされることはあっても、負けることはない。",x:"But man is not made for defeat. A man can be destroyed but not defeated.",m:"laurel"},
  {a:"ボルヘス",w:"「天恵の詩」",t:"私はいつも、*楽園*とは図書館のようなものだと思い描いていた。",x:"Yo, que me figuraba el Paraíso bajo la especie de una biblioteca.",e:"I, who had always imagined Paradise as a kind of library.",m:"book"},
  {a:"サン＝テグジュペリ",w:"『星の王子さま』",t:"大切なものは、*目*に見えない。",x:"L'essentiel est invisible pour les yeux.",e:"What is essential is invisible to the eye.",m:"moon"},
  {a:"サン＝テグジュペリ",w:"『人間の土地』",t:"愛するとは、互いに見つめ合うことではなく、いっしょに*同じ方向*を見つめることだ。",x:"Aimer, ce n'est pas se regarder l'un l'autre, c'est regarder ensemble dans la même direction.",e:"Love does not consist in gazing at each other, but in looking outward together in the same direction.",m:"candle"},
  {a:"スタインベック",w:"『エデンの東』",t:"*ティムシェル* ― 汝、なしうる。",x:"Timshel — thou mayest.",m:"laurel"},
  {a:"オーウェル",w:"『1984年』",t:"自由とは、二足す二が四であると言える*自由*である。",x:"Freedom is the freedom to say that two plus two make four.",m:"lamp"},
  {a:"オーウェル",w:"『動物農場』",t:"すべての動物は平等である。だが、ある動物は他の動物より*もっと平等*である。",x:"All animals are equal, but some animals are more equal than others.",m:"book"},
  {a:"サルトル",w:"『実存主義とは何か』",t:"人間は*自由の刑*に処せられている。",x:"L'homme est condamné à être libre.",e:"Man is condemned to be free.",m:"lamp"},
  {a:"フランクル",w:"『夜と霧』",t:"問題なのは、私たちが人生に何を期待するかではなく、*人生*が私たちに何を期待しているかだ。",x:"Es kommt nie und nimmer darauf an, was wir vom Leben noch zu erwarten haben, vielmehr lediglich darauf: was das Leben von uns erwartet.",e:"It does not really matter what we expect from life, but rather what life expects from us.",m:"candle"},
  {a:"ボーヴォワール",w:"『第二の性』",t:"人は女に生まれるのではない、女に*なる*のだ。",x:"On ne naît pas femme : on le devient.",e:"One is not born, but rather becomes, a woman.",m:"lamp"},
  {a:"カミュ",w:"『シーシュポスの神話』",t:"*幸福なシーシュポス*を想像しなければならない。",x:"Il faut imaginer Sisyphe heureux.",e:"One must imagine Sisyphus happy.",m:"laurel"},
  {a:"カミュ",w:"『夏』「ティパサに帰る」",t:"冬のさなかに、私はついに、自分の内に*打ち負かしがたい夏*があることを知った。",x:"Au milieu de l'hiver, j'apprenais enfin qu'il y avait en moi un été invincible.",e:"In the midst of winter, I finally learned that there was in me an invincible summer.",m:"candle"},
  {a:"ガルシア＝マルケス",w:"『百年の孤独』冒頭",t:"長い歳月が流れて銃殺隊の前に立つはめになったとき、アウレリャノ・ブエンディア大佐は、父親に連れられて*氷*を見に行った遠い日の午後を思い出したにちがいない。",x:"Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo.",e:"Many years later, as he faced the firing squad, Colonel Aureliano Buendía was to remember that distant afternoon when his father took him to discover ice.",m:"book"},
  {a:"アンネ・フランク",w:"『アンネの日記』1944年7月15日",t:"それでもなお、私は人間の心が本当は*善*なのだと信じています。",x:"Ik geloof, ondanks alles, aan de innerlijke goedheid van de mens.",e:"In spite of everything, I still believe that people are really good at heart.",m:"candle"}
];
